### ISSUE TITLE
l10n - string clarification

### ISSUE THREAD

**Issue by p-bo** [LibreSign/libresign#1010]
To translate it correctly, would it be possible to clarify meaning of following string please?
https://github.com/LibreSign/libresign/blob/fa2486e3375e38b7a644e50e9716d3122e37ccd6/src/views/Settings/ConfigureCheck.vue#L38
Maybe it could be "check configuration" or "configuration check" (verb vs noun) or perhaps "configuration of check", if this has that meaning, etc.
Thanks :-)

**Comment by vitormattos** [comment]
It is the title of the section that contains the checklist of all necessaries to LibreSign work fine.

Under this title have a very small description.

![Screenshot_20221010_225626](https://user-images.githubusercontent.com/1079143/194979888-94c2eb53-8fa3-4454-ba4e-b3af1908d03f.png)
