### ISSUE TITLE
l10n: Context needed for string "Tip"

### ISSUE THREAD

**Issue by rakekniven** [LibreSign/libresign#1034]
https://github.com/LibreSign/libresign/blob/870206e1f83390bf5d217201d6756ef216c0f8a9/src/views/Settings/ConfigureCheck.vue#L9

Please enlight us.

Reported at Transifex. Please see https://www.transifex.com/nextcloud/nextcloud/translate/#zh_HK/libresign/439385935

**Comment by vitormattos** [comment]
This is a label of a column with the return of setup checklist.

Follow a screenshot explaining best the place:

![Screenshot_20221013_123932](https://user-images.githubusercontent.com/1079143/195642311-cf307e8d-a0a0-4793-bd8a-db2ee24b0036.png)

**Comment by vitormattos** [comment]
This is very sad, I created an issue #973 about comments in PHP files, but I don't know what we can do to fix this in vue files.

Do you know if the script that extract the text to transifex parse .vue files getting inside <script> tag?

**Comment by vitormattos** [comment]
@fantonialice started to implement comments in other places of code:
This was the first PR related with this: #1042
