### ISSUE TITLE
Some changes in validation page 

### ISSUE THREAD

**Issue by tasagore** [LibreSign/libresign#1076]
Hi

Think in this scenery:

1) I request TWO signers in a document
2) User A signs the document so a new document is generated and can be validated, user B does not sign the document

When I validate the document the validation page shows that the document is valid, signed by A in mm/dd/yyyy, no date for B

I suggest that the page should show a message indicating that the document is valid but it's not completed (until user B signs it). So if in the table oc_libresign_file the status is=1 the document should show a warning in the validation screen adverting that it's not completed.

Also in that page would be nice to have separated shapes for signed/unsigned, example, this is the standard page, the left signagture still is pending, the right one is signed:

![image](https://user-images.githubusercontent.com/54774469/196476301-f603f84c-7fab-458c-9702-de9a259502e0.png)

I guess this would be better:

![image](https://user-images.githubusercontent.com/54774469/196477722-9cbf3a65-080a-490d-aa27-9af35e793b4e.png)

Also should be fine to have the datetime in the sign:

![image](https://user-images.githubusercontent.com/54774469/196478450-423d373f-79dc-4749-a28f-66709399cfdb.png)

**Comment by vitormattos** [comment]
Hi @tasagore, excellent suggestions!

For now, we need funding to maintain the development of this project. We have a lot of ideas, but we don't have the necessary to maintain an engineer team and then, the dedicated time to the project is the free time of volunteers from community like you did to create this very cool UI suggestion.

We have a funding project in Patreon:
https://www.patreon.com/libresign

**Comment by tasagore** [comment]
I understand. For me this is one of the most important lack in Nextcloud and this app could be perfect to solve it.

I'm a developer but not in web environments and my knowledge in JS is near zero, anyway here is a piece of code if it helps. To separate signed from unsigned in validation screen just change in validation.vue from this:

`<div class="infor-bg signed">
						<div class="header">
							<img class="icon" :src="signatureIcon">
							<h1>{{ t('libresign', 'Signatories:') }}</h1>
						</div>
						<div class="infor-content">
							<div v-for="item in document.signers"
								id="sign"
								:key="item.fullName"
								class="scroll">
								<div class="subscriber">
									<span><b>{{ getName(item) }}</b></span>
									<span v-if="item.signed" class="data-signed">{{ formatData(item.signed) }} </span>
									<span v-else>{{ noDateMessage }}</span>
								</div>
							</div>
						</div>
					</div>`

to this:

`<div class="infor-bg signed">
						<div class="header">
							<img class="icon" :src="signatureIcon">
							<h1>{{ t('libresign', 'Signatories:') }}</h1>
						</div>
						<div class="infor-content">
							<div v-for="item in document.signers">													
								<div v-if="item.signed"
									id="sign"
									:key="item.fullName"
									class="scroll">
									<div class="subscriber">
										<span><b>{{ getName(item) }}</b></span>
										<span class="data-signed">{{ formatData(item.signed) }} </span>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="infor-bg signed">
						<div class="header">
							<img class="icon" :src="signatureIcon">
							<h1>{{ t('libresign', 'Pending signatures:') }}</h1>
						</div>
						<div class="infor-content">
							<div v-for="item in document.signers">
								<div v-if="item.signed"></div><div v-else 
									id="sign"
									:key="item.fullName"
									class="scroll">
									<div class="subscriber">
										<span><b>{{ getName(item) }}</b></span>
										<span class="data-signed">{{ noDateMessage }} </span>
									</div>
								</div>
							</div>
						</div>
					</div>	`

After that the validation page will show like this:

![image](https://user-images.githubusercontent.com/54774469/197017789-d15395be-f842-4841-8781-e7a200fb725e.png)

**Comment by vitormattos** [comment]
Excellent!
Could you send in a new PR to make easier the review, or, maybe, allow to other person follow in your change?

**Comment by tasagore** [comment]
> Excellent!
> Could you send in a new PR to make easier the review, or, maybe, allow to other person follow in your change?

I'll take a look to the Github PRs since I don't use GitHub in my job. The first think I did was clone the repository and edit it with VS-Code but the version was 7.0.0 (that doesn't work in NC25) so I did the mod over the 5.1.4 version that seems the latests stable. 

I guess I need to read more about the Github stuff and JS before I can help, but I'll do.

Also I'm working in let request signature for username, not only for email (in my case all signatures are internals), don't know if it's a feature already implemented in future releases.

**Comment by vitormattos** [comment]
About the development, need to be made in main branch of LibreSign. The main branch work with master branch of server.

I recommend using a development environment to do this.

I use this environment:
github.com/librecodecoop/nextcloud-docker-development
But have a lot of app developers that use this:
https://github.com/juliushaertl/nextcloud-docker-dev/

You will need to clone the main branch of LibreSign in app folder and inside `libresign` folder, run the command `make serve`, this will install all composer and javascript dependencies and start the watch mode. To run the watch mode again, you could run `npm run watch` or  `make watch-js`

**Comment by vitormattos** [comment]
Could you test the newest release?! This is a screenshot of newest release:

![Screenshot_20240424_111209](https://github.com/LibreSign/libresign/assets/1079143/fd75bb17-889b-4eb2-b412-388f7301d6e5)

PS: If you like this app, don't hesitate to help us to maintain the development sponsoring by GitHub sponsor https://github.com/sponsors/LibreSign or also contacting us to have Enterprise support: https://libresign.coop
