### ISSUE TITLE
Command libresign:configure:cfssl don't work

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/libresign#1108]
**Describe the bug**
The command `libresign:configure:cfssl` don't work more after this PR: #1105 because the [arguments](https://github.com/LibreSign/libresign/blob/main/lib/Service/InstallService.php#L513-L514) were changed from strings to an array.

**To Reproduce**
- Install Nextcloud
- Install LibreSign (suggestion: `occ app:install libresign`)
- Run the command `occ libresign:configure:cfssl` with all necessary options, use `--help` to see the options and you can use random values as options
- Will get error:
  ```
  An unhandled exception has been thrown:
  TypeError: Argument 2 passed to OCA\Libresign\Service\InstallService::generate() must be of the type array, string given, called in /var/www/html/apps/libresign/lib/Command/Configure/Cfssl.php on line 101 and defined in /var/www/html/apps/libresign/lib/Service/InstallService.php:520
  ```

**to do**
- [ ] Add the new options listed in the follow code to this command:
https://github.com/LibreSign/libresign/blob/main/src/views/Settings/RootCertificate.vue#L191-L195
https://github.com/LibreSign/libresign/blob/main/lib/Handler/CfsslHandler.php#L86-L116
The new option need to be added like this:
https://github.com/LibreSign/libresign/blob/main/lib/Command/Configure/Cfssl.php#L34-L39
- [ ] Add new validation to new options like this:
https://github.com/LibreSign/libresign/blob/main/lib/Command/Configure/Cfssl.php#L70-L72
- [ ] Change the arguments of this method https://github.com/LibreSign/libresign/blob/main/lib/Command/Configure/Cfssl.php#L100-L108 to new pattern: https://github.com/LibreSign/libresign/blob/main/lib/Service/InstallService.php#L513-L514

**Comment by TahomaSoft** [comment]
I think this is linked to issue #1157

**Comment by vitormattos** [comment]
Install the newest release compatible with stable25 and do a new test.
