### ISSUE TITLE
405 (Method Not Allowed) in /index.php/apps/libresign/api/0.1/admin/configure-check 

### ISSUE THREAD

**Issue by Bolli84** [LibreSign/libresign#1127]
After installing Libresign 5.2.1 i want to go to the Admin panel.

The panel is loaded but the console error: "/index.php/apps/libresign/api/0.1/admin/configure-check  405 (Method Not Allowed)" rises and the "check configure" section is not filled.

In addition, the "Download binaries" Button is not clickable.

However, the signing with the existing setup, which was used also earlier, does work correctly.

**Comment by vitormattos** [comment]
Other point, during the configure-check, did you receive any error message in your nextcloud.log file?

**Comment by vitormattos** [comment]
The condition to the button stay disabled is only one: have a download in progress.

If you haven't a download in progress, I think that you got any JavaScript error.

**Comment by Bolli84** [comment]
It is an existing installation updated by web-update
The Log has no further information.

Might it be an issues with the cfssl started in another user than nextcloud with no access from nextcloud user to it instead of API

**Comment by vitormattos** [comment]
I identified this problem yesterday and already did the fix: https://github.com/LibreSign/libresign/pull/1117
You can fix the appsetting  `rootCert` according to the mentioned PR directly in your database, or wait for the next release.

**Comment by Bolli84** [comment]
Could you please explain, where to include the app-setting? I do not find in in neither files nor database.

**Comment by Bolli84** [comment]
I used to build everything with the OCC commands and it has everything now and no further open things in the configuration.
