### ISSUE TITLE
occ libresign:configure:check returns an error

### ISSUE THREAD

**Issue by kmorber** [LibreSign/libresign#1144]
Hello,

i receive the following error on the command mentioned above:

FEIN Default property file doesn't exists.
FEIN Default property file doesn't exists.
An unhandled exception has been thrown:
Error: Class 'Symfony\Component\Console\Helper\TableCellStyle' not found in /var/www/html/nextcloud/apps/libresign/lib/Command/Configure/Check.php:71
Stack trace:
#0 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Libresign\Command\Configure\Check->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/html/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Libresign\Command\Configure\Check), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#7 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')

What am i doing wrong?

Best regards

**Comment by vitormattos** [comment]
Could you provide the version of LibreSign and the version of Nextcloud Server?

**Comment by kmorber** [comment]
Nextcloud 24.0.7
libresign 5.2.1

**Comment by tasagore** [comment]
Same here but the error changes from "FEIL" to "DETALLADO", all other lines exactly as yours:

DETALLADO Default property file doesn't exists.
...

**Comment by vitormattos** [comment]
Fixed with: https://github.com/LibreSign/libresign/pull/1184
Wait the next release

**Comment by vitormattos** [comment]
Install the newest release compatible with stable25 and do a new test.
If the problem persist, reopen this issue.
