### ISSUE TITLE
 Group-folders are not found by libresign to be used

### ISSUE THREAD

**Issue by Bolli84** [LibreSign/libresign#1147]
Bigger installations with collaboration use "group-folders" to achive a good file seggregation.
Whenever you have a group folder used, libresign cannot find the file and is not able to create signature workflows or signing them.

Only in case, a particular folder is shared, Libresign is abel to detect the folder and sign the file.

Correct behaviour:
* The file should be recognized independtly from its location and the flows should work accordingly.

**Comment by iMartien** [comment]
Just wanted to add I have the same issue running Nextcloud 25.0.2 on ubuntu 22.04. When you move the document out of a Group Folder it wil also work.

**Comment by vitormattos** [comment]
Fixed on release 6.2.4
