### ISSUE TITLE
Error when I try to execute cfssl config

### ISSUE THREAD

**Issue by Iwios** [LibreSign/libresign#1157]
**Describe the bug**
When I try to launch `occ libresign:configure:cfssl` I have this return :

An unhandled exception has been thrown:
TypeError: Argument 6 passed to OCA\Libresign\Service\InstallService::generate() must be of the type string, null given, called in /var/www/html/nextcloud/apps/libresign/lib/Command/Configure/Cfssl.php on line 101 and defined in /var/www/html/nextcloud/apps/libresign/lib/Service/InstallService.php:512
Stack trace:
#0 /var/www/html/nextcloud/apps/libresign/lib/Command/Configure/Cfssl.php(101): OCA\Libresign\Service\InstallService->generate()
#1 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Libresign\Command\Configure\Cfssl->execute()
#2 /var/www/html/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#3 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#4 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#5 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#6 /var/www/html/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#7 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#8 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#9 {main}

**To Reproduce**
- Launch this command line : `sudo -u user_with_right_to_execute php occ libresign:configure:cfssl --cn Mycompany --ou IT -o Mycompany -c France`

And when I try to execute the same thing in the web interface I have this : 

Impossible de générer le certificat.
Endpoint /health of CFSSL server not found. Maybe you are using incompatible version of CFSSL server. Use latests version.

![image](https://user-images.githubusercontent.com/94412636/199540563-2c7a7426-32e6-49a9-b094-48a005b0af65.png)

Havr a good day

**Comment by TahomaSoft** [comment]
I've been looking at the code for the various parts of LibreSign's cfssl code, and there are internal inconsistencies on the data structures between routines.

**Comment by Iwios** [comment]
Hello,
Ok and this is possible to show here the inconsistencies?

**Comment by TahomaSoft** [comment]
See also:
https://github.com/LibreSign/libresign/issues/1108

**Comment by vitormattos** [comment]
Install the newest release compatible with stable25 and do a new test.
If the problem persist, reopen this issue.
