### ISSUE TITLE
CFSSL not configured.	

### ISSUE THREAD

**Issue by mankelars** [LibreSign/libresign#1162]
<img width="1378" alt="Bildschirmfoto 2022-11-07 um 09 10 49" src="https://user-images.githubusercontent.com/45971372/200258908-0d8da84a-3209-434e-bb66-7f126edfbb77.png">
Good day,

I would like to use LibreSign on a VPS Ubuntu 20.04 LTS 64bit Linux.

Unfortunately, the following message appears under configuration: CFSSL not configured.

I already ran the command and didn't get an error message.

Can someone help me?

**Comment by lhsazevedo** [comment]
Hi @mankelars, please try running `occ libresign:configure:cfssl` instead.

**Comment by vitormattos** [comment]
Looking more to down is possible to see the form to configure the root certificate.
