### ISSUE TITLE
CFSSL binaries not found, but exist

### ISSUE THREAD

**Issue by tasagore** [LibreSign/libresign#1164]
NC 24 with Libresign 5.2.1, if I try to create a signature password it fails.

NC Log:

`{"reqId":"uDVaKvOK3wCpq9vw3JNC","level":3,"time":"2022-11-07T18:13:01+00:00","remoteAddr":"192.168.100.20","user":"test","app":"libresign","method":"POST","url":"/nextclou
d/index.php/apps/libresign/api/0.1/account/signature","message":"Binary of CFSSL not found. Install binaries.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWeb
Kit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15","version":"24.0.6.1","data":{"app":"libresign"}}`

Libresign app configuration (all success, including CFSSL binaries):

<img width="936" alt="image" src="https://user-images.githubusercontent.com/54774469/200386047-21d73646-a3cf-4112-a982-e7fdc19afe9e.png">

CFSSL binary can be executed in the path:

_root@testserver:/data/nc_nextcloud/appdata_ocklbg8wjsur/libresign# sudo -u www-data ./cfssl
No command is given.
Usage:
Available commands:_
...

**Comment by vitormattos** [comment]
Install the newest release compatible with stable25 and do a new test.
If the problem persist, reopen this issue.

Id did changes in setup flow.
