### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by mikweb2017** [LibreSign/libresign#120]
App "LibreSign" cannot be installed because the following dependencies are not fulfilled: The command line tool java could not be found

kann you help me?

**Comment by vitormattos** [comment]
Hi @mikweb2017!

Follow setup instructions in the README.md of this project.

LibreSign has a few requirements to work.

**Comment by vitormattos** [comment]
Still in time...

At the moment the start point of flow to file signature requests must be requested via webhook.

**Comment by Bolli84** [comment]
Running into the same issue. Java is installed correctly and can be found be bash. However, the web-service used in nextcloud does not find the link to java, as it is not the path

**Comment by mikweb2017** [comment]
I do not know but a more detailed guide would be appreciated

**Comment by vitormattos** [comment]
The Java dependency is validated by the [info.xml](https://github.com/LibreSign/libresign/blob/main/appinfo/info.xml#L21) file which checks if the java command exists.

You must have java installed and also need jsignpdf on this path:
https://github.com/LibreSign/libresign/blob/main/lib/Handler/JLibresignHandler.php#L21

JSignPDF is run using the jsignpdf/jsignpdf-php package which is a wrapper for JSignPDF and it needs the `java` command to be accessible by bash:
https://github.com/JSignPDF/jsignpdf-php/blob/b84fc9919cf1bab0792a9aa493abc102b1cf9d66/src/Sign/JSignService.php#L63

One option to resolve the dependency on Java and JSignPDF is to run the composer install `jsignpdf/jsignpdf-bin` command in the root of the libresign folder https://github.com/JSignPDF/JSignPDFBin. This package has the java and jsignpdf binaries. The project does not include these binaries so as not to make a very large installation file.

The instructions to be applied to a Dockerfile can also be executed on any Debian-based Linux system.

**Comment by Bolli84** [comment]
Still, after a few hours with it, is does not work. I went to the exact path. Java is executable there and the user is correct. 
JSignPDF is on the correct place.

openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

It would be great to have that more clearly defined, since I assume the valueable work will not be brought into scale.

**Comment by vitormattos** [comment]
What exactly is not working? Without details of what exactly is going on I can't help you.

* Were you able to install and enable the app?
* Are there any LibreSign logs in the Nextcloud log file?
* In the Nextcloud security settings, as described in the documentation, was the LibreSign configuration data filled in and did it not give an error when saving?
* Is the CFSSL service entrypoint.sh implemented as described in the documentation?
* Is the CFSSL service up?
* Is the CFSSL service API accessible?
* When saving LibreSign settings, the configuration files for this service are saved in the CFSSL folder. If the LibreSign configuration is correct, there will be no error when saving these settings, there will be no messages in the Nextcloud log and the CFSSL folder should have a list like this: `ca.csr ca-key.pem ca.pem config_server.json csr_server.json entrypoint.sh` and the CFSSL service should be UP. These configuration steps are described in the documentation.

**Comment by Bolli84** [comment]
Still the same issue as initially of this report. 
App cannot be enabled, because "java" is not found.

**Comment by vitormattos** [comment]
This verification is done by Nextcloud itself. In the [`info.xml`](https://github.com/LibreSign/libresign/blob/main/appinfo/info.xml#L21) file there is a section to inform the commands that are required for the app to work.

For some reason the user that PHP is running (usually `www-data`) is not finding the `java` command on the operating system.

It is not a good way because I imagine that PHP is not able to execute the command java, but to test it you can remove this line of verification from the file `info.xml` and check if you can sign files.

Java and jsignpdf are used to sign PDF files.

Remembering that in the current version the start of the signature flow can only be requested via API informing the file to be signed and all the people who will sign. From then on, people receive invitation emails to sign and sign on LibreSign.

**Comment by vitormattos** [comment]
Soon it will be possible for a Nextcloud user to be able to request the signature of a PDF without having to do this directly through the API.

**Comment by Bolli84** [comment]
Here is my step by step, which does not result in anything working:

1. Removed the "java command" from info.xml: App is not downloaded and enabled.
2. Logged into ssh
3. Going to the nextcloud-libresign-folder
4. Create the docker-compose.yml with this content:
`  cfssl:
    image: cfssl/cfssl
    volumes:
      - ./cfssl:/cfssl
    working_dir: /cfssl
    entrypoint: /bin/bash
    command:
      - /cfssl/entrypoint.sh
`

3. Docker-compose pull cfssl
4.  start the docker "docker-compose up"
5. Docker responds with: Creating libresign_cfssl_1 ... done
Attaching to libresign_cfssl_1
cfssl_1  | no csr_server.json or config_server.json detected!

6. log into nextcloud admin in security and fill the form as on the libresignpage but with http://libresign_cfssl_1:8888/api/v1/cfssl/ as API
7. try no create certificate
8. Message "could not generate certificate" appears
9. Nextcloud issue logs: file_put_contents(/cfsssl/csr_server.json): failed to open stream: No such file or directory at ##locationofnextcloud##/apps/libresign/lib/Handler/CfsslServerHandler.php#53 
file_put_contents(/cfsssl/csr_server.json): failed to open stream: No such file or directory at ##locationofnextcloud##/apps/libresign/lib/Handler/CfsslServerHandler.php#53

So, it seems to be more explaination needed.

**Comment by vitormattos** [comment]
If the app was not downloaded and enabled, how did you manage to do the other steps?

Nextcloud checks the necessary commands in the step of enabling an app. There are no restrictions on downloading.

> Removed the "java command" from info.xml: App is not downloaded and enabled.

I didn't understand what you did in these steps. These CFSSL service instructions are for those who have Nextcloud working with `docker-compose.yml`. For those who do not have it, it is necessary to follow the CFSSL service setup instructions as they appear on the CFSSL project page, there is a link to the project page in the LibreSign README.

> Logged into ssh
> 
> Going to the nextcloud-libresign-folder
> 
> Create the docker-compose.yml with this content:
> ...

Did you do this step?

* Add the volume `./cfssl:/cfssl` in Nextcloud service

> Create the docker-compose.yml with this content:

The `cfssl` folder needs to be a volume inside the container and informed in `config path` in `Settings > Basic Settings`

> Docker responds with: Creating libresign_cfssl_1 ... done
Attaching to libresign_cfssl_1
cfssl_1 | no csr_server.json or config_server.json detected!

> Nextcloud issue logs: file_put_contents(/cfsssl/csr_server.json): failed to open stream: No such file or directory at ##locationofnextcloud##/apps/libresign/lib/Handler/CfsslServerHandler.php#53
file_put_contents(/cfsssl/csr_server.json): failed to open stream: No such file or directory at ##locationofnextcloud##/apps/libresign/lib/Handler/CfsslServerHandler.php#53

**Comment by Bolli84** [comment]
So, your set of instruction only works, if nextcloud runs as a docker container? 
The conventional setup does not align with the instructions?

Can you write the detailed instruction as well for conventional setups?

**Comment by Bolli84** [comment]
OK, I got the CFSSL running.  This might be useful for others

Installing cfssl it on a normale framework:

$ go get -u github.com/cloudflare/cfssl/cmd/cfssl

Start the cfssl server:
./cfssl serve -address=IP-of-your-server

Check if server is up:
http://IP-of-your-server:8888/api/v1/cfssl/scaninfo

Then, you can generate the certificate in the admin settings. (What is the configpath for?)

Then, I go to "libresign" and cannot create the subscription.
How does the subscription creation work? maybe i can find it out, how to solve my issue for others.

**Comment by vitormattos** [comment]
I did not do the CFSSL server setup manually, only with Docker but reading the documentation of CFSSL the certificates are in this folder:
`/etc/ssl/certs/`
You can put it in the `Config path` in [LibreSign settings](https://github.com/LibreSign/libresign#admin-settings)

The [`entrypoint.sh`](https://github.com/LibreSign/libresign/blob/main/cfssl/entrypoint.sh) script you must [adapt](https://github.com/cloudflare/cfssl#starting-the-api-server) to your environment without a Docker.

**Comment by Bolli84** [comment]
Fixed it :-)

create a little file called csr.json:

    "CN": "YOU",
    "names": [
        {
            "C":  "Germany",
            "L":  "Germany",
            "O":  "Orga",
            "OU": "Where Org",
            "ST": ""
        }
    ]
}

Then create the certificates:
./cfssl genkey -initca csr.json | ./cfssljson -bare ca

then start the serve:
./cfssl serve -ca=ca.pem -ca-key=ca-key.pem -address=SERVER-ip&

Then, it works all fine.

**Comment by vitormattos** [comment]
This file is generated by LibreSign itself when you save LibreSign settings and saved in the folder informed in `Config path`

An example of how cfssl server starts is in `entrypoint.sh`

**Comment by Bolli84** [comment]
Tutorial to make the cfssl available on the linux without docker:

**1. Installing cfssl:**

`$ go get -u github.com/cloudflare/cfssl/cmd/cfssl`

**2. Create a file called csr.json in any folder you want:**

```
{
"CN": "YOU",
"names": [
    {
        "C":  "Germany",
        "L":  "Germany",
        "O":  "Orga",
        "OU": "Where Org",
        "ST": ""
    }
]
}
```

**3. Create the Certificates:**
`./cfssl genkey -initca csr.json | ./cfssljson -bare ca`

**4. Start the cfssl server:**
`./cfssl serve -ca=/path/to/cert/ca.pem -ca-key=/path/to/cert/ca-key.pem -address=SERVER-ip&`

**5. Check if server is up:**
`http://IP-of-your-server:8888/api/v1/cfssl/scaninfo`

Then, you can generate the certificate in the admin settings.
The "csr_server.json " and "config_server.json" is created in the configpath folder.

**Comment by vitormattos** [comment]
Step 2 is done automatically when set the data in the LibreSign settings. When saving the settings, this configuration file is generated.

**Comment by xtc218** [comment]
> Tutorial to make the cfssl available on the linux without docker:
> 
> **1. Installing cfssl:**
> 
> `$ go get -u github.com/cloudflare/cfssl/cmd/cfssl`
> 
> **2. Create a file called csr.json in any folder you want:**
> 
> ```
> {
> "CN": "YOU",
> "names": [
>     {
>         "C":  "Germany",
>         "L":  "Germany",
>         "O":  "Orga",
>         "OU": "Where Org",
>         "ST": ""
>     }
> ]
> }
> ```
> 
> **3. Create the Certificates:**
> `./cfssl genkey -initca csr.json | ./cfssljson -bare ca`
> 
> **4. Start the cfssl server:**
> `./cfssl serve -ca=/path/to/cert/ca.pem -ca-key=/path/to/cert/ca-key.pem -address=SERVER-ip&`
> 
> **5. Check if server is up:**
> `http://IP-of-your-server:8888/api/v1/cfssl/scaninfo`
> 
> Then, you can generate the certificate in the admin settings.
> The "csr_server.json " and "config_server.json" is created in the configpath folder.

i follow your steps but, when i try to run ./cfssl serve -ca=/path/to/cert/ca.pem -ca-key=/path/to/cert/ca-key.pem -address=SERVER-ip&
i got this error:  
./cfssl is a directory
./cfssljson is a directory

any idea of how i can run it?

**Comment by xtc218** [comment]
Hi, i need help, when i try to generate my certs via nextcloud UI i get an error.
The error is: 

Error: Undefined property: OCA\Libresign\Controller\AdminController::$service at /var/www/html/apps/libresign/lib/Controller/AdminController.php#74
/var/www/html/apps/libresign/lib/Controller/AdminController.php - line 74:

OC\Log\ErrorHandler::onError()

/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 218:

OCA\Libresign\Controller\AdminController->loadCertificate()

/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 127:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/html/lib/private/AppFramework/App.php - line 157:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/html/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/var/www/html/lib/base.php - line 993:

OC\Route\Router->match()

/var/www/html/index.php - line 37:

OC::handleRequest()


Anyone can help me?

**Comment by vitormattos** [comment]
@xtc218 update your LibreSign

**Comment by xtc218** [comment]
My Libresign version is the latest: 2.1.2

**Comment by vitormattos** [comment]
Not, the latest version is 2.2.0

**Comment by xtc218** [comment]
Ok, i'll update the app but i get the same error.

**Comment by vitormattos** [comment]
Line 74 of the AdminController file is no longer this long ago.

The error log is out of date or LibreSign has not been updated.

**Comment by RenataAmoedo** [comment]
This issue is being closed due lack of interaction. 

If the issue persists, fell free to open a new one, we'll be pleased to help.

Thank you!

**Comment by sollermun** [comment]
> One option to resolve the dependency on Java and JSignPDF is to run the composer install [`jsignpdf/jsignpdf-bin`](https://github.com/JSignPDF/JSignPDFBin) command in the root of the libresign folder. 

I am trying to install this without using Docker. I've run "composer require jsignpdf/jsignpdf-bin" and it seemingly installs fine. 

Java is accessible through bash.

However, when I try to install the app it still says "The command line tool java could not be found"
