### ISSUE TITLE
Cannot sign on android devices.

### ISSUE THREAD

**Issue by cabaseira** [LibreSign/libresign#1221]
When I use an android device and I am about to sign a document, the browser does not show the PDF on the screen. Instead, try to download it to the device.

Tested on:
Tablet -> Samsung Tab S7 with OneUI 5.0 and Android 13.
Smartphone -> Samsung S22+ with OneUI 5.0 and Android 13.

Using Nextcloud 25.0.1 (in docker container) with Libresign 6.1.2

**Comment by vitormattos** [comment]
Fixed by https://github.com/LibreSign/libresign/pull/1242
