### ISSUE TITLE
Error signing on android mobile devices.

### ISSUE THREAD

**Issue by cabaseira** [LibreSign/libresign#1263]
**Describe the bug**
When I try to sign a document on an android mobile device (tablet or smartphone), I encounter two possible errors:
1 - When I place the visible areas for the signature, the "Save" button does not work by pressing my finger on the screen, it only works if I use a mousse.
2 - When I click on the "Sign" button, the browser downloads the document to the device instead of showing it in the browser itself to sign.

**To Reproduce**
- I'm an authenticated user
- I open a document in LibreSign
- Click on "Request".
- I enter my own email and press "Add"
- Click on "Submit Request"
- Click on "OK" to place the visible elements.
- I place the position of my signature.
- I can't press "Save" with my finger, only with the mousse.
- Also, click "Save" to continue the process.
- Click on "Request", and "OK" in the pop-up menu.
- I click on "Sign" and the browser downloads the PDF instead of showing it to sign.

**Screenshots**
Video: https://oficina.deados.es/s/libresign

**Environment information (please complete the following information):**
 - OS: Tested on Samsung devices with OneUI 5 and Android 13
 - Browser: Tested on Google Chrome, Mozilla Firefox and Samsung Internet Browser
 - LibreSign Version 6.2.0
 - Nextcloud Server Version 25.0.1

**Comment by tasagore** [comment]
Seems that your device is configured to not show the PDFs in the browser, I have another app configured in that way and that's the behavior I get.

**Comment by cabaseira** [comment]
Hi!
Thanks for your answer.
I can do this browser modification on a PC, but I don't know how to do it on an android device.
Could you tell me the procedure?

Un saúdo!

**Comment by cabaseira** [comment]
@tasagore @vitormattos 
After many tests with different web browsers for android, no stable browser works.
I have only managed to get it to work well with the **nightly version of Firefox** and installing a specific extension for PDF.
The steps I have followed are the following:

1. Install Firefox nightly for developers: [https://play.google.com/store/apps/details?id=org.mozilla.fenix](url)
2. Follow these instructions to create a collection: [https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/](url)
3. Enter the **PDF.js** extension page and add it to the collection you just created: [https://addons.mozilla.org/es/firefox/addon/android-pdf-js/](url)

From here LibreSign can already display the PDF at the time of signing. Additionally, I have to put my device in a horizontal position (landscape) to be able to click on the "Sign" button. Otherwise, it is not displayed on the screen.

Since I don't have much development knowledge, I don't know if we can conclude that this is not a LibreSign bug, or if we can still consider it a bug, or a possible improvement. Maybe it's an Android problem.

**Comment by cabaseira** [comment]
I correct myself. It is only necessary to install Firefox nightly for developers. Without doing anything else, it works.
In the other hand, I can't see the sign button on a smartphone, I can only see it in landscape on a tablet. Enough for me.

**Comment by tasagore** [comment]
Actually Libresing can't be used on mobile devices mainly because the page does not fit in the screen and the document can't be viewed/signed, I've opend a issue for that but was closed. I've tested in iOS, different Android devices, desktop browsers with mobile profile and nothing works. The tablet has bigger screen and probably it will work.

**Comment by vitormattos** [comment]
Could you validate at newest release?

For now I will close this issue because I made a lot of visual changes.

PS: If you like this app, don't hesitate to help us to maintain the development sponsoring by GitHub sponsor https://github.com/sponsors/LibreSign or also contacting us to have Enterprise support: https://libresign.coop

**Comment by cabaseira** [comment]
I can confirm that it works on mobile devices in LibreSign 8.0.0 
Tested on Nextcloud 28.0.4, with a Samsung Tab S7 (Android 13) and with a Samsung S22+ (Android 14)
Thank you!!

**Comment by vitormattos** [comment]
It's the party time! very happy with your comment!

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
