### ISSUE TITLE
Libresign not working with Files stored on External Storage

### ISSUE THREAD

**Issue by AlessandroDM** [LibreSign/libresign#1274]
**Describe the bug**
Submitting a request to sign after selecting a file stored inside external storage produces the error
"File not found on specified place"

Requests submitted with files stored inside nextcloud storage are processed without error.

**To Reproduce**
Select From Files (choose from External Storage)
Submit for signature

**Expected behavior**
Should allow signing documents regardless where they are stored.

Thank you

**Comment by vitormattos** [comment]
Fixed on release 6.2.4
