### ISSUE TITLE
search existing  secondary emails  for existing users and use it when it is validated

### ISSUE THREAD

**Issue by unnilennium** [LibreSign/libresign#1281]
**Is your feature request related to a problem? Please describe.**
sometimes nextcloud gets its main email from a ldap directory, and this is not the main email used for a user of  our cloud.
If you use the main email, then when user connect he can sign.

When you use an alternative email when he clicks the email he get a 404 error as he is already logged in, if he loggs out he his asked to register.
If he tried to sign the email from the file interface he is not proposed to sign

**Describe the solution you'd like**

search for all altenates email that are validated for the user and allow to sign for thoses.

**Comment by vitormattos** [comment]
For now only is possible sign a document using the main email of an user. When you use an email different of main email will return 404.

**Comment by l4b4r4b4b4** [comment]
I get an error when using the mail email of an LDAP synced user. Regardless it being the main mail of the user! Or is this a general thing with LDAP users?

**Comment by vitormattos** [comment]
Was made a lot of changes at this point and now is possible send a request to sign to a non account email.

You can change at `Administration Settings > LibreSign`

![Screenshot_20240424_110624](https://github.com/LibreSign/libresign/assets/1079143/4a7966b9-393e-4a14-ad83-5bc344c6628f)

Also is possible search by users and contacts when request to sign a new document. At the follow screenshot, the login of John Doe's account is `admin`:

![Screenshot_20240424_112131](https://github.com/LibreSign/libresign/assets/1079143/28d262a3-62d8-4669-8828-3b6eab46a1e7)


For now I will close this issue.

PS: If you like this app, don't hesitate to help us to maintain the development sponsoring by GitHub sponsor https://github.com/sponsors/LibreSign or also contacting us to have Enterprise support: https://libresign.coop
