### ISSUE TITLE
Unable to change sign method.

### ISSUE THREAD

**Issue by jhjacobs81** [LibreSign/libresign#1301]
**Describe the bug**
I am trying to change the sign method from password to email. however this returns an error:
An unhandled exception has been thrown:
Error: Call to undefined function simplexml_load_file() in /var/www/nextcloud/lib/private/App/InfoParser.php:69
Stack trace:
#0 /var/www/nextcloud/lib/private/App/AppManager.php(506): OC\App\InfoParser->parse()
#1 /var/www/nextcloud/lib/private/legacy/OC_App.php(595): OC\App\AppManager->getAppInfo()
#2 /var/www/nextcloud/lib/private/AppFramework/App.php(74): OC_App::getAppInfo()
#3 /var/www/nextcloud/lib/private/legacy/OC_App.php(280): OC\AppFramework\App::buildAppNamespace()
#4 /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(117): OC_App::registerAutoloading()
#5 /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(91): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#6 /var/www/nextcloud/lib/base.php(654): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#7 /var/www/nextcloud/lib/base.php(1104): OC::init()
#8 /var/www/nextcloud/console.php(48): require_once('...')
#9 /var/www/nextcloud/occ(11): require_once('...')

**To Reproduce**
- I log in to the terminal to execute the occ command
- I run sudo -u www-data php occ config:app:set libresign sign_method --value=email

**Expected behavior**
I expected the command to be executed successfully

**Screenshots**

**Environment information (please complete the following information):**
 - OS: Ubuntu 21.10
 - LibreSign Version: Latest version
 - Nextcloud Server Version: 24.0

**Comment by vitormattos** [comment]
The function simplexml_load_file is part of extension php-xml. Install this extension.

**Comment by vitormattos** [comment]
I will close this issue because isn't a problem of LibreSign. This is a dependency of Nextcloud Server repository.
