### ISSUE TITLE
Change QR size/position?

### ISSUE THREAD

**Issue by tasagore** [LibreSign/libresign#1305]
Hi

How can be changed the QR size and position? The latest version uses a too big QR Code and I can't find any setting to change it. Also the QR is always located at down-left, anyway to choose any other position like upper right?

I guess both can be changed modifying the lib/Handler/Pkcs12Handler.php but the changes would be overwritten in futures updates.

Regards

**Comment by vitormattos** [comment]
For now isn't possible do this without changing the code.

Would be possible to implement an WYSIWYG editor to define the text that will be added to footer and put a special tag to add the QRCode. But, this is a new feature and to do this will be necessary help the developers funding the project.
