### ISSUE TITLE
Tables not being created in DB

### ISSUE THREAD

**Issue by tonytonyistony** [LibreSign/libresign#1306]
**Describe the bug**
After manually deleting libresign tables #1302 from MariaDB, reinstalling the app does not recreated the DB tables. Because of this an error is being generated 
`An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_libresign_file' doesn't exist`

**To Reproduce**
- Uninstall app
- Enter MariaDB as root
- Select nextcloud DB
- Drop all tables related to libresign
- reinstall libresign
- clear cache
- run app check
- install binaries and generate new cert
- Upload PDF and try to send signing request to user.

**Expected behavior**
DB tables get regenerated

**Environment information (please complete the following information):**
 - OS: Ubuntu 20.04.5
 - Browser: Vivaldi & Firefox
 - LibreSign Version: 6.2.2
 - Nextcloud Server Version: Nextcloud Hub 3 25.0.2

**Comment by tasagore** [comment]
I guess this is not a bug. If you delete manually the tables should be sure to delete also the Libresign directory under appdata (data folder) and under apps (nextcloud folder). And also verify that in other config tables like oc_appconfig there is nothing about Libresign.

**Comment by tonytonyistony** [comment]
Yes this is not a bug report, but more of a request for technical assistance. At this point Im unable to (re)install due to messing with the DB. Is there a way to get libresign to do a DB check and repair?

**Comment by vitormattos** [comment]
Nextcloud have a migration table, when you delete an app table, you also need to delete the migrations from migration table and execute again the migration.
