### ISSUE TITLE
l10n: Question for a text string

### ISSUE THREAD

**Issue by Valdnet** [LibreSign/libresign#131]
Is this text string correct?

https://github.com/LibreSign/libresign/blob/b7869a1f2820e4ccc5d05a69b9c30939b5e9ee6f/lib/Controller/LibresignController.php#L136

My guess is it is because it is the name of the file with the extension, but when translating in Transifex, translators can make mistakes and add a space between `signed.` and `%s`.

I propose to separate the translation of the word `signed` from `.%s`.

**Comment by vitormattos** [comment]
Maybe remove the extension and keep only the translation of the word signed.
What do you think?

**Comment by Valdnet** [comment]
In Transifex, the text value looks like this:

![obraz](https://user-images.githubusercontent.com/47037905/111983884-edc55b00-8b0a-11eb-81c3-ad58fae3cf11.png)

This can be a problem for translators. No There is such a combination in translations.
I propose to extract only `signed` beyond the `.%s', $originalFile->getExtension()),` code so that the bot will only scan that text string.

**Comment by vitormattos** [comment]
Proposal:
```php
$this->l10n->t('signed') . '.', $originalFile->getExtension(),;
```

**Comment by Valdnet** [comment]
I think it will be fine now and the bot will only scan` signed`.

**Comment by Valdnet** [comment]
@vitormattos Shouldn't it be like this:
`$this->l10n->t('signed') . '%s', $originalFile->getExtension()`
