### ISSUE TITLE
Failed to get endpoint /health from CFSSL API

### ISSUE THREAD

**Issue by yodatak** [LibreSign/libresign#1334]
**Describe the bug**

**To Reproduce**
 sudo -u nextcloud php8.1 -f /var/www/html/cloud.XXXX.org/occ libresign:configure:check -vvv
 --------- ----------------- ------------------------------------------------------------------------------------------------- ------------------------------------- 
  Status    Resource          Message                                                                                           Tip                                  
 --------- ----------------- ------------------------------------------------------------------------------------------------- ------------------------------------- 
  success   java              Using java from operational system. Version: openjdk version "17.0.4" 2022-07-19                  Run occ libresign:install --java     
  success   jsignpdf          JSignPdf version: 2.2.0                                                                                                                
  success   jsignpdf          JSignPdf path: /var/nextcloud//appdata_ocqahjr7h96a/libresign/jsignpdf-2.2.0/JSignPdf.jar                                              
  success   libresign-cli     LibreSign cli tools found in path: /var/nextcloud//appdata_ocqahjr7h96a/libresign/libresign-cli                                        
  success   imagick           Can generate the preview                                                                                                               
  success   cfssl             CFSSL binary path: /var/nextcloud//appdata_ocqahjr7h96a/libresign/cfssl                                                                
  success   cfssl             CFSSL: Version: 1.6.3, Runtime: go1.18                                                                                                 
   error    cfssl-configure   CFSSL not configured.                                                                             Run occ libresign:configure --cfssl  
 --------- ----------------- ------------------------------------------------------------------------------------------------- ------------------------------------- 
 ⚡ root@XXXXX  ~  sudo -u nextcloud php8.1 -f /var/www/html/cloud.XXXXX.org/occ libresign:configure:cfssl --cn XXXXXX.org
2023/01/03 03:19:30 [INFO] generate received request
2023/01/03 03:19:30 [INFO] received CSR
2023/01/03 03:19:30 [INFO] generating key: rsa-2048
2023/01/03 03:19:30 [INFO] encoded CSR
2023/01/03 03:19:30 [INFO] signed certificate with serial number XXXXXXXXXXXXXXXXXXXXXX

In CfsslHandler.php line 188:
                                                                                                       
  Endpoint /health of CFSSL server not found. Maybe you are using incompatible version of CFSSL serve  
  r. Use latests version. 

 ✘ ⚡ root@XXXX  ~  sudo -u nextcloud php8.1 -f /var/www/html/cloud.XXXXX.org/occ libresign:configure --cfssl                             

                                                 
  Command "libresign:configure" is not defined.  
                                                 
  Did you mean one of these?                     
      libresign:configure:cfssl                  
      libresign:configure:check                  
      libresign:install                          
      libresign:uninstall                        
      theming:config                             
                                                 

**Expected behavior**
works

**Environment information (please complete the following information):**
 - OS: [e.g. Linux Debian, Docker] Debian 11.5 
 - Browser [e.g. chrome, safari] Firefox
 - LibreSign Version [e.g. 3.2.1] 6.2.3
 - Nextcloud Server Version [e.g. 24.0.1]  PHP 8.1 Nextcloud 25.0.2 Postgresql 15.1
 - Logs (get the entries from nextcloud.log related with LibreSign i.e `tail -f data/nextcloud.log|grep libresign`)

**Comment by pwepwe973** [comment]
hello, has this been solved? because I can't find the solution in the link shared here
cordialy

**Comment by vitormattos** [comment]
Hi @pwepwe973 if you got any problem, please, describe in other issue.

Yes, the problem related with not defined command was solved.
