### ISSUE TITLE
Invalid java version - Docker

### ISSUE THREAD

**Issue by Irish-link** [LibreSign/libresign#1337]
I have NextCloud running through docker. Specifically the LinuxServer.io build.
Version - Hub 3 (25.0.2)

After downloading from the store and following the setup I get an error in the Administrator settings for LibreSign. 

error - `Invalid java version. Found: sh: /data/appdata_ocmr5o70yvxu/libresign/java/jdk-17.0.5+8-jre/bin/java: not found expected: openjdk version "17.0.5" 2022-10-18`
error - `Necessary Java to run JSignPdf`

After download the Binaries all files do download correctly however this error persists. 

Doing `occ libresign:install --java` inside the container seems to work but the error never goes away. Following the Config Check and following its recomendation for cfssl works through the container so I know that the commands do work correctly.

Please let me know if this has been seen before and if there is a simple way to fix. (I have searched for Jave based issues but haven't found anything close to this) 

If this is outside the scope since its docker and a specific variant I totally get that. 

Thanks for the awesome work

**Comment by Irish-link** [comment]
This was not a bug with LibreSign or NextCloud. This was caused by the Linuxserver.io version of NextCloud. Recreated the Docker container with the official image and it worked as expected.

**Comment by Roxedus** [comment]
This is probably related to the fact that libresign wants to manage the jdk instance itself, and it does so by using a glibc build of the jdl, which does not work with Alpine.

**Comment by ACiDGRiM** [comment]
> This is probably related to the fact that libresign wants to manage the jdk instance itself, and it does so by using a glibc build of the jdl, which does not work with Alpine.

the nextcloud aio container uses alpine so this is frustrating

**Comment by Roxedus** [comment]
It installs glibc
