### ISSUE TITLE
File not found on specified place

### ISSUE THREAD

**Issue by polhenarejos** [LibreSign/libresign#1345]
I have installed correctly libresign app. I select a file, introduce a recipient and click on "Send request" and I get an error "File not found on specified place".

I have also configured correctly SMTP for sending emails.

From the code at 
https://github.com/LibreSign/libresign/blob/main/lib/Service/PdfParserService.php#L42
 it seems that this error is thrown when `realpath()` returns nothing.

PHP 8.1
Nextcloud 25.0.2

**Comment by cabaseira** [comment]
Hi!
Is the document you are trying to sign contained in a group folder?
This is a known bug: https://github.com/LibreSign/libresign/issues/1147

**Comment by polhenarejos** [comment]
Exactly. If you consider can close my bug. Plus, if I can help on whatever you need please let me know.

**Comment by cabaseira** [comment]
I'm just a simple user. Glad to be able to help you and the LibreSign team.

**Comment by vitormattos** [comment]
I identified the problem and fixed but I think that could be a best solution.

The problem is because when I get the path of shared file, return the path relative to authenticated user and this isn't the right path.
