### ISSUE TITLE
full installation guide?

### ISSUE THREAD

**Issue by ManySolutions** [LibreSign/libresign#1395]
I followed the instruction on the main page, however when I clicked download binaries nothing happened. So i followed all of the occ commands that were listed in the admin section.

After the final command 'configure:cfssl' there were some options, but I have no idea what to put there. When I go back to the admin page in my nextcloud the configuration check table is now completely empty.

The instructions after that are:
'is time to configure root certificate in the next section.' but there is no next section?

When I try to open libresign i get the error:
'An error occurred while fetching the files'

and when i try and click settings -> accounts in the bottom left, i get the error 'Class "Pagerfanta\Pagerfanta" not found
'.

**Comment by vitormattos** [comment]
Hi @ManySolutions,
If you have using the latest version compatible with Nextcloud server 25, I think that the problem about Pagerfanta already was fixed here https://github.com/LibreSign/libresign/pull/1386 and the fix will come in the next release.

About more details to generate root certificate I think that the PR #1399 will make more easy to configure the root certificate.

**Comment by lhsazevedo** [comment]
Hi @ManySolutions. Could you try in the latest release (6.2.6)?

**Comment by lhsazevedo** [comment]
@ManySolutions We improved error logging for the setup process in v6.2.9 (Nextcloud 25) and v7.0.0 (Nextcloud 26).

Maybe we can get more details about your issue. Try downloading binaries again and, if it fails, please share the last entries from `data/nextcloud.log`.
