### ISSUE TITLE
Class "Jeidison\JSignPDF\JSignPDF" not found in file '/apps/libresign/lib/Handler/JSignPdfHandler.php

### ISSUE THREAD

**Issue by Bolli84** [LibreSign/libresign#1397]
After an update, the signed files are not accessible in Libresign and it has the following error:

> Class "Jeidison\JSignPDF\JSignPDF" not found in file '/+++++++++/apps/libresign/lib/Handler/JSignPdfHandler.php' line 33
The check-configure is also giving this issue

After the first issue, libresign was completely uninstalled and removed from any entry. Appdata,....
A new install gave a correct libresign, but failed "success-checks". 
then I installed Java by commandline OCC leading to "success"
Then installation of Jsignpdf by OCC leads to the error.
Uninstal of "jsignpdf" but installing everything else leads to all "success" (Except Jsignpdf of course)

Installation is on Nextcloud 25.02 PHP8.0
It worked with the former versions of Libresign until it was updated with the version.

**Comment by vitormattos** [comment]
Hi @Bolli84 the problem about class not found already was fixed and the fix will come in the next release. https://github.com/LibreSign/libresign/pull/1386

**Comment by Bolli84** [comment]
Confirmed, the commit #1386  works.
