### ISSUE TITLE
l10n: Singular or plural

### ISSUE THREAD

**Issue by Valdnet** [LibreSign/libresign#140]
Should the user plural be here?
https://github.com/LibreSign/libresign/blob/99d9ca0c534dec514bad57bf40f35cae8172757a/lib/Service/WebhookService.php#L123

**Comment by vitormattos** [comment]
This sentence has no singular.
The translation method `n` must have both singular and plural.
Example:
```php
return $this->l->n(
    '%n author is currently in the city %1$s',  // singular string
    '%n authors are currently in the city %1$s',  // plural string
    $count, // number to decide which plural to use
    [$city] // further parameters are possible
);
```

**Comment by Valdnet** [comment]
@vitormattos I don't know if you got me right.
Shouldn't the text string be like this: `Empty user collection`.
The singular word "user" appears in other text strings. Whether this text string refers to a single user or multiple users.

**Comment by vitormattos** [comment]
This refers to several users.
The API must be receive a list of users and this phrase is used when the list is empty.

**Comment by vitormattos** [comment]
Maybe replacing `collection` with `list` is a good thing.

**Comment by Valdnet** [comment]
> This refers to several users.

I understand :wink:.

> Maybe replacing `collection` with `list` is a good thing.

The `list` is better suited. You also need to change other text strings.

**Comment by vitormattos** [comment]
I created a pull request to solve. 
Can you review it?

**Comment by Valdnet** [comment]
Cool. Much better 🥇.
