### ISSUE TITLE
"Confirm your signature" popup unresponsive throw error net::ERR_INVALID_URL

### ISSUE THREAD

**Issue by sergeng** [LibreSign/libresign#1407]
**Describe the bug**
when the signator create its first signature the "confirm your signature" popup stay open and doean't go away after clicking many times the close/save/cancel buttons.

**To Reproduce**
- I'm an authenticated user
- Go to 'https://cloud.domain.com/apps/libresign/f/account?_back_to_signature=0124534'
- Click on 'No signature, click here to create one'
- Once finished creating Click 'save'
- See the popup stay on the foreground no matter what

**Expected behavior**
the "Confirm your signature" popup should close accordingly

**Screenshots**
![image](https://user-images.githubusercontent.com/8804826/216752185-cf302924-92ce-4ef8-a125-a7fc22b8b4fd.png)

**Environment information (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Browser [Edge 109.0.1518.70]
 - LibreSign Version [3.2.1]
 - Nextcloud Server Version [25.0.3]
 - Nextcloud Logs
`{
    "reqId": "XVEJKkahoFmTzcVhbW2s",
    "level": 3,
    "time": "February 04, 2023 06:17:52",
    "remoteAddr": "11.222.111.222",
    "user": "admin",
    "app": "PHP",
    "method": "PATCH",
    "url": "/apps/libresign/api/0.1/account/signature/elements/2",
    "message": "exif_read_data(): File not supported at /home/nextcloud/public_html/lib/private/Metadata/Provider/ExifProvider.php#59",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.70",
    "version": "25.0.3.2",
    "exception": {
        "Exception": "Error",
        "Message": "exif_read_data(): File not supported at /home/nextcloud/public_html/lib/private/Metadata/Provider/ExifProvider.php#59",
        "Code": 0,
        "Trace": [
            {
                "function": "onAll",
                "class": "OC\\Log\\ErrorHandler",
                "type": "::"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/Metadata/Provider/ExifProvider.php",
                "line": 59,
                "function": "exif_read_data"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/Metadata/MetadataManager.php",
                "line": 68,
                "function": "execute",
                "class": "OC\\Metadata\\Provider\\ExifProvider",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/Metadata/FileEventListener.php",
                "line": 101,
                "function": "generateMetadata",
                "class": "OC\\Metadata\\MetadataManager",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/EventDispatcher/ServiceEventListener.php",
                "line": 87,
                "function": "handle",
                "class": "OC\\Metadata\\FileEventListener",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
                "line": 251,
                "function": "__invoke",
                "class": "OC\\EventDispatcher\\ServiceEventListener",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
                "line": 73,
                "function": "callListeners",
                "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/EventDispatcher/EventDispatcher.php",
                "line": 88,
                "function": "dispatch",
                "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/EventDispatcher/EventDispatcher.php",
                "line": 100,
                "function": "dispatch",
                "class": "OC\\EventDispatcher\\EventDispatcher",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/Files/Node/HookConnector.php",
                "line": 118,
                "function": "dispatchTyped",
                "class": "OC\\EventDispatcher\\EventDispatcher",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/legacy/OC_Hook.php",
                "line": 106,
                "function": "postWrite",
                "class": "OC\\Files\\Node\\HookConnector",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/Files/View.php",
                "line": 1294,
                "function": "emit",
                "class": "OC_Hook",
                "type": "::"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/Files/View.php",
                "line": 1222,
                "function": "runHooks",
                "class": "OC\\Files\\View",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/Files/View.php",
                "line": 705,
                "function": "basicOperation",
                "class": "OC\\Files\\View",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/Files/Node/File.php",
                "line": 71,
                "function": "file_put_contents",
                "class": "OC\\Files\\View",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/apps/libresign/lib/Service/AccountService.php",
                "line": 392,
                "function": "putContent",
                "class": "OC\\Files\\Node\\File",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/apps/libresign/lib/Service/AccountService.php",
                "line": 376,
                "function": "updateFileOfVisibleElement",
                "class": "OCA\\Libresign\\Service\\AccountService",
                "type": "->",
                "args": [
                    "*** sensitive parameters replaced ***"
                ]
            },
            {
                "file": "/home/nextcloud/public_html/apps/libresign/lib/Controller/AccountController.php",
                "line": 357,
                "function": "saveVisibleElement",
                "class": "OCA\\Libresign\\Service\\AccountService",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 225,
                "function": "patchSignatureElement",
                "class": "OCA\\Libresign\\Controller\\AccountController",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 133,
                "function": "executeController",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/AppFramework/App.php",
                "line": 172,
                "function": "dispatch",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/lib/private/Route/Router.php",
                "line": 298,
                "function": "main",
                "class": "OC\\AppFramework\\App",
                "type": "::"
            },
            {
                "file": "/home/nextcloud/public_html/lib/base.php",
                "line": 1047,
                "function": "match",
                "class": "OC\\Route\\Router",
                "type": "->"
            },
            {
                "file": "/home/nextcloud/public_html/index.php",
                "line": 36,
                "function": "handleRequest",
                "class": "OC",
                "type": "::"
            }
        ],
        "File": "/home/nextcloud/public_html/lib/private/Log/ErrorHandler.php",
        "Line": 99,
        "CustomMessage": "--"
    }
}
{
    "reqId": "XVEJKkahoFmTzcVhbW2s",
    "level": 2,
    "time": "February 04, 2023 06:17:52",
    "remoteAddr": "68.183.181.151",
    "user": "admin",
    "app": "libresign",
    "method": "PATCH",
    "url": "/apps/libresign/api/0.1/account/signature/elements/2",
    "message": "Controller OCA\\Libresign\\Controller\\AccountController::patchSignatureElement executed 293 queries.",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.70",
    "version": "25.0.3.2",
    "data": {
        "app": "libresign"
    }
}
{
    "reqId": "WOrE4PFXFf9TtFZa7Gqm",
    "level": 1,
    "time": "February 04, 2023 06:17:52",
    "remoteAddr": "68.183.181.151",
    "user": "admin",
    "app": "no app in context",
    "method": "GET",
    "url": "/core/preview?y=100&x=350&fileId=429686&_t=1675491473351",
    "message": "Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent is used",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.70",
    "version": "25.0.3.2",
    "data": []
}`

**Comment by vitormattos** [comment]
I think that this was solved at newest release.

PS: If you like this app, don't hesitate to help us to maintain the development sponsoring by GitHub sponsor https://github.com/sponsors/LibreSign or also contacting us to have Enterprise support: https://libresign.coop

Closing this issue.
