### ISSUE TITLE
Setup with Nextcloud AIO

### ISSUE THREAD

**Issue by bigbeka** [LibreSign/libresign#1409]
Issue: Error - Java not installed message; 
Advice: Run occ libresign:install --java

To reproduce:
- Download and enable LibreSign from list of Nextcloud apps
- Click on 'Downloads Binaries'
- Wait for the list of items to show up and some of them errored out

**Screenshots**
![Screenshot 2023-02-05 at 22 52 31](https://user-images.githubusercontent.com/53529055/216848213-359c2b8e-26e7-491e-b07c-49bf8a390634.png)

**Environment information (please complete the following information):**
 - OS: Proxmox > LXC > Docker > Nextcloud official container
 - Browser Safari
 - LibreSign Version 6.2.5
 - Nextcloud Server Version 25.0.3

Searching here or elsewhere did not reveal that someone else had similar issue.

**Comment by Prodject** [comment]
I tried on two versions - Ubuntu latest + apache + nextcloud and mac M1 native docker + nextcloud.
 There is a similar error, more precisely - on 6.2.5 Java installation error, and on 6.2.3 cfssl installation and configuration error.
Also tried to manually install all dependencies via php occ libresign:install --all. Installation doesn't throw errors, but dependency validation fails.

It seems to me that developers may return the http api url manual installation mode to be able to install packages in a separate container / vm.  Or add the ability to provide installation of dependencies from an offline bundle package

**Comment by bigbeka** [comment]
@Prodject Thanks for the followup message and further reproducing. Hoping to get this sorted soon.

**Comment by Prodject** [comment]
> Hoping to get this sorted soon

I tried to roll back to version 4.2.1 - I got a successful result of downloading dependencies. I also tried to update the version to 6.2.5 - the dependencies were preserved, but there was a bug that the current signature could not be changed.
In v.4.2.1 there was also a bug with a signature overlay conflict in pdf, I could not fix it either, and it was saved in 6.2.5.

**Comment by lhsazevedo** [comment]
Could you try in the latest release (6.2.6)?
Note that this release is compatible with Nextcloud 25 only. We do not support previous versions anymore, as we haven't sufficient funding at the moment.

**Comment by bigbeka** [comment]
@lhsazevedo updated LibreSign to 6.2.6 with Nextcloud being 25.0.3, tried to 'Download binaries', still shows the same errors.
I have also tried to remove LibreSign completely and 'Download and Enable' from within the UI, no luck there either. Any other troubleshooting I can be doing?

**Comment by lhsazevedo** [comment]
Thanks for reporting @bigbeka and @Prodject. I'll setup environments similar to yours and try to reproduce the issue to further investigate this problem.

**Comment by bigbeka** [comment]
Olay, so this is interesting. Fresh VM > Fresh Docker & Compose > Fresh Nextcloud install. And it worked, I can’t get the imagick working to generate the previews when assigning signature positions on the actual pdfs.

@lhsazevedo what would you suggest the next troubleshooting should be?
How do I get LibreSign working on my production?

**Comment by lhsazevedo** [comment]
I'm glad you made it. Now looks like you are missing the optional `ghostscript` dependency, that is only need for adding visible signatures.

Since you are using the Nextcloud AIO container, you'll need to add it to the `NEXTCLOUD_ADDITIONAL_APKS` environment variable and rebuild the image. Read more about it: [How to add OS packages permanently to the Nextcloud container?](https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container). Make sure to also specify the default `imagemagick`, as the doc warns.

@Prodject I've just released a new version (6.2.7) which fixes a bug in the "download binaries" that was preventing the progress bars from showing which might fix your issue. Could you try again with this new version, in a clean installation?

**Comment by bigbeka** [comment]
@lhsazevedo Would you look at that! Many thanks for the update, LibreSign 6.2.7 did the trick with my production as well (I just had to update LibreSign in Nextcloud GUI), all success apart from imagick, which I believe I will need to rebuild NextCloud AIO with Nextcloud_additional_APKS as you mentioned. Thank you for the link and your work on this! 

![Screenshot 2023-02-21 at 09 25 02](https://user-images.githubusercontent.com/53529055/220288882-b65a8e23-8305-4ff8-9b57-635b92c21b50.png)

@lhsazevedo Off-topic question: Is there a way to ask for signatures without requiring for an account? This features would really get it close to DocuSign (Clinex of signature validations).

**Comment by lhsazevedo** [comment]
Great! Happy to help. Let us know if you got it fully working.

At the moment, a Nextcloud account is required for signing the document, but we are aware that removing this requirement would fit LibreSign to lots of use cases out there. This will require some significant rework in the app though, we are planning this in #1406.

@Prodject I'm closing this for now, but don't hesitate to ping us if it still fails in a clean install.

**Comment by bigbeka** [comment]
@lhsazevedo We might need to reopen this, as original issue came back, right after I tried to add "imagick" to `-e NEXTCLOUD_ADDITIONAL_APKS` and I re-pulled the latest Nextcloud Docker image in this process.

I can confirm that the same issue came up when I re-pulled the latest image for the fresh/test instance.

Could you suggest how to go about this now?

**Comment by lhsazevedo** [comment]
Thanks for reporting again.
Sure. I suggest you to running the following commands:

```sh
# Uninstall all LibreSign binaries (Java, cfssl etc)
php occ libresign:uninstall --all

# Update Nextcloud filesystem nodes for libresign app data
php occ files:scan-app-data libresign
```

Then proceed to the settings page and try downloading the binaries again. I've found that sometimes I need to click "download binaries" button for a second time when the first one fails.

If that doesn't work, you could also repeat the commands above but this time download the binaries using the CLI:

```sh
# Uninstall LibreSign binary dependencies (Java, cfssl etc)
php occ libresign:uninstall --all

# Update Nextcloud filesystem nodes for libresign app data
php occ files:scan-app-data libresign

# Install LibreSign binary dependencies
php occ libresign:install --all
```

Either way, please report the results here to help us track this down.

**Comment by bigbeka** [comment]
Many thanks @lhsazevedo , you are the best!

So I managed to get the dependencies installed with 3 CLI commands:
`php occ libresign:uninstall --all
php occ files:scan-app-data libresign
php occ libresign:install --all`

GUI 'Downloads binaries' did not help.

Running the second command gave me an error, which is not related to LibreSign, it is actually being tracked [here](https://github.com/nextcloud/server/pull/35935).

I have also tried to recreate the Nextcloud container, dependencies seem to be working and are not showing any errors.

For the life of me, I can't get imagick working, as you suggested, I have added `-e NEXTCLOUD_ADDITIONAL_APKS="imagick imagemagick"`.
- Would you have any suggestions on this?

<img width="849" alt="Screenshot 2023-02-23 at 02 39 46" src="https://user-images.githubusercontent.com/53529055/220803402-0ae546b8-7675-47ba-9652-b3076a79ac5e.png">

**Comment by bigbeka** [comment]
Reading through the internet, I came across this, which might be interesting: https://github.com/nextcloud/server/issues/13099#issue

Would you guys consider switching from imagick to something else as suggested in the above discussion?

**Comment by BicycleMarketResearchLLC** [comment]
Thank you all for working on this, I have been following and trying the suggested resolutions. I keep getting this error in the GUI. It seems like a slight version mismatch in JRE:

`Invalid java version. Found: sh: /mnt/ncdata/appdata_ocmmonyuk9bz/libresign/java/jdk-17.0.5+8-jre/bin/java: not found expected: openjdk version "17.0.5" 2022-10-18`

Do you know if there is a mechanism to specify the correct version of java for the install? I am on the latest AIO deployment of Nextcloud on an Ubuntu VPS.

**Comment by lhsazevedo** [comment]
No problem, I'm learning a lot while trying to understand what is happening!

Oh, that should be `-e NEXTCLOUD_ADDITIONAL_APKS="imagemagick ghostscript"`, where:
- `imagemagick` is the sole default value of `NEXTCLOUD_ADDITIONAL_APKS`, we are just keeping it:
  
  > By default added is imagemagick. If you want to keep that, you need to specify it. ([source](https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container))
- `ghostscript` is the dependency that was missing [here](https://github.com/LibreSign/libresign/issues/1409#issuecomment-1435990965)

That should fix it.

Thanks for sharing the concerns around imagick vulnerabilities. The app uses it only for rendering pages when adding visible signatures, it would be necessary to estimate the work required to switch to a safer alternative like the new Imaginary service mentioned in the thread you sent. Would you mind creating an issue for this?

--------------

Hi @BicycleMarketResearchLLC, I guess the cause of your problem is not related to this one. Could you open a new issue for it?

**Comment by lhsazevedo** [comment]
@bigbeka We improved error logging for the setup process in v6.2.9 (Nextcloud 25) and v7.0.0 (Nextcloud 26).

Maybe we can get more details about your issue. Try downloading binaries again and, if it fails, please share the last entries from `data/nextcloud.log`.

**Comment by lhsazevedo** [comment]
`Any other thoughts on this?`

Either you do not have ghostscript installed or LibreSign wasn't able to detect it, the former is most likely. You can check by opening a shell in your Nextcloud container and typing `gs --version`.

**Comment by leanbuild** [comment]
@lhsazevedo Thank you, as always, you were right, `gs` is not installed despite the fact that I have the `-e NEXTCLOUD_ADDITIONAL_APKS="imagemagick ghostscript"` added to my docker-compose.yml.

Your suggestions on this error would be greatly appreciated. I will do some googling.

**Comment by bigbeka** [comment]
@lhsazevedo Thank you, as always, you were right, gs is not installed despite the fact that I have the -e NEXTCLOUD_ADDITIONAL_APKS="imagemagick ghostscript" added to my docker-compose.yml.

Your suggestions on this error would be greatly appreciated. I will do some googling.

**Comment by bigbeka** [comment]
> Hi @lhsazevedo Thank you very much! I have now upgraded my NC25 to NC26.0.0
> 
> I had deleted LibreSign before doing this, so I downloaded LibreSign 7.0.0 and tried to download binaries and here are the errors that it output. Does it tell anything useful?
> 
> <img alt="Screenshot 2023-03-23 at 13 40 15" width="2000" src="https://user-images.githubusercontent.com/53529055/227206456-515cc0be-ef2d-4933-99ca-cfd4137301fc.png">

@lhsazevedo It would be great to resolve this, as I am back in square 1 with 'Download Binaries'. As soon as I re-pull the image and `docker-compose up` I get the following state:

<img width="1149" alt="Screenshot 2023-03-25 at 09 50 13" src="https://user-images.githubusercontent.com/53529055/227707310-a7156557-874b-4dce-8101-e39d1d6e81cc.png">

**Comment by lhsazevedo** [comment]
Oops, I missed your comment about the error log. I'll take a look into it later this weekend. Thank you for your patience.

**Comment by bigbeka** [comment]
Not at all, thank YOU for your help! Have a great weekend.On 25 Mar 2023, at 12:24, Lucas Azevedo ***@***.***> wrote:﻿
Oops, I missed your comment about the error log. I'll take a look into it later this weekend. Thank you for your patience.

**Comment by leanbuild** [comment]
@lhsazevedo Any news on this? Is there anything I could do to troubleshoot it?

**Comment by bigbeka** [comment]
@lhsazevedo Any news on this? Is there anything I could troubleshoot?

**Comment by Nocross** [comment]
### "Java not installed" 
#### Cause:
Download of incompatible flavor of OpenJDK: linux - instead of alpine, which is the base for AIO NextCloud.

#### Suggestion(s):
Add fallback to OS environment java as it will be sufficiently expectable for Operator/Administrator.

Remove downloading of external binaries:
- Security issue - patching of 'embedded' java is completely reliant on Developer/Maintainer(s) of the app;
- Single point of failure - completely dependent on existence and availability of GitHub.

### "imagick/ghostscript "

#### Cause:
Narrow test for executable pass with single well-known name - [ConfigureCheckService.php](https://github.com/LibreSign/libresign/blob/main/lib/Service/ConfigureCheckService.php#L67)

#### Suggestion(s):
- Extend heuristics for more well-known names/alias(es) and/or query distribution package manager for info;
- Provide setting for manageable configuration.

**Comment by szaimen** [comment]
Hi, what about using `-e NEXTCLOUD_ADDITIONAL_APKS="imagemagick openjdk17-jre ghostscript"`

**Comment by Nocross** [comment]
@szaimen, will not suffice by itself.

one'll have to manually override `java_path` setting ([ConfigureCheckService.php:164](https://github.com/LibreSign/libresign/blob/main/lib/Service/ConfigureCheckService.php#L164)) and create a symlink for `/usr/bin/gs`  (i. e. to `/usr/local/bin/ghostscript`) which will deviate from [alpine package](https://pkgs.alpinelinux.org/contents?branch=v3.17&name=ghostscript&arch=x86_64&repo=main).

**Comment by vitormattos** [comment]
@Nocross you can use this app setting to change the java path too and do a handmade setup. But the easiest way to do the setup is using the interface that will download all the necessary binaries because all the binaries to LibreSign works will stay inside the app data folder and you don't need to worry about how to do the setup.

**Comment by Nocross** [comment]
@vitormattos, the setup procedure is fragile and it won't work out of the box for AIO flavor of NextCloud - as it downloads wrong archive for java. Correct one for alpine can be downloaded - https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jre_x64_alpine-linux_hotspot_17.0.5_8.tar.gz

To be precise:
[InstallService.php:L261](https://github.com/LibreSign/libresign/blob/main/lib/Service/InstallService.php#L261) assumes that beside `arch` all linux distribution are uniform.

**Comment by vitormattos** [comment]
I'm thinking about to increase this part of code and put a link to a issue or other place that can help other people to solve problems related to Java setup:

https://github.com/LibreSign/libresign/blob/main/lib/Service/ConfigureCheckService.php#L118-L134

**Comment by prevail90** [comment]
i pulled

`/var/www/html # php java_test.php `./occ config:app:get libresign java_path`
The file Console didn't exists.`

after I created a java_test.php and inputted:
`<?php
if (!function_exists('exec')) {
        die("function exec didn't exists.\n");
}

if (!file_exists($argv[1])) {
        printf("The file %s didn't exists.\n", $argv[1]);
        die();
}

if (!is_executable($argv[1])) {
        printf("The file %s haven't execution permission.\n", $argv[1]);
        die();
}

echo "Current date: ";
\exec('date', $output);
var_dump($output);

\exec($argv[1] . " -version 2>&1", $output);
var_dump($output);`

**Comment by narendra-bhole** [comment]
I'm also facing similar error

Invalid java version. Found: sh: /mnt/ncdata/appdata_ocmmonyuk9bz/libresign/java/jdk-17.0.5+8-jre/bin/java: not found expected: openjdk version "17.0.5" 2022-10-18

it looks some excution permission issue in docker. Please help me to resolve

**Comment by Aniket-IN** [comment]
Same issue, just using the simple default Nextcloud Docker AIO installation still facing same issue.
![image](https://github.com/LibreSign/libresign/assets/64463116/13fe38d2-900d-4f99-b4cd-a5ff167ad0ac)

**Comment by Arbel-arad** [comment]
i noticed this error when trying to install the dependencies
the error only shows up when using the button on the web interface, but installing with OCC still doesn't work.
![image](https://github.com/LibreSign/libresign/assets/65590498/f6b52424-5fe4-4949-8902-d0d22e781781)
![image](https://github.com/LibreSign/libresign/assets/65590498/67557269-d6b1-4887-a1e2-345af3b09511)

**Comment by Arbel-arad** [comment]
looking at it again, i tried to sign a document and got the following result:
![image](https://github.com/LibreSign/libresign/assets/65590498/23efc740-4d3d-4e3f-8a58-215ba822b769)

`Error to sign PDF. ["sh: \/mnt\/ncdata\/appdata_oc5bwmghpu5h\/libresign\/java\/jdk-17.0.5+8-jre\/bin\/java: not found"]`

there appear to be both a forward and back slash in all locations. (is this intended?)
also, the java files are indeed in the correct folder:
```
3f9316d05ee4:/var/www/html$ ls -l /mnt/ncdata/appdata_oc5bwmghpu5h/libresign/java/jdk-17.0.5+8-jre/bin/
total 120
-rwxrwx--- 1 www-data root 16320 Oct 19  2022 java
-rwxrwx--- 1 www-data root 16336 Oct 19  2022 jfr
-rwxrwx--- 1 www-data root 16376 Oct 19  2022 jrunscript
-rwxrwx--- 1 www-data root 16336 Oct 19  2022 keytool
-rwxrwx--- 1 www-data root 16344 Oct 19  2022 rmiregistry
3f9316d05ee4:/var/www/html$ 
```

**Comment by vitormattos** [comment]
I made a lot of changes at setup flow.

Who with Nextcloud AIO could help testing again to check if this issue was solved?

**Comment by bigbeka** [comment]
I will try it now. Do I need to delete anything manually before reinstalling? I already had LibreSign installed on my instance of NC.

**Comment by vitormattos** [comment]
Wow! Very happy by your feedback!

> Although the "Identification documents" doesn't seem to work. The flow does not ask to upload any ID docs.

Could you open an issue about this?

I think that now is the time to close this issue. It's the party time!

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop

**Comment by martin-77** [comment]
Not working on nextcloud-aio with manual upgrade to hub 8
errors:

```
c2bc57ffc481:/var/www/html$ php occ libresign:configure:check
 --------- ----------------- --------------------------------------------------------------------------------------------------- -----------------------------------
  Status    Resource          Message                                                                                             Tip
 --------- ----------------- --------------------------------------------------------------------------------------------------- -----------------------------------
   error    java              Java binary not found: /mnt/ncdata/appdata_ocmhlw0tagos/libresign/java/jdk-21.0.2+13-jre/bin/java   Run occ libresign:install --java
   error    pdftk             PDFtk binary is invalid: /mnt/ncdata//appdata_ocmhlw0tagos/libresign/pdftk.jar                      Run occ libresign:install --pdftk
   error    jsignpdf          Necessary Java to run JSignPdf                                                                      Run occ libresign:install --java
  success   cfssl             CFSSL binary path: /mnt/ncdata/appdata_ocmhlw0tagos/libresign/cfssl
  success   cfssl             CFSSL: Version: 1.6.4, Runtime: go1.18
  success   cfssl-configure   Root certificate config files found.
 --------- ----------------- --------------------------------------------------------------------------------------------------- -----------------------------------
c2bc57ffc481:/var/www/html$ php occ libresign:install --all
Downloading java...
    0 [>---------------------------]Failure on download java try again.
Directory /mnt/ncdata//appdata_ocmhlw0tagos/libresign/java does not exist for sink value of /mnt/ncdata//appdata_ocmhlw0tagos/libresign/java/OpenJDK21U-jre_x64_linux_hotspot_21.0.2_13.tar.gz
    0 [->--------------------------]
    0 [--->------------------------]Failure on download java, empty file, try again 

```
/mnt/ncdata/appdata_ocmhlw0tagos/libresign/java/jdk-21.0.2+13-jre/bin/java: folder is empty
/mnt/ncdata**//**appdata_ocmhlw0tagos/libresign/pdftk.jar: strange error //

any idea how to fix the // error?

**Comment by martin-77** [comment]
Command shows 8 folders and 26 files.

**Comment by vitormattos** [comment]
Check now if all is working fine.

You also can use the UI at Administration Settiongs > LibreSign

**Comment by martin-77** [comment]
Still the same. tried occ uninstall and install, java stays uninstalled.

**Comment by vitormattos** [comment]
Sounds that could be related with:

- https://github.com/LibreSign/libresign/issues/2327

The issue #2327 already was solved but is open because is necessary to think more about how to give tips to identify that is a problem related to `policies of SELinux`.

To identify if is about policy, try to run the command to check the java version directly at the terminal of your server. 

```bash
/mnt/ncdata/appdata_ocmhlw0tagos/libresign/java/jdk-21.0.2+13-jre/bin/java --version
```

And first, check if this file (java) exists.

**Comment by martin-77** [comment]
java is not installed

```
c2bc57ffc481:/var/www/html$ /mnt/ncdata/appdata_ocmhlw0tagos/libresign/java/jdk-21.0.2+13-jre/bin/java --version
bash: /mnt/ncdata/appdata_ocmhlw0tagos/libresign/java/jdk-21.0.2+13-jre/bin/java: cannot execute: required file not found
```

**Comment by vitormattos** [comment]
Have anything strange because you have the file and the message is not about without file, sounds that is about any dependency wrong.

The file is downloaded from here if is x64
https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2+13/OpenJDK21U-jre_x64_linux_hotspot_21.0.2_13.tar.gz

And from here if is aarch64:
https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2+13/OpenJDK21U-jre_aarch64_linux_hotspot_21.0.2_13.tar.gz

Could you download the tar file to your architecture, extract and test if  `bin/java --verison` will work fine? Pay attention to directory.

To use the same way of LibreSign to identify the architecture, you can use the follow command:

```php
php -r "echo php_uname('m') . PHP_EOL;"
```

**Comment by martin-77** [comment]
Ok, this is crazy - maybe I make a mistake, but even the downloaded version does not work (forget about wrong folders I produce)

```
c2bc57ffc481:/mnt/ncdata/appdata_ocmhlw0tagos/libresign/java/jdk-21.0.2+13-jre/bin/jdk-21.0.2+13-jre/bin$ php -r "echo php_uname('m') . PHP_EOL;"
x86_64
c2bc57ffc481:/mnt/ncdata/appdata_ocmhlw0tagos/libresign/java/jdk-21.0.2+13-jre/bin/jdk-21.0.2+13-jre/bin$ ./java --version
bash: ./java: cannot execute: required file not found
c2bc57ffc481:/mnt/ncdata/appdata_ocmhlw0tagos/libresign/java/jdk-21.0.2+13-jre/bin/jdk-21.0.2+13-jre/bin$ ls -la
total 104
drwxr-xr-x 2 www-data www-data  4096 Jan 17 06:55 .
drwxr-xr-x 6 www-data www-data  4096 Jan 17 06:55 ..
-rwxr-xr-x 1 www-data www-data 16240 Jan 17 06:55 java
-rwxr-xr-x 1 www-data www-data 16304 Jan 17 06:55 jfr
-rwxr-xr-x 1 www-data www-data 16344 Jan 17 06:55 jrunscript
-rwxr-xr-x 1 www-data www-data 16312 Jan 17 06:55 jwebserver
-rwxr-xr-x 1 www-data www-data 16304 Jan 17 06:55 keytool
-rwxr-xr-x 1 www-data www-data 16336 Jan 17 06:55 rmiregistry
c2bc57ffc481:/mnt/ncdata/appdata_ocmhlw0tagos/libresign/java/jdk-21.0.2+13-jre/bin/jdk-21.0.2+13-jre/bin$
```

the folder contains the same files as the java/bin which was downloaded by libresign itself. Not sure if I make a mistake...

**Comment by vitormattos** [comment]
> Ok, this is crazy - maybe I make a mistake, but even the downloaded version does not work (forget about wrong folders I produce)
> 
> ```
> c2bc57ffc481:/mnt/ncdata/appdata_ocmhlw0tagos/libresign/java/jdk-21.0.2+13-jre/bin/jdk-21.0.2+13-jre/bin$ php -r "echo php_uname('m') . PHP_EOL;"
> x86_64
> c2bc57ffc481:/mnt/ncdata/appdata_ocmhlw0tagos/libresign/java/jdk-21.0.2+13-jre/bin/jdk-21.0.2+13-jre/bin$ ./java --version
> bash: ./java: cannot execute: required file not found
> c2bc57ffc481:/mnt/ncdata/appdata_ocmhlw0tagos/libresign/java/jdk-21.0.2+13-jre/bin/jdk-21.0.2+13-jre/bin$ ls -la
> total 104
> drwxr-xr-x 2 www-data www-data  4096 Jan 17 06:55 .
> drwxr-xr-x 6 www-data www-data  4096 Jan 17 06:55 ..
> -rwxr-xr-x 1 www-data www-data 16240 Jan 17 06:55 java
> -rwxr-xr-x 1 www-data www-data 16304 Jan 17 06:55 jfr
> -rwxr-xr-x 1 www-data www-data 16344 Jan 17 06:55 jrunscript
> -rwxr-xr-x 1 www-data www-data 16312 Jan 17 06:55 jwebserver
> -rwxr-xr-x 1 www-data www-data 16304 Jan 17 06:55 keytool
> -rwxr-xr-x 1 www-data www-data 16336 Jan 17 06:55 rmiregistry
> c2bc57ffc481:/mnt/ncdata/appdata_ocmhlw0tagos/libresign/java/jdk-21.0.2+13-jre/bin/jdk-21.0.2+13-jre/bin$
> ```
> 
> the folder contains the same files as the java/bin which was downloaded by libresign itself. Not sure if I make a mistake...

Yes, is the same content because is the same file that LibreSign setup get.

Did you put at the same place? I ask because at your previous message is the same place. The place to extract the content is not important at this moment because I suggested to download and run the handmade test only to check if will works to you and the strange is that don't works.

**Comment by martin-77** [comment]
It is in ab sub-sub-folder of libresign. 
but something prevents java from being executed. And I do not understand, why at all. the java file is executable by www-data and I am www-data...

**Comment by vitormattos** [comment]
Yes, this is the strange point and I don't know how to solve. Let's think more about and wait for comments from others.

**Comment by cubeoneGmbH** [comment]
Hello, same issue as @martin-77 . This might have something to do with the docker containers using alpine. Java can be executed as expected outside the container on ubuntu.

**Comment by martin-77** [comment]
Are you on nc28 or 29?

**Comment by cubeoneGmbH** [comment]
I'm on nc28.

**Comment by neocult-de** [comment]
I am testing LibreSign on NC28 with Nextcloud-AIO. The issue is that the container is alpine which is not build with glibc libraries and therefore the Java cant be executed inside the container. Running the following adds compatibility to glibc and then java and pdftk for that matter will be recognized and work for me.

`apk add gcompat`

Please keep in mind, that this task might need to be repeated every time nextcloud-aio-nextcloud is updated. The dependencies are in the persistent ncdata folder though.

An automation could be to put the call to install gcompat into cron (as root or a user in the docker group) and schedule it after the nightly backup/update for nextcloud-aio:

0 5 * * * docker exec -it nextcloud-aio-nextcloud apk add gcompat

Hope that helps people want to try LibreSign with Nextcloud-AIO

**Comment by martin-77** [comment]
sadly, this did not solve my issue. running v29 - maybe there is something different?

**Comment by cube-one-gxp-lifescience-partner** [comment]
Unfortunately this is also the case for nc28 but the libjimage.so file is existing and has correct permissions.

**Comment by cube-one-gxp-lifescience-partner** [comment]
With the updated solution @neocult-de provided PDFtk is now recognized properly. But jsignpdf still won't run and so does the whole application.

"Necessary Java to run JSignPdf | jsignpdf"

**Comment by vitormattos** [comment]
ref: https://github.com/LibreSign/libresign/issues/3026

**Comment by vitormattos** [comment]
Do you think that using Alpine as a base Linux distribution will be possible to reproduce the problem? I don't have any instances with Nextcloud AIO and looking at the documentation of AIO, I haven't found a way to run AIO locally to reproduce the issue.

**Comment by martin-77** [comment]
@szaimen might be the one, we all need ;-) sorry for the ping...
But to be honest, libresign would be wonderfull see implemented in Nextcloud AIO.

**Comment by szaimen** [comment]
Hi @vitormattos you could try https://github.com/nextcloud/all-in-one/discussions/588#discussioncomment-3450343

**Comment by martin-77** [comment]
It is not the questiuon of setting up Nextcloud-AIO itself but adding jdk-21.0.2+13-jre / java jdk on top of the the alpine image.
As you can see, a simple apk install did not do the trick -> https://github.com/LibreSign/libresign/issues/1409#issuecomment-2104749277 - maybe you find some time to support or inspire us @szaimen . 
And thanks for your quick reply! You are unbelievable!

**Comment by szaimen** [comment]
Should be possible by so, no? 
https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-add-os-packages-permanently-to-the-nextcloud-container

**Comment by neocult-de** [comment]
The openjdk version shipped in the alpine repositories is outdated and can not be used. Therefore how to add os packages does not apply even though it would solve the issue if we could A rely on an updated version in Alpine and B LibreSign to actually use the shipped version.

There is another solution just by LibreSign to actually download a fitting release depending on the distro / c-library it finds.
Details and a Workaround for now I have listed here in the feature request: https://github.com/LibreSign/libresign/issues/3026#issuecomment-2126754011

**Comment by vitormattos** [comment]
I made this change:
- #3049
I wish to launch a new RC today to be more easy to test, but if possible, would be best getting the changes of this PR and making a test changing the file in your environment and launch a new stable release.

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

**Comment by martin-77** [comment]
had to remove previous install and run occ files:scan-app-data libresign but then, installation was possible without any problems! Thanks a lot!

**Comment by neocult-de** [comment]
The bugfix is out and working. So update the app via the AppStore and for making it work because the old checksum might be still there in the files follow the general reinstall procedure:

occ libresign:uninstall --all
occ files:scan-app-data libresign
occ flibresign:install --all   # Or use the web interface to install binaries

---
It works on Nextcloud-AIO stable (Nextcloud 28.0.5) that LibreSign 8.0.2 is correctly backported. A uninstall --all and reinstall via the web interface and via command line both works. A reinstallation of java by itself as well.

It works as well on Nextcloud-AIO with manual update to Nextcloud 29.0.0 and with LibreSign 9.0.2 in the same way.

Both were directly installed with the release from the App Store

**Comment by vitormattos** [comment]
Closing this issue as solved.

Thanks a lot by contribution of all that give a comment at this issue.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop

**Comment by javito1081** [comment]
Hi, 

I just setup LibreSign and its working perfectly on my Nextcloud instance, but im still getting an error on the LibreSign configuration check, can anyone help me fix it cause i cant find anything on google

![Image](https://github.com/user-attachments/assets/43a00912-011b-43a5-b587-d5edb8d1b962)

**Comment by vitormattos** [comment]
@javito1081 this isn't related to this issue.

But, replying:

The tip explains what you need to do. You need to install poppler utils at your operational system to improve your LibreSign. This is only an info, not an error.

If you have any doubt, you can go to our community at Telegram: https://t.me/LibreSign or if you like this project and consider important help to maintain the development, we will be very happy to receive a recurrent sponsoring at [GitHub Soponsors](https://github.com/sponsors/LibreSign).

**Comment by javito1081** [comment]
> [@javito1081](https://github.com/javito1081) this isn't related to this issue.
> 
> But, replying:
> 
> The tip explains what you need to do. You need to install poppler utils at your operational system to improve your LibreSign. This is only an info, not an error.
> 
> If you have any doubt, you can go to our community at [Telegram group](https://t.me/LibreSign). or if you like this project and consider important help to maintain the development, we will be very happy to receive a recurrent sponsoring at [GitHub Soponsors](https://github.com/sponsors/LibreSign).

Ty, ill join the telegram grp :-)

**Comment by javito1081** [comment]
This was my answer, for those using Nexctcloud AIO, this is what i did

sudo docker exec --user root -it nextcloud-aio-nextcloud apk add poppler-utils

**Comment by imaustinlittle** [comment]
> This was my answer, for those using Nexctcloud AIO, this is what i did
> 
> sudo docker exec --user root -it nextcloud-aio-nextcloud apk add poppler-utils

This worked great! Thank you!
