### ISSUE TITLE
Fix missing fields in the certificate generation form

### ISSUE THREAD

**Issue by lhsazevedo** [LibreSign/libresign#1427]
**Describe the bug**
When generating a certificate for the first time, the fields of additional names are not displaying after adding them in the select input.
A work around possible by generating the certificate with only the Common Name (CN), and then generating again. This second time the additional names field won't be missing.

**Environment information (please complete the following information):**
 - OS: Linux Mint, Docker
 - Browser: Firefox
  - LibreSign Version: main
 - Nextcloud Server Version: main
 - Logs: No relevant log entries

**Comment by vitormattos** [comment]
Fixed by https://github.com/LibreSign/libresign/pull/1561
