### ISSUE TITLE
[PDF/A] Impossible get metadata from this file. Check if you installed correctly the libresign-cli.

### ISSUE THREAD

**Issue by Alexis-M51** [LibreSign/libresign#1428]
**Describe the bug**
The bug this product when sending the email for the signature, an error message appears is displayed "Failed to obtain the metadata of this file. Check if you have correctly installed libresign-cli. »

**To Reproduce**
- I'm an authenticated user
- Go to in the page "libresign"
- Click on "chose from file"
- Select pdf file
- Enter the destination email
- Send
- See error

**Expected behavior**
The mail is send

**Screenshots**
![emaildestination](https://user-images.githubusercontent.com/90853905/219064388-e8a14cca-9388-4dba-90fd-47a480836541.png)

![error](https://user-images.githubusercontent.com/90853905/219064458-c3072259-aff8-4b04-8c60-0431235fd240.png)

![terminal](https://user-images.githubusercontent.com/90853905/219064479-02e0ca85-44d5-44da-85ce-cc26b0f9f470.png)

![Capture d’écran 2023-02-15 155921](https://user-images.githubusercontent.com/90853905/219064499-9bfcc701-eab4-4ad0-b424-c906f097e84d.png)

**Environment information (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser [e.g. chrome, firefox]
 - LibreSign Version 6.2.6
 - Nextcloud Server Version 25.0.3
 - NO LOGS

**Comment by vitormattos** [comment]
Hi @Alexis-M51 what's the output of libresign-cli command when you pass the path of PDF that you got the problem?

**Comment by Alexis-M51** [comment]
> Hi @Alexis-M51 what's the output of libresign-cli command when you pass the path of PDF that you got the problem?

here is the error: 

{"level":"error","error":"validation error (obj#:224): dict=extGStateDict entry=SM: unsupported in version 1.2\nThis file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7\n","time":"2023-02-23T10:02:27+01:00","message":"execution error"}

**Comment by vitormattos** [comment]
This is a limitation of [pdfcpu](https://github.com/pdfcpu/pdfcpu/issues/34) and for now don't will be possible sign a PDF/A. Please, use other way to generate your PDF file.
