### ISSUE TITLE
EMail- Uniqueness NC Accounts

### ISSUE THREAD

**Issue by DevOpsAmph** [LibreSign/libresign#1433]
NC 25.0.3, Libresign 6.2.6, Debian Kernel 5.15.64:

Issue:
Requesting Signature(s) the libresign app searches for the matching NC user id and takes the first hit. 
1. Even disabled NC-User accounts are considered a match. 
2. If multiple NC-User accounts use the same email address - the first one is addressed. 

Solution approach:
- Matching email address to NC-User ID should skip disabled NC-Accounts completeley.
- If there are mutliple NC-User IDs using the same Email-Address a selection-dialog would be very helpful. So the requestor can select wich NC User to send the request to. 

Thanks

**Comment by tasagore** [comment]
For me would be better to change the behavior of the app replacing then email with the nc user. Or have two choices:

A) Internal signatures (just NC user)
B) External signatures (email, verifying that nobody in the NC uses that address)

**Comment by brtptrs** [comment]
It would also be great to have the possibility to restrict signees to users with accounts (via the user names) and not allow external users to create accounts via e-mail invitations.

**Comment by vitormattos** [comment]
I think that this was solved at newest release. 

In the follow screenshot have two accounts with the same email but now you can choose who will sign the document.

![Screenshot_20240424_113456](https://github.com/LibreSign/libresign/assets/1079143/3fe00933-49b8-40cc-a8c2-13d68c358f89)

Closing this issue for now as solved.

PS: If you like this app, don't hesitate to help us to maintain the development sponsoring by GitHub sponsor https://github.com/sponsors/LibreSign or also contacting us to have Enterprise support: https://libresign.coop
