### ISSUE TITLE
Error when I try to sign a pdf

### ISSUE THREAD

**Issue by Iwios** [LibreSign/libresign#1434]
**Describe the bug**
When I try to sign a pdf, I have an error message: Internal error, please contact your admin

**Screenshots**

**Environment information (please complete the following information):**
 - OS: Debian 11
 - Browser Firefox
 - LibreSign Version 6.2.6
 - Nextcloud Server Version 25.0.3

Log:

{"reqId":"TLX0VjRYNpY0DOZQRC5o","level":3,"time":"2023-02-17T13:59:24+01:00","remoteAddr":"192.168.15.11","user":"FVentalon","app":"libresign","method":"POST","url":"/apps/libresign/api/0.1/sign/uuid/649dfca1-3bf5-4866-b1c9-f5309e8d3d70","message":"Class \"TCPDI\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36","version":"25.0.3.2","data":{"app":"libresign"}}
{"reqId":"TLX0VjRYNpY0DOZQRC5o","level":3,"time":"2023-02-17T13:59:24+01:00","remoteAddr":"192.168.15.11","user":"User","app":"libresign","method":"POST","url":"/apps/libresign/api/0.1/sign/uuid/649dfca1-3bf5-4866-b1c9-f5309e8d3d70","message":"[{\"file\":\"\\/var\\/www\\/html\\/nextcloud\\/lib\\/composer\\/composer\\/ClassLoader.php\",\"line\":571,\"function\":\"include\"},{\"file\":\"\\/var\\/www\\/html\\/nextcloud\\/lib\\/composer\\/composer\\/ClassLoader.php\",\"line\":428,\"function\":\"Composer\\\\Autoload\\\\includeFile\"},{\"file\":\"\\/var\\/www\\/html\\/nextcloud\\/apps\\/libresign\\/lib\\/Handler\\/Pkcs12Handler.php\",\"line\":149,\"function\":\"loadClass\",\"class\":\"Composer\\\\Autoload\\\\ClassLoader\",\"type\":\"->\"},{\"file\":\"\\/var\\/www\\/html\\/nextcloud\\/apps\\/libresign\\/lib\\/Service\\/SignFileService.php\",\"line\":790,\"function\":\"writeFooter\",\"class\":\"OCA\\\\Libresign\\\\Handler\\\\Pkcs12Handler\",\"type\":\"->\"},{\"file\":\"\\/var\\/www\\/html\\/nextcloud\\/apps\\/libresign\\/lib\\/Service\\/SignFileService.php\",\"line\":674,\"function\":\"getPdfToSign\",\"class\":\"OCA\\\\Libresign\\\\Service\\\\SignFileService\",\"type\":\"->\"},{\"file\":\"\\/var\\/www\\/html\\/nextcloud\\/apps\\/libresign\\/lib\\/Service\\/SignFileService.php\",\"line\":597,\"function\":\"getFileToSing\",\"class\":\"OCA\\\\Libresign\\\\Service\\\\SignFileService\",\"type\":\"->\"},{\"file\":\"\\/var\\/www\\/html\\/nextcloud\\/apps\\/libresign\\/lib\\/Controller\\/SignFileController.php\",\"line\":202,\"function\":\"sign\",\"class\":\"OCA\\\\Libresign\\\\Service\\\\SignFileService\",\"type\":\"->\"},{\"file\":\"\\/var\\/www\\/html\\/nextcloud\\/apps\\/libresign\\/lib\\/Controller\\/SignFileController.php\",\"line\":180,\"function\":\"sign\",\"class\":\"OCA\\\\Libresign\\\\Controller\\\\SignFileController\",\"type\":\"->\"},{\"file\":\"\\/var\\/www\\/html\\/nextcloud\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php\",\"line\":225,\"function\":\"signUsingUuid\",\"class\":\"OCA\\\\Libresign\\\\Controller\\\\SignFileController\",\"type\":\"->\"},{\"file\":\"\\/var\\/www\\/html\\/nextcloud\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php\",\"line\":133,\"function\":\"executeController\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\"},{\"file\":\"\\/var\\/www\\/html\\/nextcloud\\/lib\\/private\\/AppFramework\\/App.php\",\"line\":172,\"function\":\"dispatch\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\"},{\"file\":\"\\/var\\/www\\/html\\/nextcloud\\/lib\\/private\\/Route\\/Router.php\",\"line\":298,\"function\":\"main\",\"class\":\"OC\\\\AppFramework\\\\App\",\"type\":\"::\"},{\"file\":\"\\/var\\/www\\/html\\/nextcloud\\/lib\\/base.php\",\"line\":1047,\"function\":\"match\",\"class\":\"OC\\\\Route\\\\Router\",\"type\":\"->\"},{\"file\":\"\\/var\\/www\\/html\\/nextcloud\\/index.php\",\"line\":36,\"function\":\"handleRequest\",\"class\":\"OC\",\"type\":\"::\"}]","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36","version":"25.0.3.2","data":{"app":"libresign"}}

**Comment by vitormattos** [comment]
Can't reproduce, test with newest version.
