### ISSUE TITLE
l10n: Password or passwords?

### ISSUE THREAD

**Issue by Valdnet** [LibreSign/libresign#144]
Is this information: 
https://github.com/LibreSign/libresign/blob/99d9ca0c534dec514bad57bf40f35cae8172757a/src/views/CreateUser.vue#L62
concerns the comparison of two entered passwords?

If so, it should be: `Passwords do not match`.

Unless it is a password comparison to another signature password.

**Comment by vitormattos** [comment]
Yes, it concerns password and password confirmation.

The signature password has nothing to do with this message

**Comment by Valdnet** [comment]
> Yes, it concerns password and password confirmation.

So correctly it should be: `Passwords do not match`. Yes?

**Comment by vitormattos** [comment]
Yes

**Comment by Valdnet** [comment]
PR made. Please merge 😉.
