### ISSUE TITLE
Several signatures on one document

### ISSUE THREAD

**Issue by swi33ty** [LibreSign/libresign#1449]
**GOAL:**
A single pdf file needs to be signed by 4 people.

**Steps:**
- 4 different accounts in NC (ver 25) - LDAP authorization, 4 different e-mail addresses, 4 different physical machines.
- 1st user (file owner)  is signing pdf without any problems by himself
- 1st user requesting to sign with 2nd user. He's able to do all the steps (pointing to the place when the signature needs to be put, etc) 
- 2nd user receiving an e-mail message "there's a document ready to sign"
- when 2nd user clicks the button from the e-mail message, he's receiving information 
"Congratulations you have digitally signed a document using LibreSign" without any request to sign the document first.
- when I'm checking the status of this document - there's information, that 1st user signed the document, but the user2 status is pending.

**Expectations**
Allow multiple users to sign the document.

Nextcloud ver 25 /LDAP as authorization/
LibreSign 6.2.7

**Comment by swi33ty** [comment]
heartbeat check ...
Any chance of this?

**Comment by vitormattos** [comment]
Hi,

I did the scenario with success:

Upload a document to app Files
At file list, go to menu and select "Open in LibreSign"
Fill the email of user A
Click at "Add" button
Fill the email of user B
Click at "Add" button
Click at "Submit request"
At the confirm box about configure visible elements, click on "Ok"
Click over user A
Click on "Save"
Then you will see a "clips" at right side of user A
Click over user B
Change the position of signature box of user B
Click on "Save"
Then you will see a "clips" at right side of user B
Click at "Request" button
At the confirm box, click on "Ok"
Then you will see the status "able to sign"
And you will see the button "Sign"
Click at the button "Sign"
You will be redirected to signature page
Click at "Sign the document"
Fill your signature password
Click at "Sign the document"
Then you will be redirected to validation page
And you will see a date under user A
And you will see "no date" under user B

As user B
Access the link that user B received by email in a new browser session or maybe an anonymous window
Follow the steps to sign the document
Then you will be redirected to validation page
And you will see a date under user A
And you will see a date under user B

I can't reproduce the reported problem with the steps that you send.
Could you provide more details about what you did?

**Comment by swi33ty** [comment]
Oh thank you
Now I can see that I need to fill all e-mails at once (one package)
I've tried to do it separately - that caused problems.
I did it using your step-by-step and it works
