### ISSUE TITLE
l10n: Date: at or on?

### ISSUE THREAD

**Issue by Valdnet** [LibreSign/libresign#146]
Question from Transifex user:

> Available *at* {date} or *on* {date} ?

Applies to this text string:
https://github.com/LibreSign/libresign/blob/a3e3085cc5c99e5f9e5e873a1bb997c0938256e2/src/views/LibresignTab.vue#L141

**Comment by vitormattos** [comment]
In this case the variable name is wrong.
It should be {place} maybe
And yes, it should be on

**Comment by Valdnet** [comment]
So it should be: `Signed document available on {date}`.

**Comment by vitormattos** [comment]
It is also good to replace `date` with `place`

**Comment by Valdnet** [comment]
He understands that this requires changing the values of the variables. Can @vitormattos you create a PR?

**Comment by vitormattos** [comment]
I can create
