### ISSUE TITLE
Dark mode fix: Define your initials

### ISSUE THREAD

**Issue by bigbeka** [LibreSign/libresign#1460]
Define your initials > Confirm your initials: not visible in dark mode

<img width="1202" alt="Screenshot 2023-02-22 at 21 34 10" src="https://user-images.githubusercontent.com/53529055/220761559-891deab5-c543-4a97-86f5-558cd873d9e2.png">

**Comment by vitormattos** [comment]
I don't know if have a simple solution. What we will do if the signature color is white and the background also is white?

**Comment by vitormattos** [comment]
The initials feature was temporary disabled because we haven't UI to put an initial in a document.

We will follow this topic at this issue: https://github.com/LibreSign/libresign/issues/1461
