### ISSUE TITLE
Dark mode fix: Define your signature

### ISSUE THREAD

**Issue by bigbeka** [LibreSign/libresign#1461]
Define your signature > Confirm your signature: not visible in dark mode

<img width="1202" alt="Screenshot 2023-02-22 at 21 34 10" src="https://user-images.githubusercontent.com/53529055/220761559-891deab5-c543-4a97-86f5-558cd873d9e2.png">

**Comment by vitormattos** [comment]
I don't know if have a simple solution. What we will do if the signature color is white and the background also is white?

**Comment by bigbeka** [comment]
99.9999% of documents are white background, hence the signature area can be in white, signature line in black and the rest of the UI can be system darkness.

alternatively, signature box could also have a button to inverse the darkness of the sign satire box.
