### ISSUE TITLE
Dark mode fix: Define your signature & initials not visible

### ISSUE THREAD

**Issue by bigbeka** [LibreSign/libresign#1462]
Dark mode fix: Define your signature & initials not visible

<img width="804" alt="Screenshot 2023-02-22 at 21 33 31" src="https://user-images.githubusercontent.com/53529055/220762134-2547d4a7-0da5-469c-8050-f769f75531a4.png">

**Comment by vitormattos** [comment]
Closed by https://github.com/LibreSign/libresign/pull/1541
