### ISSUE TITLE
Fix formatting of the text on account creation

### ISSUE THREAD

**Issue by bigbeka** [LibreSign/libresign#1463]
The text is justified to the width, I believe it should be centre or left?

<img width="1164" alt="Screenshot 2023-02-22 at 21 27 16" src="https://user-images.githubusercontent.com/53529055/220762343-d4e777e1-d9b9-4e90-9494-7ecd3ad8fb97.png">

**Comment by vitormattos** [comment]
This screen was rewrite. Follow the new layout:

![Screenshot_20240424_113842](https://github.com/LibreSign/libresign/assets/1079143/a3db59f4-2361-427f-b3d3-065fb6908e0c)
