### ISSUE TITLE
Redirection to requested document, not to home directory of nextcloud

### ISSUE THREAD

**Issue by bigbeka** [LibreSign/libresign#1464]
After account creation redirect to the document that needs to be signed, not to the Nextcloud’s default dashboard.

<img width="1164" alt="Screenshot 2023-02-22 at 21 27 16" src="https://user-images.githubusercontent.com/53529055/220762949-340c99a2-955a-4479-9923-873822627a18.png">

**Comment by vitormattos** [comment]
Duplicated of  #1463
