### ISSUE TITLE
Libresign on Nextcloud - Qualified e-Signature (QES)

### ISSUE THREAD

**Issue by Githopp192** [LibreSign/libresign#1479]
**Describe the bug**

**To Reproduce**
is LibreSign supporting QES in any form ?

**Expected behavior**

As far i understand correctly legally binding document signatures (i.e PDF), needs to have the QES Label.

Is this possible through LibreSign with Nextcloud (may by configuring a specific/public Root certificate ?)

**Screenshots**

**Environment information (please complete the following information):**
 - OS: RHEL 8.7
 - Browser : MS Edge, newest Versioin
 - LibreSign Version 5.2.1
 - Nextcloud Server Version 24.0.8
 - Logs (get the entries from nextcloud.log related with LibreSign i.e `tail -f data/nextcloud.log|grep libresign`)

**Comment by vitormattos** [comment]
When you generate the root certificate at LibreSign admin settings, the LibreSign will generate your root certificate outside of a PKI, but all certificates that LibreSign generate to all users is a PFX file using the root certificate.

You can replace the PFX files generated by LibreSign by a PFX file generated under the PKI of your country.

You need to do this flow to generate your self signed certificate as pfx format:

![image](https://user-images.githubusercontent.com/1079143/222611147-bea851eb-7cd2-4399-9b72-5f3032f765f6.png)

If you wish to use your own pfx file and don't use the pfx generated by LibreSign, you can replace the signature.pfx file at this place:

![image](https://user-images.githubusercontent.com/1079143/222611292-fbd3bd9e-d684-41f9-9bc7-8e83dcc76a14.png)

When you replace the LibeSign PFX file by your own certificate, you will sign all documents using LibreSign with your pfx file with your pfx password.
