### ISSUE TITLE
.htaccess missing ffrom install

### ISSUE THREAD

**Issue by velocity08** [LibreSign/libresign#1488]
G'Day Team

seem to be missing a .htaccess file from the setup according to Nextcloud.

see error message below.

let me know whats needed to assist troubleshoot this issue?

""Cheers
G

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- libresign
	- FILE_MISSING
		- vendor/tecnickcom/tcpdf/tools/.htaccess

Raw output
==========
Array
(
    [libresign] => Array
        (
            [FILE_MISSING] => Array
                (
                    [vendor/tecnickcom/tcpdf/tools/.htaccess] => Array
                        (
                            [expected] => 93f01c456d82fe5d666672aa6a52432e510e23cc751cefa32b48342f29d0be6fa1ae604813ef9a687469bae1ae9afd7bef9d484e43b7b322ce30576416f4e756
                            [current] => 
                        )

                )

        )

)

**Comment by chnateag** [comment]
Hi everyone, same thing here

**Comment by vitormattos** [comment]
Duplicated of #1455
