### ISSUE TITLE
Error when I try to sign : Internal Error: Please contact your administrator

### ISSUE THREAD

**Issue by Iwios** [LibreSign/libresign#1586]
**Describe the bug**
When I try to sign a pdf, I put my password, and after click en sign, I have this message error:
Internal error: Please contact your administrator

**To Reproduce**
- I'm an authenticated user
- Upload a file
- Click on 'Open in Libresign'
- Click on the username of user need to sign
- Put the frame where the sign does appear
- Log with the user sign, clink on sign
- Put your password
- Click on sign
- See the error message on top right

**Environment information (please complete the following information):**
 - OS: Debian 11
 - Browser Firefox
 - LibreSign Version 6.3.0
 - Nextcloud Server Version 25.0.3

**Error message:**

`	[{"file":"\/var/www/html/apps\/libresign\/vendor\/tecnickcom\/tcpdf\/tcpdf.php","line":6412,"function":"max"},{"file":"\/var/www/html/apps\/libresign\/lib\/Handler\/Pkcs12Handler.php","line":194,"function":"Write","class":"TCPDF","type":"->"},{"file":"\/var/www/html/apps\/libresign\/lib\/Service\/SignFileService.php","line":800,"function":"writeFooter","class":"OCA\\Libresign\\Handler\\Pkcs12Handler","type":"->"},{"file":"\/var/www/html/apps\/libresign\/lib\/Service\/SignFileService.php","line":684,"function":"getPdfToSign","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/var/www/html/apps\/libresign\/lib\/Service\/SignFileService.php","line":597,"function":"getFileToSing","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/var/www/html/apps\/libresign\/lib\/Controller\/SignFileController.php","line":207,"function":"sign","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/var/www/html/apps\/libresign\/lib\/Controller\/SignFileController.php","line":180,"function":"sign","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/var/www/html/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":225,"function":"signUsingUuid","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/var/www/html/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/var/www/html/lib\/private\/AppFramework\/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/var/www/html/lib\/private\/Route\/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"\/var/www/html/lib\/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"\/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}]`

2nde error message:

max(): Argument #1 ($value) must contain at least one element

**Comment by Iwios** [comment]
After many search, this bug is from tcpdf.
An update have been develop but not push.

This is the link where I find the change:
https://github.com/tecnickcom/TCPDF/commit/ab5fe4d024eddaeb918a3cefe59b3aa0fb5aa1c0

Sorry for the message with no link with LibreSign :)

**Comment by vitormattos** [comment]
Yes, this is from TCPDF.

Unfortunately we have this dependency to put the footer at all pages. I think that if you disable the feature to put the footer at PDF will work fine. This package is used by a lot of PHP projects but have problems with specific contents of PDF files.

**Comment by vitormattos** [comment]
Duplicated of #889
