### ISSUE TITLE
Suggestion: Use Hash Value instead of UUID to Validate a Document

### ISSUE THREAD

**Issue by karazonanas** [LibreSign/libresign#1594]
Hey there,

I noticed (if I'm not mistaken) that Libresign requires users to enter the UUID of a document to validate it. I think using the hash value of a document would be a better option to ensure that it hasn't been modified.

Hash values are unique digital fingerprints that are created from the contents of a file. Even if a single character is changed, the hash value will be completely different. Using hash values to validate documents is more secure than using UUIDs because UUIDs can be manipulated by someone with malicious intent.

So, my suggestion is to consider using hash values instead of UUIDs to validate documents in Libresign. This would provide a more secure and reliable method for ensuring that documents have not been tampered with.

**Comment by vitormattos** [comment]
Hi,

The UUID is only to identify the document by an identifier a bit big, not to validate the document.

The document is digital signed using signature key with PKCS#12 format and the signed version of PDF is stored at Nextcloud instance. When you send the UUID at validation page, you will see the signed PDF file and you also can download this PDF and validate using other software like [Okular](https://okular.kde.org).

The UUID used at LibreSign is unique, haven't problem to have more than a file with the same UUID.

**Comment by vitormattos** [comment]
Closing the issue because isn't a feature request neither a bug report. Was only to clarify about the working of sign and validate documents.
