### ISSUE TITLE
Nextcloud 21.0.1: Sidebar to sign a document not available anymore

### ISSUE THREAD

**Issue by Bolli84** [LibreSign/libresign#165]
After the upgrade to nextcloud 21.0.1(stable), the app sidebar vanished.

1. Updated by web-updater
2. Disable libresign
3. Reinstall libresign app
4. Create new certificate
5. LibreSign menu and "Certificate creator" is available, but not for PDF-files to be signed.

**Comment by vitormattos** [comment]
At the moment, as described in the README, the signature flow can only be started via API.

**Comment by Bolli84** [comment]
No, in the nextcloud 20 I had a nice field to sign a document once i clicked on "... Details" and then "signature

**Comment by vitormattos** [comment]
The option to sign a PDF by going to the details of the file through the Files app was developed using jQuery, a deprecated framework in Nextcloud.

In future versions we will rewrite this functionality in VueJS which was adopted as a standard for Nextcloud.

**Comment by Bolli84** [comment]
Which means, the functionalityis gone for the moment?

**Comment by vitormattos** [comment]
Yes.
It is no longer recommended to use jQuery on the Nextcloud.

We are looking for ways to get sponsor (funding) for the development of this app. At the moment in our country unfortunately the GitHub Sponsor is not available.

**Comment by Bolli84** [comment]
OK, 

just the dsvTAB is missing. 

How much funding would you need and what would be outcome?

**Comment by vitormattos** [comment]
We need 6k USD to maintain a fulltime team in this project but whatever comes is welcome and already helps.

We plan to implement:
- users request document signatures for as many people as they wish and with various rules such as:
   - Validate signatures with a hash and add or not a footer with a validation hash (or qrcode) in the PDF. # 130, # 43, # 127
   - Request that signatures must follow an order
- View a list of LibreSign documents # 5
- Generate a digital certificate for every Nextcloud user and improve the generation of certificates # 9
- Make it possible to sign documents through Files # 60

Some of these tasks are in the project issues. All the tasks we do are exposed in the issues.

We have some internal notes, I will update the planning for the next release and return on this issue with more information.

This is a summary so as not to get too large a text.

**Comment by vitormattos** [comment]
Hi @Bolli84,

I reviewed and updated all issues and organized them in the versions of LibreSign that you can view in this link:

https://github.com/LibreSign/libresign/projects

**Comment by vinicios-gomes** [comment]
Hi @Bolli84  
we updated LibreSign recently, so we can start the subscription flow using the app file, as before. However, the flow is different from the previous one, to sign a document, you need to request the signature, we are developing a flow where you do not necessarily need to request to be able to sign any document in your Nextcloud.
Today this option is only available on Nextcloud 20. We are looking for solutions for compatibility with Nextcloud 21.

You can update your LibreSign version to get this new feature.

On behalf of the entire @LibreSign/developer  team, we appreciate your feedback.

**Comment by vitormattos** [comment]
Nextcloud changed the way the tab works from 20 to 21.

In #254 a conditional was inserted to load a JS for the Nextcloud 20 and another for the 21
