### ISSUE TITLE
Prevent non-registered users from creating Nextcloud accounts

### ISSUE THREAD

**Issue by brtptrs** [LibreSign/libresign#1650]
**Describe the bug**
Everyone can create Nextcloud accounts via signing-requests. On our system, only admins are allowed to create accounts.

**To Reproduce**
- Send a request to a mail address of non-users
- External person can register an account, although it is not allowed on our system

**Expected behavior**
- Only registered users can be invited to sign a document
- No external person should be allowed to register a Nextcloud account via a request to sing a document, sent to an unregistered mail address

**Comment by vitormattos** [comment]
Related with #686

**Comment by vitormattos** [comment]
Would be solve by #1406
Need more funding.

**Comment by vitormattos** [comment]
Fixed at newest release. Now is possible to uncheck the option "request to create account".

![Screenshot_20240424_110624](https://github.com/LibreSign/libresign/assets/1079143/9a352118-5925-45a8-abeb-0a75fd240ee0)
