### ISSUE TITLE
Nextcloud 25 AIO has current version of Libresign as  6.3.1

### ISSUE THREAD

**Issue by prevail90** [LibreSign/libresign#1672]
I am having issues with getting LibreSign to work with Nextcloud AIO 25. I installed LibreSign from the Apps page on Nextcloud. but I am having the issue of the binaries not installing. After attempting the php commands on another issue, I believe the issue lies in the version. 
![Screenshot_20230424_184427](https://user-images.githubusercontent.com/90661674/234135030-c03b636a-e358-4629-b7c6-2bdfed02c8d8.png)
![Screenshot_20230424_183447](https://user-images.githubusercontent.com/90661674/234135032-707c7557-38bd-4e99-8d04-b5131b048400.png)

**Comment by prevail90** [comment]
Ok I was able to get to 7.1.1 and NC26 but still having the same issue.

**Comment by vitormattos** [comment]
Run the follow command inside the container:

`<yourJavaPath> -version`

The java path is the same of you get  on the first print screen and the same that you also can get with the follow commands:
```
occ libresign:configure:check
occ config:app:get libresign java_path
```
With the -v option will need to return: https://github.com/LibreSign/libresign/blob/main/lib/Service/InstallService.php#L31

More details:

https://github.com/LibreSign/libresign/blob/main/lib/Service/ConfigureCheckService.php#L167-L169

**Comment by vitormattos** [comment]
This comparison need to return true:
https://github.com/LibreSign/libresign/blob/main/lib/Service/ConfigureCheckService.php#L167-L169
And the -version need to return https://github.com/LibreSign/libresign/blob/main/lib/Service/InstallService.php#L31

But you don't need to uninstall all, only need to check the return of -version option and verify if contains the same that as I mentioned.

The web interface do the same as the install command that you executed.

What return when you run the configure:check command?

**Comment by prevail90** [comment]
![Screenshot_20230426_104741](https://user-images.githubusercontent.com/90661674/234613738-79b6d7e8-396f-4a08-a85c-27deb314763a.png)
This is what I got fromthe configure check command

**Comment by prevail90** [comment]
also added the imagick to the environment when I recreated the server and that has an error as well.

**Comment by vitormattos** [comment]
And what is the value returned by -version?

**Comment by prevail90** [comment]
![Screenshot_20230426_183136](https://user-images.githubusercontent.com/90661674/234716958-a4793360-bf25-437f-89fa-951b10c2880e.png)

**Comment by vitormattos** [comment]
Did you executed the uninstall first? You haven't any file inside libresign data folder and your configure:check returned that you haven't any file. Run first the install to download the binaries.

**Comment by Aniket-IN** [comment]
I'm also facing the same issue, 

I created the `java_test.php` file, here's the output:
![image](https://user-images.githubusercontent.com/64463116/235310176-083929ec-538d-43f1-8aa1-2411d130b41c.png)

Here's also the output of when I try to get the Java version:
![image](https://user-images.githubusercontent.com/64463116/235310213-e87f6c4e-460e-4d86-a05e-6bbfb89f804b.png)

**Comment by vitormattos** [comment]
Hi @Aniket-IN could you also check this?

```php
<?php
var_dump([
    'architecture' => php_uname('m'),
    'bits'         => PHP_INT_SIZE * 8,
]);

**Comment by Aniket-IN** [comment]
Hey @vitormattos,
Here's the output:
```sh
bash-5.1# php test_1.php 
array(2) {
  ["architecture"]=>
  string(6) "x86_64"
  ["bits"]=>
  int(64)
}
 ```

**Comment by Aniket-IN** [comment]
Also we get these error logs when we try to sign a document.
![image](https://github.com/LibreSign/libresign/assets/64463116/2e6bb9ed-0cb5-415a-8b4c-80f330a50647)

However, we can open the Libresign pages:
![image](https://github.com/LibreSign/libresign/assets/64463116/6b85e158-7207-4094-86de-21201e26edfb)

**Comment by vitormattos** [comment]
Closing this issue to centralize this topic here: #1409
