### ISSUE TITLE
Failed to sign any document (Error Message - Internal error. Contact admin. Log - Entity which should be updated has no id)

### ISSUE THREAD

**Issue by kevinkuan1969** [LibreSign/libresign#1674]
**Describe the bug**
Failed to sign any document and identification document and error message 'Internal error and contact admin'

Screenshots
![image](https://user-images.githubusercontent.com/80019930/234639388-c3fbed9f-2ff0-4298-b4d8-89978892cc64.png)

**Environment information (please complete the following information):**
 - OS: Ubuntu 22.04 
 - LibreSign Version 7.1.1
 - Nextcloud Server Version 26.0.1 
 - Logs 

<html>
<body>

Error | libresign | [{"file":"\/var\/www\/nextcloud\/apps\/libresign\/lib\/Service\/SignFileService.php","line":650,"function":"update","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"\/var\/www\/nextcloud\/apps\/libresign\/lib\/Controller\/SignFileController.php","line":202,"function":"storeUserMetadata","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/var\/www\/nextcloud\/apps\/libresign\/lib\/Controller\/SignFileController.php","line":168,"function":"sign","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":230,"function":"signUsingFileId","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":1056,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"\/var\/www\/nextcloud\/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}] |   | 27 minutes ago
-- | -- | -- | -- | --
Error | libresign | Entity which should be updated has no id

</body>
</html>

Please find below Libresign configuration when run 'sudo -u www-data php /var/www/nextcloud/occ config:list libresign'

{
    "apps": {
        "libresign": {
            "add_footer": "1",
            "approval_group": "[\"Approval Group\"]",
            "authkey": "xxxxxxxx",
            "cfsslUri": "http:\/\/127.0.0.1:8888\/api\/v1\/cfssl\/",
            "cfssl_bin": "\/var\/www\/nextcloud\/data\/appdata_xxxxx\/libresign\/cfssl",
            "collect_metadata": "1",
            "configPath": "\/var\/www\/nextcloud\/data\/appdata_xxxxxx\/libresign\/cfssl_config\/",
            "default_user_folder": "LibreSign ",
            "enabled": "yes",
            "identification_documents": "1",
            "installed_version": "7.1.1",
            "jsignpdf_jar_path": "\/var\/www\/nextcloud\/data\/appdata_octvkfccyu6e\/libresign\/jsignpdf-2.2.0\/JSignPdf.jar",
            "legal_information": "xxxxxxxxxxxx\n",
            "notifyUnsignedUser": "1",
            "rootCert": "{\"commonName\":\"xxxxxx\",\"names\":[]}",
            "types": "",
            "validation_site": "https:\/\/xxxxxxx",
            "webhook_authorized": "[\"Approval Group\"]",
            "write_qrcode_on_footer": "1"
        }
    }
}

**Comment by vitormattos** [comment]
This is a bit strange because the fileUser property need to have an ID at this point of code.

If possible, change the file `lib/Service/SignFileService.php` before the row 650 (`$this->fileUser->setMetadata($metadata);`) and add the follow code:
```php
$this->logger->error('file user data', $this->fileUser);
```
This will send to log the content of fileUser property and you will can see at the log file.

**Comment by vitormattos** [comment]
LibreSign haven't a setting called `types` and haven't any place adding or reading this setting. Maybe, you could created accidentally using the occ config:app:set.

**Comment by vitormattos** [comment]
Have an error at row that I send to you add. Change to this, now the log will work
```php
$this->logger->error('file user data: ' . serialize($this->fileUser));
```

**Comment by kevinkuan1969** [comment]
It still displayed 2 sets of errors and still not working. Any chance to look at the log again. Thanks.

<html>
<body>


Error | libresign | [{"file":"\/var\/www\/nextcloud\/apps\/libresign\/lib\/Service\/SignFileService.php","line":649,"function":"error","class":"OC\\AppFramework\\ScopedPsrLogger","type":"->"},{"file":"\/var\/www\/nextcloud\/apps\/libresign\/lib\/Controller\/SignFileController.php","line":202,"function":"storeUserMetadata","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/var\/www\/nextcloud\/apps\/libresign\/lib\/Controller\/SignFileController.php","line":168,"function":"sign","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":230,"function":"signUsingFileId","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":1056,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"\/var\/www\/nextcloud\/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}] |   | 9 hours ago
-- | -- | -- | -- | --
Error | libresign | OC\AppFramework\ScopedPsrLogger::error(): Argument #2 ($context) must be of type array, OCA\Libresign\Db\FileUser given, called in /var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php on line 649 |   | 9 hours ago


</body>
</html>

**Comment by kevinkuan1969** [comment]
It maybe the bug of Libresign Adminstration which the setting is not refreshed or updated after any changes.
Refer the case #1684
