### ISSUE TITLE
Implement layout to add new factor identifier user

### ISSUE THREAD

**Issue by enieber** [LibreSign/libresign#1678]
Implement new layout of admin based in #1406 

add new factor to identifier user:

![image](https://user-images.githubusercontent.com/7907068/235292634-b62e82b9-7fd6-4ea7-af31-792812aa1450.png)

**Comment by enieber** [comment]
It is part implemented, need review

**Comment by vitormattos** [comment]
Solved at newest release.

Follow the layout:

![Screenshot_20240424_110624](https://github.com/LibreSign/libresign/assets/1079143/20b74054-b19b-4ed5-86ee-406e24c0dbf2)
