### ISSUE TITLE
Authorized group are not refreshed after changes in Nextcloud User Management  

### ISSUE THREAD

**Issue by kevinkuan1969** [LibreSign/libresign#1684]
After rename or create the new group in Nextcloud User Management, the settings in Libresign Administration are not displayed according with the new update.

The screen of Nextcloud User Management:
![image](https://user-images.githubusercontent.com/80019930/235334085-0cf06a8b-55ca-478c-aaab-ca6f6ecc5f3e.png)

The screen of Libresign Administration:

![image](https://user-images.githubusercontent.com/80019930/235334121-d64810ef-b4e9-4acd-866d-adea89023541.png)

![image](https://user-images.githubusercontent.com/80019930/235334139-2ad3c4d0-aa85-4551-9f8a-b9a8a0e175a0.png)

Environment information (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome 
 - LibreSign Version 7.1.1
 - Nextcloud Server Version 26.0.1

**Comment by vitormattos** [comment]
Solved at newest release.

PS: If you like this app, don't hesitate to help us to maintain the development sponsoring by GitHub sponsor https://github.com/sponsors/LibreSign or also contacting us to have Enterprise support: https://libresign.coop
