### ISSUE TITLE
Simplify root certificate generation

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/libresign#172]
The generation of root certificates has generated issues with questions. It is good to make it more friendly to system administrators.

## Backend
- [ ] Add comments describing the arguments of the `cfssl serve` command in the` entrypoint.sh` file or link to the cfssl documentation. Second option is better.
- [ ] Improve LibreSign documentation on CFSSL setup
- [ ] Put a sample file of the CFSSL configuration json
- [ ] Create a dictionary of standard fields for generating the root certificate containing: field name, field description
- [ ] Make it possible to receive from the frontend which fields will be filled when generating the root certificate
- [ ] Receive the CFSSL server IP from the frontend

## Frontend
- [ ] Set the CFSSL server IP
- [ ] Component for adding multiple values for creating the certificate showing tooltip with the description of the field

**Comment by vitormattos** [comment]
Fix #120

**Comment by theancients89** [comment]
Hi there, I'd really like to see these instructuions, I've followed what's there to the mark and can't generate a root certificate. CFSSL is running.

**Comment by vitormattos** [comment]
Moved to GitLab:

https://gitlab.com/librecodecoop/libresign/libresign/-/issues/172
