### ISSUE TITLE
Install Libresign on NextCloud Snaps

### ISSUE THREAD

**Issue by spoiledtechie** [LibreSign/libresign#1746]
**Describe the bug**
I am getting a health url not found.

In CfsslHandler.php line 188:                                                                                 [Exception (1)                                                              ]  Endpoint /health of CFSSL server not found. Maybe you are using incompatibl    e version of CFSSL server. Use latests version.                                                                                              

**To Reproduce**
- I'm an authenticated user
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**
In CfsslHandler.php line 188:                                                                                 [Exception (1)                                                              ]  Endpoint /health of CFSSL server not found. Maybe you are using incompatibl    e version of CFSSL server. Use latests version.                                                                                                             Exception trace:  at /var/snap/nextcloud/34542/nextcloud/extra-apps/libresign/lib/Handler/CfsslHandler.php:188 OCA\Libresign\Handler\CfsslHandler->health() at /var/snap/nextcloud/34542/nextcloud/extra-apps/libresign/lib/Service/InstallService.php:604 OCA\Libresign\Service\InstallService->generate() at /var/snap/nextcloud/34542/nextcloud/extra-apps/libresign/lib/Command/Configure/Cfssl.php:123 OCA\Libresign\Command\Configure\Cfssl->execute() at /var/snap/nextcloud/34542/nextcloud/extra-apps/recognize/vendor/symfony/console/Command/Command.php:298 Symfony\Component\Console\Command\Command->run() at /snap/nextcloud/34542/htdocs/core/Command/Base.php:177 OC\Core\Command\Base->run() at /var/snap/nextcloud/34542/nextcloud/extra-apps/recognize/vendor/symfony/console/Application.php:1040 Symfony\Component\Console\Application->doRunCommand() at /var/snap/nextcloud/34542/nextcloud/extra-apps/recognize/vendor/symfony/console/Application.php:301 Symfony\Component\Console\Application->doRun() at /var/snap/nextcloud/34542/nextcloud/extra-apps/recognize/vendor/symfony/console/Application.php:171 Symfony\Component\Console\Application->run() at /snap/nextcloud/34542/htdocs/lib/private/Console/Application.php:214 OC\Console\Application->run() at /var/snap/nextcloud/34542/nextcloud/extra-apps/occweb/lib/Controller/OccController.php:59 OCA\OCCWeb\Controller\OccController->run() at /var/snap/nextcloud/34542/nextcloud/extra-apps/occweb/lib/Controller/OccController.php:75 OCA\OCCWeb\Controller\OccController->cmd() at /snap/nextcloud/34542/htdocs/lib/private/AppFramework/Http/Dispatcher.php:225 OC\AppFramework\Http\Dispatcher->executeController() at /snap/nextcloud/34542/htdocs/lib/private/AppFramework/Http/Dispatcher.php:133 OC\AppFramework\Http\Dispatcher->dispatch() at /snap/nextcloud/34542/htdocs/lib/private/AppFramework/App.php:172 OC\AppFramework\App::main() at /snap/nextcloud/34542/htdocs/lib/private/Route/Router.php:298 OC\Route\Router->match() at /snap/nextcloud/34542/htdocs/lib/base.php:1048 OC::handleRequest() at /snap/nextcloud/34542/htdocs/index.php:36libresign:configure:cfssl [--cn CN [--ou OU] [-o|--o O] [-c|--c C] [-s|--st ST] [-l|--l L] [--config-path CONFIG-PATH] [--cfssl-uri CFSSL-URI]]

**Environment information (please complete the following information):**
occ $ libresign:configure:check  -vvv
 --------- ----------------- ---------------------------------------------------------------------------------------------------------------------- ---------------------------------------------------   Status    Resource          Message                                                                                                                Tip                                                 --------- ----------------- ---------------------------------------------------------------------------------------------------------------------- ---------------------------------------------------   success   java              Java version: openjdk version "17.0.5" 2022-10-18                                                                                                                           success   java              Java binary: /var/snap/nextcloud/common/nextcloud/data/appdata_oc5s3859aysz/libresign/java/jdk-17.0.5+8-jre/bin/java                                                        success   jsignpdf          JSignPdf version: 2.2.0                                                                                                                                                     success   jsignpdf          JSignPdf path: /var/snap/nextcloud/common/nextcloud/data/appdata_oc5s3859aysz/libresign/jsignpdf-2.2.0/JSignPdf.jar                                                          error    imagick           Extension Imagick required                                                                                             https://github.com/LibreSign/libresign/issues/829    success   cfssl             CFSSL binary path: /var/snap/nextcloud/common/nextcloud/data/appdata_oc5s3859aysz/libresign/cfssl                                                                           success   cfssl             CFSSL: Version: 1.6.3, Runtime: go1.18                                                                                                                                       error    cfssl-configure   CFSSL (root certificate) not configured.                                                                               Run occ libresign:configure:cfssl --help            --------- ----------------- ---------------------------------------------------------------------------------------------------------------------- --------------------------------------------------- 
**Additional context**

Trying to install Libresign on NextCloud Snap.  Both snap and Nextcloud and Libresign are all latest versions.  But for some reason, I can't generate the certificate.

**Comment by vitormattos** [comment]
Looking the backtrace sounds that you are using the command `libresign:configure:cfssl`, if yes, could you share the command with the options that you used?

**Comment by vitormattos** [comment]
Closing the issue without interaction with a lot of time.

Please check the newest release of LibreSign to identify if the problem persists.

PS: If you like this app, don't hesitate to help us to maintain the development sponsoring by GitHub sponsor https://github.com/sponsors/LibreSign or also contacting us to have Enterprise support: https://libresign.coop
