### ISSUE TITLE
Error: Certificate expired

### ISSUE THREAD

**Issue by Bolli84** [LibreSign/libresign#1762]
Creating a document for signature, for a particular user it is not possible to sign and I get the error: Certificate expired

When a request for the signature is started (either by me, or by someone else), the procedure is working normal.
Once a particulart user wants to sign it, the user gets the pp-up "Internal error. contact admin"
The other users can sign well.

The following output is in the nextcloud log:

> [{"file":"\/var\/www\/vhosts\/SERVER-HOST\/SERVER-HOST\/apps\/libresign\/vendor\/jsignpdf\/jsignpdf-php\/src\/JSignPDF.php","line":29,"function":"sign","class":"Jeidison\\JSignPDF\\Sign\\JSignService","type":"->"},{"file":"\/var\/www\/vhosts\/SERVER-HOST\/SERVER-HOST\/apps\/libresign\/lib\/Handler\/JSignPdfHandler.php","line":105,"function":"sign","class":"Jeidison\\JSignPDF\\JSignPDF","type":"->"},{"file":"\/var\/www\/vhosts\/SERVER-HOST\/SERVER-HOST\/apps\/libresign\/lib\/Handler\/JSignPdfHandler.php","line":77,"function":"signUsingVisibleElements","class":"OCA\\Libresign\\Handler\\JSignPdfHandler","type":"->"},{"file":"\/var\/www\/vhosts\/SERVER-HOST\/SERVER-HOST\/apps\/libresign\/lib\/Handler\/Pkcs12Handler.php","line":126,"function":"sign","class":"OCA\\Libresign\\Handler\\JSignPdfHandler","type":"->"},{"file":"\/var\/www\/vhosts\/SERVER-HOST\/SERVER-HOST\/apps\/libresign\/lib\/Service\/SignFileService.php","line":618,"function":"sign","class":"OCA\\Libresign\\Handler\\Pkcs12Handler","type":"->"},{"file":"\/var\/www\/vhosts\/SERVER-HOST\/SERVER-HOST\/apps\/libresign\/lib\/Controller\/SignFileController.php","line":207,"function":"sign","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/var\/www\/vhosts\/SERVER-HOST\/SERVER-HOST\/apps\/libresign\/lib\/Controller\/SignFileController.php","line":180,"function":"sign","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/var\/www\/vhosts\/SERVER-HOST\/SERVER-HOST\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":230,"function":"signUsingUuid","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/var\/www\/vhosts\/SERVER-HOST\/SERVER-HOST\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/var\/www\/vhosts\/SERVER-HOST\/SERVER-HOST\/lib\/private\/AppFramework\/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/var\/www\/vhosts\/SERVER-HOST\/SERVER-HOST\/lib\/private\/Route\/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"\/var\/www\/vhosts\/SERVER-HOST\/SERVER-HOST\/lib\/base.php","line":1058,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"\/var\/www\/vhosts\/SERVER-HOST\/SERVER-HOST\/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}]

And in addition:

>Error | libresign | Certificate expired.

Other users can sign well.

**Comment by vitormattos** [comment]
Hi.
This occur when the certificate is expired. I recommend to you to request to this user generate again the certificate redefining the going to LibreSign settings.
https://github.com/JSignPdf/jsignpdf-php/blob/fa302ee5333a8643cf49c60ce33189aa86961350/src/Sign/JSignService.php#L142-L147

By default, the duration of a certificate generated by LibreSign is very big, sounds that this user is using a PFX file generated externally from LibreSign. Verify this first and if possible, return here with this information.

The action to reset password only will work if the certificate was generated by LibreSign because at the moment of reset password will generate a new certificate.

If is an external certificate, this user will need to generate a new pfx file outside of LibreSign and put the new certificate file inside LibreSign folder.

I will maintain this issue open because is necessary to cover this scenario with an user case.

**Comment by Bolli84** [comment]
Thank you. Resetting the password for this user helped!

**Comment by blattms** [comment]
We had a similar problem.
I installed libresign, created a certifcate inside of nexcloud/libresign and signed documents. Only two weeks later all certificates were expired.
Resetting the password did not help. We had to delete the certificates and create new ones.

Libresign: 11.0.6
Nextcloud: 31.0.11

**Comment by vitormattos** [comment]
> Only two weeks later all certificates were expired.

@blattms Thanks for reporting this.
We identified issues related to certificate lifecycle handling in older versions of LibreSign.

The next LibreSign release includes improvements in this area, especially regarding certificate validation and expiration handling.

Before publishing the next release, we need to perform manual validation checks (smoke tests) to ensure everything is working as expected.
If you are willing to help, you can test the current development version either using GitHub Codespaces or on a local test machine. Both approaches are valid, although some setup steps are required.

<details>
<summary>How to test LibreSign using GitHub Codespaces</summary>

### 1. Open the Codespace

* Authenticate to GitHub
* Go to the branch:
  [https://github.com/LibreSign/libresign/tree/chore/reduce-configure-check-time](https://github.com/LibreSign/libresign/tree/chore/reduce-configure-check-time)
* Click the `Code` button and select the `Codespaces` tab
* Click **“Create codespace on feat/customize-signature-stamp”**

### 2. Wait for the environment to start

* A progress bar will appear on the left
* The terminal will show the build process
* Wait until you see the message:

  ```bash
  ✍️ LibreSign is up!
  ```

  This may take a few minutes

### 3. Access LibreSign in the browser

* Open the **Ports** tab (next to the **Terminal**)
* Look for the service running on port **80**
* Click the **globe icon** 🌐 to open it in your browser

### 4. (Optional) Make the service public

* If you want to share the app with people **not logged in to GitHub**:

  * Click the three dots `⋮` on the port 80 row
  * Select `Change visibility` → `Public`

### 5. Login credentials

* **Username**: `admin`
* **Password**: `admin`

You're now ready to test LibreSign.

</details>

If the problem persists after the next release, please let us know by opening a new issue so we can investigate further.

As a side note, if you like the LibreSign project, you can also support its development through recurring funding on our [GitHub Sponsors page](https://github.com/sponsors/LibreSign) or by contacting us for enterprise support. This kind of support is essential to keep the project active and evolving.

**Comment by blattms** [comment]
It seems like the issue is still there Nextcloud 33.0.8, libresign 13.3.0. the signature file was generated August 15, 2026 and I get the error "Certficate expired"

Changing the password does not  help. I still get the same error.

The only thing that helps is deleting the certificate and creating it again
