### ISSUE TITLE
Settings doesn't want save

### ISSUE THREAD

**Issue by Iwios** [LibreSign/libresign#1799]
**Describe the bug**
When I change a setting, for exemple : "Add a footer with sign "(sorry I have the french translate), this settings doesn't want save. If I reload the page, the setting was in the original position

**Expected behavior**
Setting be in the position that I want

**Comment by s0kr8s** [comment]
Encountered the same problem in LibreSign 6.3.1, Nextcloud 25.0.12. 

Did some digging, and I think this is a UI bug. 

App settings appear to be stored in the database table named "oc_appinfo," and when settings are updated, the database table updates rows with the "libresign" in the "appid" column correctly. 

JSON objects returned from calls to endpoints like "/ocs/v2.php/apps/provisioning_api/api/v1/config/apps/libresign/write_qrcode_on_footer" display the correctly updated value as well, but the sliders do not render properly. 

I also think the UI bug is specifically limited to the slider elements.

**Comment by vitormattos** [comment]
I created a newest release of LibreSign. Could you test again?

Closing this issue because was made a lot of improvements at LibreSign.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
