### ISSUE TITLE
LibreSign should allow use of system CFSSL

### ISSUE THREAD

**Issue by madscientist159** [LibreSign/libresign#1818]
**Is your feature request related to a problem? Please describe.**
LibreSign should not be tied only to proprietary, insecure architectures like x86 and ARM.  This requirement stems from LibreSign downloading and using opaque, unauditable CFSSL binaries despite CFSSL being open source.

**Describe the solution you'd like**
LibreSign should scan for compatible CFSSL binaries in the system path instead of downloading its own pre-build version.  Alternatively, LibreSign could build the requisite CFSSL version from source using golang as a system dependency.

**Comment by madscientist159** [comment]
I was able to get LibreSign working on OpenPOWER (ppc64le)by:

- Removing the architecture restriction in the manifest file
- Downloading the CFSSL source from GitHub
- Checking out v1.6.3
- Running make
- Copying the binaries from bin/ to both the system binary path (/usr/bin) as well as LibreSign's application binary directory

If LibreSign can be modified to try to use the system binaries first, the first and last steps will no longer be needed.

**Comment by vitormattos** [comment]
Now is possible to use OpenSSL too.

Could you test the newest release?

Closing this issue because this was solved.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
