### ISSUE TITLE
Fresh Install NextCloud + Libresign

### ISSUE THREAD

**Issue by JEAholding** [LibreSign/libresign#1848]
**Bug**

I am getting error when trying to sign the document, when it ask for signature (after mail is send, and/or click on sign button on Nextcloud if email matches Nextcloud user + ask for user password after click confirm = error). 

`Cannot set non existing property OCA\Libresign\Handler\CfsslHandler->set = array (
0 => 'Name_I_Put_in_CFSSL',
).`

I cannot sign the document. 

All of the binaries seem good....

Status | Message | Resource | Advice
-- | -- | -- | --
success | Java version: openjdk version "17.0.5" 2022-10-18 | java |  
success | Java binary: /var/www/nextcloud/data/appdata_ocf8cexsocrs/libresign/java/jdk-17.0.5+8-jre/bin/java | java |  
success | JSignPdf version: 2.2.0 | jsignpdf |  
success | JSignPdf path: /var/www/nextcloud/data/appdata_ocf8cexsocrs/libresign/jsignpdf-2.2.0/JSignPdf.jar | jsignpdf |  
success | Can generate the preview | imagick |  
success | CFSSL binary path: /var/www/nextcloud/data/appdata_ocf8cexsocrs/libresign/cfssl | cfssl |  
success | CFSSL: Version: 1.6.3, Runtime: go1.18 | cfssl |  
success | Root certificate config files found. | cfssl-configure |  

**Environment  Information: **
Debian Bookworm 12
LibreSign 7.1.1
Nextcloud Hub 27.1.1

**data/nextcloud.log**
`{"reqId":"NkQzR1FsfD1tIlPyDHjX","level":3,"time":"2023-09-28T21:40:05+00:00","remoteAddr":"ACCESS_IP","user":"USER_ID_NEXCLOUD","app":"libresign","method":"POST","url":"/index.php/apps/libresign/api/0.1/account/signature","message":"Cannot set non existing property OCA\\Libresign\\Handler\\CfsslHandler->set = array (\n  0 => 'Name_I_Put_In_CFSSL',\n).","userAgent":"Mozilla/5.0 (X11; FreeBSD amd64; rv:109.0) Gecko/20100101 Firefox/110.0","version":"27.1.1.0","data":{"app":"libresign"}}
{"reqId":"r3Y3OEJ5mB9kmELISY34","level":3,"time":"2023-09-28T21:40:05+00:00","remoteAddr":"ACCESS_IP","user":"USER_ID_NEXCLOUD","app":"libresign","method":"POST","url":"/index.php/apps/libresign/api/0.1/account/signature","message":"Cannot set non existing property OCA\\Libresign\\Handler\\CfsslHandler->set = array (\n  0 => 'Name_I_Put_In_CFSSL',\n).","userAgent":"Mozilla/5.0 (X11; FreeBSD amd64; rv:109.0) Gecko/20100101 Firefox/110.0","version":"27.1.1.0","data":{"app":"libresign"}}
{"reqId":"a3cAwsfMV5pSUZ2ejRpq","level":3,"time":"2023-09-28T22:11:31+00:00","remoteAddr":"ACCESS_IP","user":"USER_ID_NEXCLOUD","app":"libresign","method":"POST","url":"/index.php/apps/libresign/api/0.1/account/signature","message":"Cannot set non existing property OCA\\Libresign\\Handler\\CfsslHandler->set = array (\n  0 => 'Name_I_Put_In_CFSSL',\n).","userAgent":"Mozilla/5.0 (X11; FreeBSD amd64; rv:109.0) Gecko/20100101 Firefox/110.0","version":"27.1.1.0","data":{"app":"libresign"}}
{"reqId":"HcxJydl0ffzFUpLrjLbF","level":3,"time":"2023-09-28T22:16:14+00:00","remoteAddr":"ACCESS_IP","user":"USER_ID_NEXCLOUD","app":"libresign","method":"POST","url":"/index.php/apps/libresign/api/0.1/account/signature","message":"Cannot set non existing property OCA\\Libresign\\Handler\\CfsslHandler->set = array (\n  0 => 'Name_I_Put_In_CFSSL',\n).","userAgent":"Mozilla/5.0 (X11; FreeBSD amd64; rv:109.0) Gecko/20100101 Firefox/110.0","version":"27.1.1.0","data":{"app":"libresign"}}`

Any suggestion I could try to fix ? 

Bug#2: 
I am trying to disable some of the options in admin settings section of libresign like Collect signers metadata but its not saving the changes.

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made a lot of improvements.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
