### ISSUE TITLE
Unify site repositories

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/libresign#1878]
# Problem

Now we have two sites:
| URL | Repository| Description |
|---|---|---|
| https://libresign.github.io/  | https://github.com/LibreSign/libresign.github.io |Documentation of project with how to use the API and OpenAPI yaml fiel|
| https://libresign.coop | https://github.com/LibreSign/site|Institutional site. Downloaded from WordPress.|

We need to unify these repositories.

# Suggestion
- [ ] Implement using static site
- [ ] Add the libresign.github.io as submodule of site repository 
- [ ] Add the content of libresign.github.io at menu of libresign.coop and build the content to work in a subpath
- [ ] Replace, if necessary, this path to be compatible with repository name: https://github.com/LibreSign/libresign/blob/main/Makefile#L69

**Comment by giovannism20** [comment]
Opa @vitormattos o que acha de usarmos o https://sculpin.io/ ? Se achar interessante, tenho interesse em pegar essa issue caso não, seria interessante a sugestão de outros geradores estáticos de site.

**Comment by vitormattos** [comment]
- [ ] Add instructions on how to view collected metadata of a document
- [ ] a brief explanation of what a "certificate engine" is.

**Comment by vitormattos** [comment]
Closing that issue after the documentation was moved to be shipped with LibreSign
