### ISSUE TITLE
Custom validate url

### ISSUE THREAD

**Issue by manuelkamp** [LibreSign/libresign#1918]
So I am using nginx as reverse proxy and have set up a different url for validation to get instead of:
https://cloud.some.domain/apps/libresign/validation/6bccf218-52fd-4955-9efc-8d3c67204854
the much nicer url:
https://validate.some.domain/6bccf218-52fd-4955-9efc-8d3c67204854

I already have added the new subdomain in trusted_domains in nextclouds config.php.

This is partly my nginx config for the new subdomain:
```
	location / {
		proxy_pass http://srv-cloud.domain.local/apps/libresign/validation/;
		proxy_buffering off;
                proxy_http_version 1.1;
		proxy_set_header	Host $host;
		proxy_set_header	X-Real-IP $remote_addr;
		proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header	X-Forwarded-Proto $scheme;
	}
```

the problem with that is, nc redirects to:
https://validate.some.domain/apps/libresign/p/validation/6bccf218-52fd-4955-9efc-8d3c67204854
note the apps/libresign... appearing out of nowhere :) also it has a /p/ in it, where does that come from?

Any ideas how to get that to work?

**Comment by manuelkamp** [comment]
never mind, it worked just because of browser caching - it is not working.

So I am using nginx as reverse proxy and have set up a different url for validation to get instead of:
https://cloud.some.domain/apps/libresign/validation/6bccf218-52fd-4955-9efc-8d3c67204854
the much nicer url:
https://validate.some.domain/6bccf218-52fd-4955-9efc-8d3c67204854

I already have added the new subdomain in trusted_domains in nextclouds config.php.

This is partly my nginx config:
`	location / {
		proxy_pass http://srv-cloud.domain.local/apps/libresign/p/validation/;
		proxy_buffering off;
                proxy_http_version 1.1;
		proxy_set_header	Host $host;
		proxy_set_header	X-Real-IP $remote_addr;
		proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header	X-Forwarded-Proto $scheme;
	}
`

Any ideas how to get that to work?

**Comment by vitormattos** [comment]
Closing because is unrelated to LibreSign. This is a question about Nginx.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
