### ISSUE TITLE
[Suggestion] Nextcloud Collaborative Tags | Libresign Signature Status

### ISSUE THREAD

**Issue by aheider** [LibreSign/libresign#201]
Hi,
this is a suggestion for a feature in future version of LibreSign:
It would be great, if we could define NC collaborative tags that LibreSign attaches in NC to files that have been signed.
Example:
- I need a document signed by 3 people, I need one as author, one as verifier and one as approver
- in LibreSign admin app I make a connection between the sign "text" or "purpose" like author, verifier and approver with the respective NC tags
- when the person designated as author signs the document it gets the tag "authored" or "signed by author" in NC
- this tags should be restricted tags

At the very least there should be a tag stating if a document has been signed any how, so just add the tag "signed with LibreSign".

Just a suggestion :thumbsup:

**Comment by vinicios-gomes** [comment]
Hello @aheider,
Thanks for the suggestion, any feedback for improvement will always be welcome. We will certainly keep your suggestion for improvement in our boards.

On behalf of the entire @LibreSign/developer team, we appreciate your feedback.

PS: we created an account on [Patreon] (https://patreon.com/librecode). It is already possible to use.

We also created a [Bountysource] (https://www.bountysource.com/teams/libresign/issues) account

**Comment by aheider** [comment]
I saw that someone wrote a seperate app to solve this:
[https://github.com/nextcloud/approval](https://github.com/nextcloud/approval)

Excerpt from the readme:
"Admins can define approval workflows: who can request, who can approve/reject. Users can then request approval. Authorized users will be able to approve or reject.
Files can optionally be signed with DocuSign or LibreSign. 
[...]
Workflow definition:
    A workflow title
    A list of users, groups and circles who can request approval
    A list of users, groups and circles who can approve or reject
    A pending tag: the tag meaning approval was requested and elements can be approved or rejected
    An approved tag: the assigned tag when elements get approved
    A rejected tag: the assigned tag when elements get rejected
[...]
There are 3 ways to assign a hidden tag to a file/folder:
    Click the "Request approval" button in Files sidebar
    Admins can see and use hidden tags like classic tags. So they can be manually assigned.
    Via the Files Automated Tagging App"

**Comment by vitormattos** [comment]
Issue closed. We understand that Approval already meets the issue's initial need.
