### ISSUE TITLE
Docker-Compose Issues

### ISSUE THREAD

**Issue by kp3nguinz** [LibreSign/libresign#205]
When following instructions i see an error pop up of `Could not generate certificate.`
in the logs: 
no csr_server.json or config_server.json detected!
I am guessing these need to be created in some form, but if can add instructions I shall try again!

**Comment by vitormattos** [comment]
Review the volumes following the setup instructions, they were not assembled correctly.

**Comment by vinicios-gomes** [comment]
Hi @kp3nguinz,
Since in 18 days there was no further interaction on this issue, we are closing it, if you need help, contact us at @LibreSign/developer  we will help you.
