### ISSUE TITLE
check validity in PDF viewer (eg. Adobe Reader)

### ISSUE THREAD

**Issue by aheider** [LibreSign/libresign#207]
Dear libresign developers,
I fideled a little with JSignPDF on my desktop and arrived at an acceptable situation testing the applied signature in Adobe Reader:
![grafik](https://user-images.githubusercontent.com/6790802/116549883-5536ad80-a8f6-11eb-8067-eb56c9c24810.png)

For this I used JSignPDF from my desktop, but from what I saw this should be possible from CLI also, which is what LibreSign uses:
1. downloaded CFSSL certificate and installed it as trusted root for signing in Adobe Reader (not sure if this can be done also on a Windows Domain Controller and be seen by all devices in the domain)
2. downloaded the libresign generated *.psf file and installed this one into the Windows 10 keystore --> you need to entry your password
3. fired up JSignPDF, select WIndows Key Store, select the libresign generated key, enter your password, select a pdf to sign, set reason and site, for timestamps via time server click "TSA/OCSP/CRL" like this:
![grafik](https://user-images.githubusercontent.com/6790802/116550723-62a06780-a8f7-11eb-8c4e-e42e13331d13.png)
 for hashing I set SHA-512, if you want visual signature select it and settings --> select a picture and place it visually on a page in the PDF file
4. click "sign"
5. in adobe reader follow [https://www.freetsa.org/guide/demonstration-digitally-signed-PDF-documents.html](FreeTSA guidance) to trust freetsa root CA
6. open the signed PDF in Adobe Reader

Most of that should be covered by LibreSign as well and I should allow any user (at least in the same organization) to lookup the signature and timestamp.
This would mean that:
1. JSignPDF parameters are set differently from current settings in LibreSign (including Timestamping Authority)
2. a short guide for installation of certificates on client machines (which files?)

Yours.

**Comment by vitormattos** [comment]
Moved to GitLab:

https://gitlab.com/librecodecoop/libresign/libresign/-/issues/207

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
> - Star ⭐️ this repository
