### ISSUE TITLE
translation of visual signature | special chars

### ISSUE THREAD

**Issue by aheider** [LibreSign/libresign#208]
When signing with current git code, after signing, the PDF has the following text at the bottom of each page:
"Digital unterschrieben mit LibreSign. ÃœberprÃ¼fe in b087d957-bc69-40cf-8d64-1042049bcd04"
while it should be "... überprüfe ..." in the middle.
In Adobe Reader it looks the same.

Probably a problem with localization and an encoding ...

**Comment by vitormattos** [comment]
Hi,

The problem:

https://stackoverflow.com/questions/6334134/fpdf-utf-8-encoding-how-to

The solution was applied in #206

Explain:

To write in the footer for now LibreSign uses the lib FPDF and before the first signature creates a file with the footer.

PS: The signature URL in #206 will be different, it will now contain the UUID of the file.

Also note that in `Settings> Admin> LibreSign` you can now define the validation URL.

In the README that will be updated in #206 there are instructions on the new URL for the validation page.
