### ISSUE TITLE
select PDf to sign | different ways

### ISSUE THREAD

**Issue by aheider** [LibreSign/libresign#209]
I can succseefully sign PDF files that are attached base64-encoded in the POST request sent to the server.
However, I tested signing documents in my NC20 installation:
1. mysite.url/f/123: does not work: {"message":"Client error: `GET https:\/\/mysite.url\/f\/13` resulted in a `401 Unauthorized` response:\n{\"message\":\"Current user is not logged in\"}\n"}
2. mysite.url/s/uuid: does not work: {"message":"Die URL sollte ein PDF sein."}
3. mysite.url/s/uuid/download: does not work: {"message":"Invalid PDF"}
3. a. try another PDF with mysite.url/s/uuid/download: {"message":"Erfolgreich","data":{"uuid":"5d13885f-ce96-4d2d-a64f-2f99c5d7bd84"}}

First PDf was 5.5 MB while second one was 0.7 MB. Latter one worked.

Is there another way to select a PDF from my NC20 installation?

**Comment by vitormattos** [comment]
The last option is the correct. The application needs a PDF URL. The first two options are not a direct URL to a PDF.

A solution for people to request a document signature is being implemented in issue #206 60

We are looking for support to keep the project going and to be able to move faster with development.

https://www.bountysource.com/teams/libresign/issues
https://www.rysolv.com/repos/detail/b9e2ce14-b53c-43df-84b6-632bb2daec7b
https://www.patreon.com/librecode

**Comment by vitormattos** [comment]
Hi @aheider ,
It is now possible to request the signature of a document via Files, API and LibreSign app. It's on the main branch and we'll be releasing a new stable version soon.
The API is documented at: https://libresign.github.io/api/

**Comment by vitormattos** [comment]
Task closed for not having interactions in the last few days
