### ISSUE TITLE
CSP preventing vue-pdf-editor loading

### ISSUE THREAD

**Issue by barrystyle** [LibreSign/libresign#2229]
Unable to add or see existing documents in LibreSign UI, due to excessively strict 'Content-Security-Policy' preventing vue-pdf-editor from loading (seen in stable28).

**Comment by vitormattos** [comment]
I already identified this past week. I will send today a fix at this point. Thanks for your contribution!
Will be very nice receive more feedbacks about the branch stable28. I wish to launch this release as a soon.

**Comment by vitormattos** [comment]
Hi @barrystyle , can you test again?

**Comment by vitormattos** [comment]
I reproduced here and created an issue about this.
