### ISSUE TITLE
LibreSign disappeared from files Tab

### ISSUE THREAD

**Issue by barrystyle** [LibreSign/libresign#2256]
It appears that LibreSign has now disappeared from the files preview tab, possibly as a result of latest commits on stable28?

**Comment by vitormattos** [comment]
Could you provide more details about?

**Comment by barrystyle** [comment]
Sure. At some stage LibreSign has disappeared from the details menu, have attempted mimetype.js/db rebuild, complete removal and reinstall but issue persists.

![image](https://github.com/LibreSign/libresign/assets/14147070/22b43a22-33b0-47a2-b188-34f2b4f844ee)

**Comment by vitormattos** [comment]
I will verify as a soon and go back here with the solution.
Finishing before the opened PR's.

**Comment by vitormattos** [comment]
Hi @barrystyle 
I made tests here and fixed the problem.
Could you test again?
Your contributions testing the new version is helping a lot!
I will maintain opened until you return here with a feedback about if is working or not.

**Comment by barrystyle** [comment]
@vitormattos
Worked first time, functionality as expected.
Is no problem at all!
