### ISSUE TITLE
Unable to test RC5 (all installed from scratch)

### ISSUE THREAD

**Issue by tasagore** [LibreSign/libresign#2398]
Hi

I've tried to test the RC5 version (in fact any 8.0.0 version) and I always had problems so I've started from scratch.

1) Installed latest NC 28.0.3
2) Modify the channel to beta
3) Install LibreSign RC5
4) Configured:
   a) Root Cert
   b) Custom folder from LibreSign to .LibreSign
   c) Installed manually all the requisites, no error and all shows green check
5) Choose a file to be signed
6) The popup asks for signature positions and the web browser (Firefox in this case) freezes:

![image](https://github.com/LibreSign/libresign/assets/54774469/4a0d83c5-ebbd-4f11-b924-51b73a007f55)

**Comment by vitormattos** [comment]
Wow! I never made this step to install the nightly build of an app:

2. Modify the channel to beta

I wil test this when I launch the next RC.

About your problem, could you open the developer tools (Press F12 in your browser) and check if have any error at console tab of Developer Tools?

**Comment by vitormattos** [comment]
This is the password of your signature file (the pfx file).

At this point have an ux problem because I don't implemented a button to reset the password. To change the password of your signature file you will need to go to settings (lower left corner of LibreSign) and change your password. I focused to fix the problems that break the flow. If I implement all improvements at this time, we don't will have a stable version.

**Comment by tasagore** [comment]
> This is the password of your signature file (the pfx file).
> 
> At this point have an ux problem because I don't implemented a button to reset the password. To change the password of your signature file you will need to go to settings (lower left corner of LibreSign) and change your password. I focused to fix the problems that break the flow. If I implement all improvements at this time, we don't will have a stable version.

I've changed the password three times before posting, that's why I'm sure the password is right. There is something more here. Any log to analyze or checks I can do in this side?

**Comment by vitormattos** [comment]
> If you don't change the channel to BETA the RC5 does not appears (at least in my tests).

I every download the .tar.gz file handmade at server to install a nightly build of an app. Next time I will follow your suggestion. :-)

**Comment by vitormattos** [comment]
This is the unique point at the code that throw the error message of your screenshot:

https://github.com/LibreSign/libresign/blob/84b646a0ddea3925049fe34353bb82cd61989f92/lib/Service/IdentifyMethod/SignatureMethod/Password.php#L47-L50

Only by test purpose, you can change this piece of code to that to check if your password is OK. Pay attention that this will put your password at the log file:

```php
openssl_pkcs12_read($pfx, $cert_info, $this->getEntity()->getIdentifierValue());
if (empty($cert_info)) {
	\OC::$server->getLogger()->error('Length of PFX file: '.strlen($pfx));
	\OC::$server->getLogger()->error('Password: '.$this->getEntity()->getIdentifierValue());
	throw new LibresignException($this->identifyMethodService->getL10n()->t('Invalid password'));
}
```

**Comment by tasagore** [comment]
Ok, I've modded the file and this is what is logged, the password showed is "administrador" but that's the username, anyway i've tried with that password and same error:

{"reqId":"g6FgwSQJGvcaEmFQm261","level":3,"time":"2024-02-29T16:16:01+00:00","remoteAddr":"192.168.100.3","user":"administrador","app":"no app in context","method":"POST","url":"/test/ocs/v2.php/apps/libresign/api
/v1/sign/uuid/f3b70775-dd21-48e4-94f8-6225f7c456e1","message":"Length of PFX file: 2588","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/
605.1.15","version":"28.0.3.2","data":[]}
{"reqId":"g6FgwSQJGvcaEmFQm261","level":3,"time":"2024-02-29T16:16:01+00:00","remoteAddr":"192.168.100.3","user":"administrador","app":"no app in context","method":"POST","url":"/test/ocs/v2.php/apps/libresign/api
/v1/sign/uuid/f3b70775-dd21-48e4-94f8-6225f7c456e1","message":"**Password: administrador**","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/6
05.1.15","version":"28.0.3.2","data":[]}

**Comment by vitormattos** [comment]
I identified the problem and will send a PR with the fix

**Comment by vitormattos** [comment]
@tasagore the pr #2404 will close this issue.

I think that will be best because mixed the subject of this issue.

If the problem to add visible elements persists, open a specific issue to this.
