### ISSUE TITLE
Delete a file from the LibreSign app if no signers left 

### ISSUE THREAD

**Issue by tasagore** [LibreSign/libresign#2399]
Hi

Although I can't test the RC5 (described the issue in other post) one thing that could be fine is to have a way to delete a file from the LibreSign app y there is no signers or if I just choose to remove it from there.

Example:

1) I select a file to be signed and it remains in draft mode under the LibreSign app:

![image](https://github.com/LibreSign/libresign/assets/54774469/9b037375-bbbe-42dc-b646-548d9babb863)

2) If I delete the signers the file remains there with the "no signers" label:

![image](https://github.com/LibreSign/libresign/assets/54774469/5a5056e3-fa74-4154-8dc1-f19aad33f8a1)

No way to remove the file from there. I know that there is no real file and it's just a register on the oc_libresign_file table, but should be fine to have any option for cancel/remove the file from there.

**Comment by DazeEnd** [comment]
I agree that it is important to be able to delete files.

**Comment by vitormattos** [comment]
This is a new feature.
I'm focused for now to fix the bugs, but this could be the first feature after the stable release.
I think that we are very close to create the stable release.

**Comment by DazeEnd** [comment]
I just went through the process of documenting this issue, but discovered that my issue would have been a duplicate right before posting. So please consider this another upvote. There should be some way of "canceling" a signature request, whether that is an explicit "Cancel" button or simply removing all signers from a document.

**Comment by Fuseteam** [comment]
where are the files located? perhaps a workaround for now would be to delete it manually?

**Comment by Fuseteam** [comment]
ah now i read this
> No way to remove the file from there. I know that there is no real file and it's just a register on the oc_libresign_file table, but should be fine to have any option for cancel/remove the file from there.

i just gave a thumbs up, we did a few tests with libresign, and now our test documents are just in limbo in the app with no way to cancel the sign request

**Comment by vitormattos** [comment]
We are excited to implement this feature  and believe that implementing after the follow issue would be good:

- https://github.com/LibreSign/libresign/issues/3143

To make this a reality, your support in funding the development of LibreSign could help a lot. If you are able to assist us, you can contribute through GitHub Sponsors. However, if you have other ideas or suggestions of way to support, please don’t hesitate to reach out to us to give more details.

Together, we can make LibreSign an even better tool!

**Comment by vitormattos** [comment]
Inside the PR #3746 to solve the issue #3143 I made the necessary changes to implement the delete file.

Have good points that a extra opinion would be nice to finish the PR #3746 and launch the next release.

If you wish to make tests, we can create a pre-release with LibreSign builded with the PR #3746.

A point that will make me and everyone involved in the development of LibreSign very happy is if  we receive more recurring funding from LibreSign's [GitHub Sponsor](https://github.com/sponsors/LibreSign). This will greatly help to keep the project developing.

If you have any other ideas on how to help the project continue to improve, we would be happy to hear from you: contact@libesign.coop

**Comment by vitormattos** [comment]
![Screenshot_20241105_125131](https://github.com/user-attachments/assets/9dc3c26c-8ecf-4f27-a95f-2ee791374cdd)

**Comment by vitormattos** [comment]
I have added this feature to the new release.

Could you test?

I made a lot of improvements.

Closing this issue as solved.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
