### ISSUE TITLE
File filters do not work properly

### ISSUE THREAD

**Issue by DazeEnd** [LibreSign/libresign#2428]
**Describe the bug**
In LibreSign > Files, there are "All Files", "Pending", and "Signed" buttons that seem intended to filter the view and show only the indicated types of files. These buttons do not work the way I expect.

**To Reproduce**
1. After requesting signatures and receiving signatures on several files, open the LibreSign app, and then click "Files" in the sidebar.

2. Notice at three buttons appear at the top of this "Files" screen: "All Files", "Pending", and "Signed". By default, "All Files" is selected.

3. Click the "Pending" button and examine the files that are displayed.

4. Click the "Signed" button and examine the files that are displayed.

**Expected behavior**
After clicking the "Pending" button in step 3, only files that are in the "available for signature" state should be displayed. After clicking the "Signed" button in step 4, only files that are in the "signed" state should be displayed.

**Actual behavior**
After clicking the "Pending" button in step 3, all files are displayed whether or not they are signed. After clicking the "Signed" button in step 4, only files that that are in the "available for signature" state are displayed.

**Screenshots**
![image](https://github.com/LibreSign/libresign/assets/2699247/52756d19-f984-41f1-85f2-0e8881db5edd)
![image](https://github.com/LibreSign/libresign/assets/2699247/d2a853d5-b511-4cd2-90e8-1fe98de5b646)

**Environment information (please complete the following information):**
 - OS: AlmaLinux 8.9
 - Browser: Chrome
 - LibreSign Version: v8.0.0-rc6
 - Nextcloud Server Version: v28.0.2
 - Logs (get the entries from nextcloud.log related with LibreSign i.e `tail -f data/nextcloud.log|grep libresign`): No messages were printed to nextcloud.log as a result of these steps.

**Additional context**
N/A

**Comment by DazeEnd** [comment]
This does **NOT** appear to be completely fixed in LibreSign v8.0.0-rc7 on Nextcloud 28.0.2. The "All Files" filter and "Pending" filter work correctly, but the "Signed" filter reports that "There are no documents" even though there is a signed document to display. (SELinux is disabled.)

![image](https://github.com/LibreSign/libresign/assets/2699247/acbb8b5d-5bc7-4798-a919-ea55a85e14b0)
![image](https://github.com/LibreSign/libresign/assets/2699247/a8db0764-6bfc-456d-9ab3-227ea9c30efe)
![image](https://github.com/LibreSign/libresign/assets/2699247/5ba2b1d5-3046-49d4-9a8f-0e7feb7d212f)

**Comment by vitormattos** [comment]
Fixed by:

- #2569

**Comment by vitormattos** [comment]
@DazeEnd could you check the prints that I made at PR #2569 ?

### Background
- **Status**: _Draft_.
  Is when we add a signer but don't send the file to be signed.
- **Status**: _No signers_.
  Is when we add a signer and after this, delete the signer.

### Question
Do you think that both status need to be added as "pending" too?

**Comment by DazeEnd** [comment]
@vitormattos I like the way you divided it.

Display in Signed if status = "signed"
Display in Pending if status = "available for signature" or status = "partially signed"
Display everything in All, including status = "draft" and status = "no signers"

I agree with you that if no signature has been requested (as would be the case for status = "draft" and status = "no signers"), then it is not "Pending". "Pending" should be reserved for files that are waiting on action by somebody else.

**Comment by vitormattos** [comment]
Fixed at: https://github.com/LibreSign/libresign/releases/download/v8.0.0-rc9/libresign-v8.0.0-rc9.tar.gz
