### ISSUE TITLE
After signing a document, there should be a way for the user to return to the Nextcloud interface

### ISSUE THREAD

**Issue by DazeEnd** [LibreSign/libresign#2429]
**Is your feature request related to a problem? Please describe.**
After signing a document, the signing user is presented with a screen that reads "Congratulations you have digitally signed a document using LibreSign." After signing a document, a logged in user will probably want to return to Nextcloud, but there is no way to do that from this screen. The only way to get back to Nextcloud is to go to the browser address bar and type in the URL.

**Describe the solution you'd like**
When logged in Nextcloud users sign a document, the signing process should display the standard Nextcloud app bar at the top of the screen so that the user can return to Nextcloud. Here is a mock-up:
![image](https://github.com/LibreSign/libresign/assets/2699247/bc524e99-3dd2-4f79-b310-461bfe45005c)
![image](https://github.com/LibreSign/libresign/assets/2699247/f19ef2b8-2bc0-4e1e-b9e2-22244800eb60)

**Describe alternatives you've considered**
If the Nextcloud app bar cannot be placed at the top of the screen, then there should at least be a "Home" button placed next to the "See Document Validation" button. When the "Home" button is clicked, the user should be returned to the standard Nextcloud user interface. Here is a mock-up:
![image](https://github.com/LibreSign/libresign/assets/2699247/b63a9460-4a1b-4e2e-a1cf-1c890e3384e8)

**Additional context**
A signer who is not logged in should not be given the option to return to Nextcloud, because that signer would have no access to Nextcloud.

**Comment by vitormattos** [comment]
I wish to open at Viewer app when the user is authenticated. Like when open a picture or a markdown document.

**Comment by vitormattos** [comment]
I will maintain this issue opened because I disliked the solution that I made. I implemented iframe and only work when click at sign button.

## to-do
- [ ] remove iframe
- [ ] Every when the signer is authenticated, open in the same tab as modal
- [ ] When isn't an authenticated signer, will open as external site (without Nextcloud menu).

**Comment by vitormattos** [comment]
Good idea, then I will move to a new issue.

**Comment by vitormattos** [comment]
solved
