### ISSUE TITLE
Only first signer can sign document

### ISSUE THREAD

**Issue by DazeEnd** [LibreSign/libresign#2431]
**Describe the bug**
When a signature is requested by more than one person, only one person can sign the document. The other user cannot sign the document.

**To Reproduce**
1. Log into Nextcloud as the admin user.

2. Go to Settings > Administration > LibreSign. Under the "Identity factors" heading, make sure that both "Account" and "Email" are turned ON, and that "Click to sign" is selected for both. UNCHECK the "Request to create account" option.
![image](https://github.com/LibreSign/libresign/assets/2699247/8eacc7e2-feb0-45ce-a4ad-53a683bba9f8)

3. In LibreOffice, request a signature from two different signers: Signer1 has a Nextcloud account. Signer2 does not have a Nextcloud account. 
![image](https://github.com/LibreSign/libresign/assets/2699247/92588bb7-f562-43bf-9cc3-5fbc2f145a19)

4. Log out of Nextcloud.

5. Open the email for Signer2 and click on the button that appears at the bottom of LibreSign signature request email that the user received. This will open LibreSign in a browser window.

6. Define your signature (by drawing a signature) and save it.

7. Click the "Sign the document" button and confirm your signature.

8. Log into Nextcloud as Signer1, and open the LibreSign app.

9. Click on "Files" in the sidebar and click on the file that the user was requested to sign. This will open up a "Multiple Signers" sidebar on the right side of the screen.

10. Examine the "Multiple Signers" sidebar that was opened in step 9.

**Expected behavior**
In step 10, the logged in user should see a "Sign" button that will begin the signing process when it is clicked.

**Actual behavior**
Only a "Validate" button is displayed. There is no "Sign" button. There does not appear to be any way for for the logged in user to sign the document.
![image](https://github.com/LibreSign/libresign/assets/2699247/719e989f-bb2a-4666-9d4d-2cdaa8b1ffb3)

**Screenshots**
See above.

**Environment information (please complete the following information):**
 - OS: AlmaLinux 8.9
 - Browser: Chrome
 - LibreSign Version: v8.0.0-rc6
 - Nextcloud Server Version: v28.0.2
 - Logs (get the entries from nextcloud.log related with LibreSign i.e `tail -f data/nextcloud.log|grep libresign`): No messages are printed to nextcloud.log when performing these steps.

**Additional context**
N/A

**Comment by vitormattos** [comment]
@DazeEnd what you think about this?

![Screenshot_20240306_082150](https://github.com/LibreSign/libresign/assets/1079143/a4b23771-2ebe-4dad-aa8e-0b99b951e921)

**Comment by DazeEnd** [comment]
@vitormattos I'm not exactly sure what I am looking at there. Is that the view that the second signer will see? Or were you not able to reproduce my bug report?

What would the "Next" button do in the screenshot you provided?

**Comment by vitormattos** [comment]
At my screenshot, the user admin is the requester and also the signer, because this can see the next button.

Thinking best, this will generate other complex scenarios to-do. I will block to change the position of signatures after the first person sign the document.

**Comment by vitormattos** [comment]
I made a change at PR to don't show the next button after the first person sign the document.

I will create a fallback task to block changes from API side after the first person sign the document.

**Comment by DazeEnd** [comment]
This issue is fixed for me in LibreSign v8.0.0-rc7 running on Nextcloud v28.0.2.

**Comment by HeteMacmania** [comment]
That is strange because i'm using NC 30. and LibreSign 11. and i got the same issue but with 2 guests signing

**Comment by vitormattos** [comment]
@HeteMacmania this issue already was closed.
If you have a similar scenario but consider that is similar to this issue, open a new issue detailing your scenario with all steps that is necessary to reproduce, adding logs if exists, and following the requirements.
