### ISSUE TITLE
After clone this object, open it use the 'npm run server' command, but localhost page show 'Cannot GET /'

### ISSUE THREAD

**Issue by WeldonLei** [LibreSign/libresign#2516]
npm run serve

......
Building libresign 9.0.0 

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:3000/
<i> [webpack-dev-server] On Your Network (IPv4): http://***.***.***.***:3000/
<i> [webpack-dev-server] On Your Network (IPv6): http://*****************:3000/
<i> [webpack-dev-server] Content not from webpack is served from 'E:\workplace\libresign\public' directory
......

Is it to run the php file?  How to run it?

**Comment by vitormattos** [comment]
Closing this issue due to lack of interaction after 1 week and because it's actually not an issue.
