### ISSUE TITLE
Inform requestor after file is signed

### ISSUE THREAD

**Issue by Bolli84** [LibreSign/libresign#2531]
After I sent out a file for signing, i would like to be informed, if the file has been signed fully.

So, I want to get a mail after it has been finished.

**Comment by vitormattos** [comment]
Good idea!

We have two ways to provide this:

1. Wait by this be a priority to LibreSign Team 
2. Help funding the project to be possible to us to pay an engineer to do this.

**Comment by vitormattos** [comment]
Issue replaced by
- #2618

The issue #2618 have a solution suggestion.
