### ISSUE TITLE
Running Libresign in Containers

### ISSUE THREAD

**Issue by tendaworld** [LibreSign/libresign#268]
Hi Vitto and Team,

I have succesfully replicated the setup steps for docker and now have containerised Nextcloud PHP image updated with Java and Jsign and a standalone externally running CFSSL server.

Kindly assist with a simple instruction on how to get the libresign app running in the nextcloud container....this bit is missing in the instructions and so its unclear what next after installation of the Nextcloud PHP, Java, Jsign and CFSSL containers how to access the libresign in the nextcloud apps. Thanks in advance.

Stay Safe

**Comment by cohabo** [comment]
The Libresign is downloadable from the app store section within the installed app. Perhaps you can give it a few minutes to update the app collection it is searchable and downloadable.

**Comment by vitormattos** [comment]
And, after installing the app, go to Nextcloud settings, then to the LibreSign section to configure the root certificate.

**Comment by cohabo** [comment]
Hi Vitor,

I am replicating the steps with docker-compose, and  now in Next Clouds => Settings => Password Creation => I get error message: Error creating new password, please contact the administrator. Is this Libresign related or Nextcloud, anyhow i can debug this, FWIW logs don't show any captures from this failure event.
Thanks

**Comment by vitormattos** [comment]
Task closed for not having interactions in the last few days
