### ISSUE TITLE
Disable prompt for password, when setting up a signing password

### ISSUE THREAD

**Issue by jayfk** [LibreSign/libresign#286]
We are using nextcloud with oAuth 2 Logins via the Social Login app. Our users don't have a password associated to their account.

Is there a way to disable the password prompt when setting up a new signing password?

<img width="844" alt="Screenshot 2021-06-18 at 13 52 12" src="https://user-images.githubusercontent.com/2930472/122557205-c401ce80-d03c-11eb-9e93-0e90872008cc.png">

**Comment by vitormattos** [comment]
Hi @jayfk ,
It is necessary to analyze this specific case. In this scenario how does Nextcloud do for admins who do some action that requires password usage like installing an app?

**Comment by jayfk** [comment]
It doesn't ask for a password. This could, however, be a Social Login specific thing since there's a "Disable password confirmation on settings change" checkbox.

Is the elevated password prompt something that is triggered by nextcloud or by LibreSign?
