### ISSUE TITLE
Can't request signature from existing users

### ISSUE THREAD

**Issue by bigbeka** [LibreSign/libresign#2883]
**Describe the bug**
If the user exists in the NC, adding the existing user's username/email address in "Search signer" returns 0 results, unless it is my own email address.

I tried to "Search signer" from file details sidebar and from the LibreSign > Request page, it returns 0 results.

**Comment by vitormattos** [comment]
Check at Administration Settings if is enabled to identify the signer using account.

![Screenshot_20240424_110624](https://github.com/LibreSign/libresign/assets/1079143/f5efd6bc-7264-4b73-bf24-6af864ddf99f)

**Comment by bigbeka** [comment]
Yes, that seems to be the logic solves the problem!

> Check at Administration Settings if is enabled to identify the signer using account. If account is disabled, the search don't will return accounts.

**Comment by bigbeka** [comment]
Yes please, although I have not tested all edge cases with various settings. I tested to the extent that I could see our organisation using it.
