### ISSUE TITLE
Allow LibreSign to use Nextcloud Viewer app to visualize PDF files

### ISSUE THREAD

**Issue by bigbeka** [LibreSign/libresign#2885]
**Describe the bug**
When "View" is clicked on Verification page, the PDF preview is 1/50th size of the whole window on Safari. PDF preview should expand to full width of the safari window. Chrome expands the PDF preview to full width correctly.

<img width="2879" alt="Screenshot 2024-04-24 at 19 47 21" src="https://github.com/LibreSign/libresign/assets/53529055/edf20dde-4e21-449c-800a-a0c1edae3583">

**Comment by vitormattos** [comment]
This is not about LibreSign. This is the PDF visualizer of your browser.

**Comment by bigbeka** [comment]
But other PDFs in Safari's preview open up full width. Maybe allow LibreSign to use NC's native PDF viewer?

Below screenshot is when I open a PDF from the list of Files in Safari, NC opens in natively.

But when I click on "Validation > View", the PDF opens up in a separate tab with Safari's PDF preview.

<img width="2072" alt="Screenshot 2024-04-24 at 20 06 10" src="https://github.com/LibreSign/libresign/assets/53529055/36e21a00-719f-4dcc-ab04-4dec78cd82bc">

**Comment by vitormattos** [comment]
The PDF viewer of Nextcloud don't use the native viewer.

> allow LibreSign to use NC's native PDF viewer?

This could be a good idea. Maybe we can change the subject of this issue to `allow LibreSign to use NC's native PDF viewer`

**Comment by bigbeka** [comment]
Perfect, enabling Nextcloud's native viewers app will resolve the compatibility issue. Changes the subject to your proposed one.
