### ISSUE TITLE
Signature areas are overlapping in Safari

### ISSUE THREAD

**Issue by bigbeka** [LibreSign/libresign#2887]
**Describe the bug**
When Signer opens the link to sign a document in Safari, where there are 2 or more signers, the two signature areas are overlapping.

Below screenshot shows the view from both signers:
<img width="2714" alt="Screenshot 2024-04-24 at 17 09 21" src="https://github.com/LibreSign/libresign/assets/53529055/beae4cfe-1be2-42f8-84cf-0e86e5627eb0">

This is how it looks from Chrome:
<img width="1083" alt="Screenshot 2024-04-24 at 17 18 25" src="https://github.com/LibreSign/libresign/assets/53529055/affd5903-1622-4547-a082-428fc1a910a5">

Although, when both signers sign, the end results still comes out correctly:
<img width="803" alt="Screenshot 2024-04-24 at 17 10 22" src="https://github.com/LibreSign/libresign/assets/53529055/acbb5d01-e4ee-4304-b142-d3b48112285b">

**Comment by vitormattos** [comment]
I think that this was fixed by this PR:
- 
Could you test at your environment after next release and return here to talk if was solved to be possible close this issue?

**Comment by bigbeka** [comment]
I have update from 9.0.0 to 9.0.1 now.

I confirm, this bug has been resolved. Thank you very much!
