### ISSUE TITLE
Can only place signature positions on first page

### ISSUE THREAD

**Issue by metheos** [LibreSign/libresign#2903]
When defining signature positions, the signature box seems to disappear behind the next page when dragged.

**To Reproduce**
Add a signer and click next to get the modal for setting signature positions.
Click a signer to define their signature position.
Attempt to drag the signature position box beyond the first page.
See that the signature position box is no longer visible on the second page.

**Expected behavior**
The signature position box should be able to be placed on any page of a document.

**Screenshots**
![2024-04-25 12_04_20-LibreSign - Cloud](https://github.com/LibreSign/libresign/assets/4603749/2df0f0bd-0f2a-4d61-8e4d-0c93110e91fd)

**Environment information (please complete the following information):**
Ubuntu 22.04.4 LTS
Chrome 124.0.6367.78
LibreSign 8.0.0
Nextcloud 28.0.4
Nothing logged

**Comment by metheos** [comment]
I see. That makes a lot of sense actually. Maybe we should add a note to the modal that explains this, as it was not obvious.

Change ```Select each signer to define their signature positions```
to
```Click the page to sign, then select a signer to set their signature position```

Or something along those lines.

**Comment by vitormattos** [comment]
> Maybe we should add a note to the modal that explains this, as it was not obvious.

This is a good workaround to give a best help.

Will be necessary only to change the follow row and send a PR with the text change to be possible make available this change at next release:

https://github.com/LibreSign/libresign/blob/278120f05cab2568a8d747e339b997da73780938/src/Components/Request/VisibleElements.vue#L17

**Comment by metheos** [comment]
I've submitted PR 2915 to accomplish this
