### ISSUE TITLE
JSignPdf 1.6.5 supported, too?

### ISSUE THREAD

**Issue by szaimen** [LibreSign/libresign#293]
Hi there, 
I wonder if [JSignPdf 1.6.5](https://sourceforge.net/projects/jsignpdf/files/stable/JSignPdf%201.6.5/) is supported, too?

Thanks for your feedback!

Cheers!

**Comment by vitormattos** [comment]
Hello @szaimen,

We currently implement an app configuration to enable changing the JSignPDF path. There is no visual interface to make this modification but it can be done directly in the `appconfig` table.

https://github.com/LibreSign/libresign/blob/main/lib/Handler/JSignPdfHandler.php#L4
