### ISSUE TITLE
Internal error when sign usign password with UTF8 chars

### ISSUE THREAD

**Issue by DaianeAlvesRJ** [LibreSign/libresign#2969]
**To Reproduce**
- I'm an authenticated user and
- Request to sign a .pdf file
- Go to Sign the document
- Click at "Sign the document"
- See the modal with title "Confirm your signature"
- And fill the subscription password with `úy>'\u:Ö}P%5`
- See internal error. Contact admin

**Screenshots**
![Screenshot_20240507_183940](https://github.com/LibreSign/libresign/assets/26097287/8ae27538-78a0-4bbb-a118-0dda40f40791)

**Environment information (please complete the following information):**
 - Identification factors: account -> certificate with password
 - Email: disabled

**Comment by vitormattos** [comment]
Already was solved. Thanks!
