### ISSUE TITLE
About custom footer and its settings

### ISSUE THREAD

**Issue by tasagore** [LibreSign/libresign#3016]
Hi

Custom footer is a new feature that can be surprisedly useful but:

_To customize the template you will need to change the LibreSign app setting footer_template by twig code of your custom template._

I guess that setting is not in the frontend interface so it must be changed in the backend (using occ command), is it right or I'm missing something?

Regards

**Comment by vitormattos** [comment]
I didn't made the change to make this accessible at administration settings because this is an experimental feature.

You can enable the frontend interface to change this setting 1 to `extra_settings`  using occ command:

```
occ app:config:set extra_settings --value=1
```
