### ISSUE TITLE
Document not visible when singing from iOS

### ISSUE THREAD

**Issue by tasagore** [LibreSign/libresign#3017]
Hi

NC29+Libresign 9.0.1

1) Request a signature,
2) Click the email link in an iPhone
3) Safari shows then Nextcloud login page
4) Enter credentials
5) A webpage appears with the document name at the top, a text "available for signature" and a button with "Sign the document." but the PDF is not visible.

The PDF should be visible in that point.

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made a lot of improvements.

I haven't an iOS to reproduce but I made changes at this point that could affect this scenario. Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
