### ISSUE TITLE
Cannot set non existing property OCA\\Libresign\\Handler\\CertificateEngine\\CfsslHandler

### ISSUE THREAD

**Issue by nlublovary** [LibreSign/libresign#3040]
**Describe the bug**
Installed vanilla LibreSign App version 9.0.1 on Nextcloud 29.0.0, when clicking Files or Settings > LibreSign I receive a error:

`Cannot set non existing property OCA\\Libresign\\Handler\\CertificateEngine\\CfsslHandler->set = array (\n  0 => 'mydomain.com',\n).`

LibreSign App renders Nextcloud unusable and therefore I have no other choice but disable LibreSign for now.

**To Reproduce**
- Authenticated as Nextcloud Admin
- Install and Enable LibreSign App
- Go to Files
- See error

**Expected behavior**
Able to use Files and access LibreSign settings without error.

**Screenshots**

**Environment information (please complete the following information):**
 - OS: Debian 12
 - Browser: Firefox
 - LibreSign Version: 9.0.1
 - Nextcloud Server Version: 29.0.0
 - Nextcloud itself runs on http port 80 but behind NGINX proxy that manages https and SSL
 - Logs:

`{
  "reqId": "9aR9jto5kFb35a2rwQ2e",
  "level": 3,
  "time": "May 20, 2024 11:10:06",
  "remoteAddr": "xxx.172.176.214",
  "user": "Administrator",
  "app": "index",
  "method": "GET",
  "url": "/apps/files/",
  "message": "Cannot set non existing property OCA\\Libresign\\Handler\\CertificateEngine\\CfsslHandler->set = array (\n  0 => 'mydomain.com',\n).",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0",
  "version": "29.0.0.19",
  "exception": {
    "Exception": "LogicException",
    "Message": "Cannot set non existing property OCA\\Libresign\\Handler\\CertificateEngine\\CfsslHandler->set = array (\n  0 => 'mydomain.com',\n).",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/cloud/apps/libresign/lib/Handler/CertificateEngine/AEngineHandler.php",
        "line": 217,
        "function": "__call",
        "class": "OCA\\Libresign\\Handler\\CertificateEngine\\AEngineHandler",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/apps/libresign/lib/Handler/CertificateEngine/Handler.php",
        "line": 55,
        "function": "populateInstance",
        "class": "OCA\\Libresign\\Handler\\CertificateEngine\\AEngineHandler",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/apps/libresign/lib/Files/TemplateLoader.php",
        "line": 62,
        "function": "getEngine",
        "class": "OCA\\Libresign\\Handler\\CertificateEngine\\Handler",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/lib/private/EventDispatcher/ServiceEventListener.php",
        "line": 86,
        "function": "handle",
        "class": "OCA\\Libresign\\Files\\TemplateLoader",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 230,
        "function": "__invoke",
        "class": "OC\\EventDispatcher\\ServiceEventListener",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 59,
        "function": "callListeners",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 86,
        "function": "dispatch",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 98,
        "function": "dispatch",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/apps/files/lib/Controller/ViewController.php",
        "line": 263,
        "function": "dispatchTyped",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 232,
        "function": "index",
        "class": "OCA\\Files\\Controller\\ViewController",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 138,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/lib/private/AppFramework/App.php",
        "line": 184,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/lib/private/Route/Router.php",
        "line": 338,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/var/www/cloud/lib/base.php",
        "line": 1050,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/index.php",
        "line": 49,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/var/www/cloud/apps/libresign/lib/Helper/MagicGetterSetterTrait.php",
    "Line": 30,
    "message": "Cannot set non existing property OCA\\Libresign\\Handler\\CertificateEngine\\CfsslHandler->set = array (\n  0 => 'mydomain.com',\n).",
    "exception": {},
    "CustomMessage": "Cannot set non existing property OCA\\Libresign\\Handler\\CertificateEngine\\CfsslHandler->set = array (\n  0 => 'mydomain.com',\n)."
  }
}`

**Additional context**
LibreSign works fine on my other server running Nextcloud 28, so this seems to be an issue related only to Nextcloud 29 perhaps, or related to Nextcloud running on HTTP behind an Nginx proxy with HTTPS, not certain.

**Comment by vitormattos** [comment]
Thanks! I will check as a soon.

**Comment by vitormattos** [comment]
This fix will come in the next release.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
