### ISSUE TITLE
404 invalid user - for links sent to users without an account

### ISSUE THREAD

**Issue by mantis64** [LibreSign/libresign#3066]
**Describe the bug**
Users click on link to sign document and they are faced with 404 page with invalid user

**To Reproduce**
Unless I choose 'Account' as identification all links sent result in a 404

**Expected behavior**
A link to the document to sign rather than a 404 with invalid user

**Environment information (please complete the following information):**
 - OS: [e.g. Linux Debian, Docker]
 - Browser Chrome & Firefox
 - LibreSign Version 9.0.2
 - Nextcloud Server Version 29.0.0
 - Logs (get the entries from nextcloud.log related with LibreSign i.e `tail -f data/nextcloud.log|grep libresign`)

**Comment by vitormattos** [comment]
This is not a bug, the message is right.

If you are authenticated with account of signer A and send a request to sign to signer B and at the same browser access the link that signer B received by email, will be displayed that the signer is invalid.

To access the link that user B received, you will need to do one of the follow ways:
- Logout of account of signer A.
- Open an anonymous tab of your browser.
- Use other browser. If you are using Chrome, you can open Firefox by example.
- Use other device to access the link.

Maybe a best exposition to signer A about what's happened would be good. I'm open for suggestions.

**Comment by EnriqueSK9** [comment]
Boa tarde

Este problema está causando confusão em alguns dos nossos clientes. Basicamente eles ficam mandando solicitações de assinatura usando a opção "Email" ao invés de "Conta", e sempre que eles fazem isso dá esse erro e eles ficam confusos.

Eu sugiro uma mudança na interface.
Básicamente ao invés do usuário escolher entre conta e email, tem apenas um input, e o libresign detecta se foi colocado um email interno ou externo. E trata a solicitação como "conta" se o email for interno, e como "email" se for externo.

Aí claro, teria que fazer todos os ajustes. Tipo:
- Barrar o usuário de por email interno/externo dependendo de qual é a configuração do aplicativo.
- Talvez mostrar uma mensagem avisando que o usuário está enviando solicição para um email externo(para situações onde o usuário digita errado o email do coleguinha).

Na minha opinião isso ajudaria a evitar confusão na mão de usuários mais leigos
