### ISSUE TITLE
White page on opening signing document

### ISSUE THREAD

**Issue by RaulGRD** [LibreSign/libresign#3067]
**Describe the bug**
When requesting a signature, the client receives a link that does not open (a white page opens). Neither from email nor from the nextcloud libresign client account
**To Reproduce**
- I'm an authenticated user
- Go to 'Libresign, request sign,send request to someone then the user receives the mail/notification but it's opening in new blank window'

![nextcloud 1](https://github.com/LibreSign/libresign/assets/19626537/db642604-ecbf-41d7-83e6-cbe2fe29caa3)

**Environment information (please complete the following information):**
 - OS: Ubuntu 24.04
 - LibreSign Version 9.02
 - Nextcloud Server Version 29.0.1 (I also tried in 29.0.0)
 - PHP 8.3
 - Logs (get the entries from nextcloud.log related with LibreSign i.e `tail -f data/nextcloud.log|grep libresign`)
 - 
{"reqId":"DlzS2aD0ggRyq0RO9v8M","level":3,"time":"2024-05-4T13:48:23+03:00","remoteAddr":"xxxxxxxxxxx","user":"xxxxx","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Undefined array key \"d\" at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#535","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Edg/125.0.0.0","version":"29.0.1.1","data":{"app":"PHP"}}
{"reqId":"DlzS2aD0ggRyq0RO9v8M","level":3,"time":"2024-05-24T13:48:23+03:00","remoteAddr":"xxxxxxxxxxx","user":"xxxxx","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Trying to access array offset on null at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#535","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Sa
fari/537.36 Edg/125.0.0.0","version":"29.0.1.1","data":{"app":"PHP"}}
{"reqId":"DlzS2aD0ggRyq0RO9v8M","level":3,"time":"2024-05-24T13:48:23+03:00","remoteAddr":"xxxxxxxxx","user":"xxxxx","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Trying to access array offset on null at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#539","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Sa
fari/537.36 Edg/125.0.0.0","version":"29.0.1.1","data":{"app":"PHP"}}
{"reqId":"XFmuoSDdN4KYKyD1Zwfd","level":3,"time":"2024-05-24T13:48:39+03:00","remoteAddr":"xxxxxxxxxxxxxxxx","user":"xxxxxx","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Undefined array key \"d\" at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#535","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Edg/125.0.0.0","version":"29.0.1.1","data":{"app":"PHP"}}
{"reqId":"XFmuoSDdN4KYKyD1Zwfd","level":3,"time":"2024-05-24T13:48:39+03:00","remoteAddr":"xxxxxxxxx","user":"xxxx","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Trying to access array offset on null at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#535","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Sa
fari/537.36 Edg/125.0.0.0","version":"29.0.1.1","data":{"app":"PHP"}}
{"reqId":"XFmuoSDdN4KYKyD1Zwfd","level":3,"time":"2024-05-24T13:48:39+03:00","remoteAddr":"xxxxxxxxxxx","user":"xxxxxxx","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Trying to access array offset on null at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#539","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Sa
fari/537.36 Edg/125.0.0.0","version":"29.0.1.1","data":{"app":"PHP"}}
{"reqId":"zkjidXkFZXDUCm7J6V6L","level":3,"time":"2024-05-24T13:48:44+03:00","remoteAddr":"xxxxxxxxxxxxxxxx","user":"xxxxxx","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Undefined array key \"d\" at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#535","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Edg/125.0.0.0","version":"29.0.1.1","data":{"app":"PHP"}}
{"reqId":"zkjidXkFZXDUCm7J6V6L","level":3,"time":"2024-05-24T13:48:44+03:00","remoteAddr":"xxxxxxxxxxxxx","user":"xxxxxx","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Trying to access array offset on null at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#535","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Sa
fari/537.36 Edg/125.0.0.0","version":"29.0.1.1","data":{"app":"PHP"}}
{"reqId":"zkjidXkFZXDUCm7J6V6L","level":3,"time":"2024-05-24T13:48:44+03:00","remoteAddr":"xxxxxxxxxxxxxxx","user":"xxxxxx","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Trying to access array offset on null at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#539","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Sa
fari/537.36 Edg/125.0.0.0","version":"29.0.1.1","data":{"app":"PHP"}}

**Comment by vitormattos** [comment]
Could you do a query in your table `libresign_file` ?

Sounds that the field metadata haven't the key 'd', is the key that store the file dimensions to be possible determine the position of visible elements. You will need to check the column `metadata` if have a json like the follow:

```json
{"d": [{"h": 841.889763779528, "w": 595.275590551181}], "p": 1}
```

At this example, is the metadata of a PDF file that have only a page with a dimension (h: height, w: width). When have more than a page, the dimension array will have more than a dimension object, one for each page.

We need to check what happened to you don't have the dimension to this document.

**Comment by RaulGRD** [comment]
How to do that query?

**Comment by RaulGRD** [comment]
> Could you do a query in your table `libresign_file` ?
> 
> Sounds that the field metadata haven't the key 'd', is the key that store the file dimensions to be possible determine the position of visible elements. You will need to check the column `metadata` if have a json like the follow:
> 
> ```json
> {"d": [{"h": 841.889763779528, "w": 595.275590551181}], "p": 1}
> ```
> 
> At this example, is the metadata of a PDF file that have only a page with a dimension (h: height, w: width). When have more than a page, the dimension array will have more than a dimension object, one for each page.
> 
> We need to check what happened to you don't have the dimension to this document.

![nextcloud_88](https://github.com/LibreSign/libresign/assets/19626537/3ae6ff63-3263-4469-b1ff-e4dbe656af11)


I don't know how to display the content of the table

**Comment by RaulGRD** [comment]
![nextcloud_89](https://github.com/LibreSign/libresign/assets/19626537/8aa066fa-1ee6-4fce-8f77-63f874af9f1c)

**Comment by vitormattos** [comment]
```sql
SELECT id, node_id, name, metadata FROM oc_libresign_file;
```

**Comment by RaulGRD** [comment]
> Could be this query:
> 
> ```sql
> SELECT id, node_id, name, metadata FROM oc_libresign_file;
> ```

![Screenshot_88](https://github.com/LibreSign/libresign/assets/19626537/cb8d781e-4558-4238-b709-43a4835966b9)

**Comment by RaulGRD** [comment]
I have deleted the file. Now another error it's showing


{"reqId":"MMr4X0nRJiFMN9uef81N","level":3,"time":"2024-05-27T16:56:07+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Undefined a
rray key \"d\" at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#535","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36","version":
"29.0.1.1","data":{"app":"PHP"}}
{"reqId":"MMr4X0nRJiFMN9uef81N","level":3,"time":"2024-05-27T16:56:07+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Trying to a
ccess array offset on null at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#535","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
","version":"29.0.1.1","data":{"app":"PHP"}}
{"reqId":"MMr4X0nRJiFMN9uef81N","level":3,"time":"2024-05-27T16:56:07+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Trying to a
ccess array offset on null at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#539","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
","version":"29.0.1.1","data":{"app":"PHP"}}
{"reqId":"Eiulc4boipWyGPvAaPQn","level":3,"time":"2024-05-27T16:57:00+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Undefined a
rray key \"d\" at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#535","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36","version":
"29.0.1.1","data":{"app":"PHP"}}
{"reqId":"Eiulc4boipWyGPvAaPQn","level":3,"time":"2024-05-27T16:57:00+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Trying to a
ccess array offset on null at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#535","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
","version":"29.0.1.1","data":{"app":"PHP"}}
{"reqId":"Eiulc4boipWyGPvAaPQn","level":3,"time":"2024-05-27T16:57:00+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Trying to a
ccess array offset on null at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#539","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
","version":"29.0.1.1","data":{"app":"PHP"}}

**Comment by RaulGRD** [comment]
when i want to upload a file from nextcloud files it doesen't show the files.
![Screenshot_89](https://github.com/LibreSign/libresign/assets/19626537/2256989a-145e-4912-b76b-30b0a0e4710d)

**Comment by vitormattos** [comment]
Did you removed the buttons of your Nextcloud?
I can't see the menu in your print and this is a bit strange.

**Comment by vitormattos** [comment]
> Undefined array key "d"

Sounds that is the same problem of first error.

How you deleted the file?

**Comment by RaulGRD** [comment]
same white page
![Screenshot_90](https://github.com/LibreSign/libresign/assets/19626537/6454dfae-1669-4bba-a72c-b9e26987bb15)

**Comment by RaulGRD** [comment]
Undefined array key "d" was the old error. the new error is this one
![Screenshot_91](https://github.com/LibreSign/libresign/assets/19626537/8c7e9ea7-b4c1-4fd7-a655-01ed63d7a898)

**Comment by RaulGRD** [comment]
{"reqId":"Eiulc4boipWyGPvAaPQn","level":3,"time":"2024-05-27T16:57:00+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/file/list","message":"Trying to a
ccess array offset on null at /var/www/nextcloud/apps/libresign/lib/Service/FileService.php#539","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
","version":"29.0.1.1","data":{"app":"PHP"}}

**Comment by vitormattos** [comment]
Looking the code and your return of database, sounds that this problem is an old problem. Does your installation come from an old LibreSign setup? The file with ID 1 have null values at metadata and is this your problem now.

Because this is an old problem and is dirty data in your database, you can choose by one of these options to fix this problem:
- Delete the file `Nextcloud Manual.pdf` at app Files. This will trigger a listener of LibreSign to delete all data of this file from LibreSign tables.
- Delete this data handmade from database 
  ```sql
  DELETE FROM oc_libresign_file WHERE id = 1;
  DELETE FROM oc_libresign_sign_request WHERE file_id = 1;
  DELETE FROM oc_libresign_sign_request WHERE file_id = 1;
  DELETE FROM oc_libresign_identify_method WHERE sign_request_id not IN ( SELECT id FROM oc_libresign_sign_request);
  ```
- Reset all settings of LibreSign:

  ```bash
  occ config:system:set debug --value false --type boolean
  occ libresign:developer:reset --all
  occ config:system:set debug --value true --type boolean
  ```

**Comment by RaulGRD** [comment]
Should i make all 3 steps or just one?

**Comment by RaulGRD** [comment]
root@nextcloudsrv:/var/www/nextcloud# sudo -u www-data php occ libresign:developer:reset --all


  There are no commands defined in the "libresign:developer" namespace.

  Did you mean one of these?
      libresign
      libresign:configure

**Comment by vitormattos** [comment]
> Should i make all 3 steps or just one?

Just one. Choose what you think that will be best. If only have test files, i recommend to use the 3th option.

**Comment by vitormattos** [comment]
> There are no commands defined in the "libresign:developer" namespace.

To 3th option, you will need to run the commands in the exposed order. The developer commands of LibreSign only works if your Nextcloud is with debug mode enabled.

**Comment by RaulGRD** [comment]
root@nextcloudsrv:/var/www/nextcloud# sudo -u www-data php occ config:system:set debug --value false --type boolean
System config value debug set to boolean false
root@nextcloudsrv:/var/www/nextcloud# sudo -u www-data php occ libresign:developer:reset --all


  There are no commands defined in the "libresign:developer" namespace.

  Did you mean one of these?
      libresign
      libresign:configure

**Comment by RaulGRD** [comment]
it was first sudo -u www-data php occ config:system:set debug --value true --type boolean

**Comment by vitormattos** [comment]
Did this solved your problem?

**Comment by RaulGRD** [comment]
Yessssss. It's working. Thank you

**Comment by vitormattos** [comment]
I will close this as solved.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
