### ISSUE TITLE
 Cannot set non existing property OCA\\Libresign\\Handler\\CertificateEngine\\CfsslHandler

### ISSUE THREAD

**Issue by nlublovary** [LibreSign/libresign#3072]
**Reference**
This is a follow-up to #3040 

**Describe the bug**
Installed latest LibreSign App version 9.0.2 on Nextcloud 29.0.0, when clicking Files or Settings>LibreSign I still receive same error:
`Cannot set non existing property OCA\\Libresign\\Handler\\CertificateEngine\\CfsslHandler->set = array (\n  0 => 'mydomain.com',\n).`
This bug breaks Nextcloud because it throws an exception when trying to get into the Files page.

**Suggestion**
The error is thrown because Nextcloud can't find "set" property in CfsslHandler. This error can be mitigated and LibreSign will start to work, by adding the following into ./apps/libresign/lib/Handler/CertificateEngine/CfsslHandler.php 

```
	public function set($uri): void {
		if ($uri) {
			$this->appConfig->setAppValue('cfssl_uri', $uri);
		} else {
			$this->appConfig->deleteAppValue('cfssl_uri');
		}
		$this->cfsslUri = $uri;
	}
```

Hope it helps. Cheers.

**Comment by vitormattos** [comment]
Isn't at this method. The error is throws by this: https://github.com/LibreSign/libresign/blob/46a655ad9b35efb4dc81771025e281d6e3763835/lib/Helper/MagicGetterSetterTrait.php

I think that you made an upgrade from an old version of LibreSign that saved the root cert with a different structure at settings table.

I implemented the follow change to check if is this case:
https://github.com/LibreSign/libresign/pull/3062/files
But I didn't created a new release after this. This fix will come in the next release.

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made a lot of improvements.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
