### ISSUE TITLE
User group for signing not saved

### ISSUE THREAD

**Issue by jth184** [LibreSign/libresign#3082]
**Description:**

I have installed Libresign on Nextcloud. I am experiencing an issue where I need to set user groups that are allowed to request signatures. However, when I configure a group, it is not saved. There are no error messages displayed.
![image](https://github.com/LibreSign/libresign/assets/628541/9cac6bf1-427c-4276-88eb-a7167a7889ff)
After refreshing the page:
![image](https://github.com/LibreSign/libresign/assets/628541/de4e956f-6699-4966-8800-0cae8341b39c)

If a user from this group tries to sign a document, an error message "You don't have sufficient rights" appears
![image](https://github.com/LibreSign/libresign/assets/628541/08c6e195-05c2-4bea-bbaa-ff9c066c3d5d)

**Steps to Reproduce:**

Go to the Libresign settings in Nextcloud.
Set a user group that should be allowed to request signatures.
Save the settings.
The group is not saved and the configuration does not persist.
Expected Behavior:
The user group should be saved and should appear in the configuration.

**Actual Behavior:**
The user group is not saved and the configuration does not persist.

**Environment:**

Nextcloud version: 29
Libresign version: 9.0.2
Server OS: Debian 12 LXC on Proxmox 8.2.2
Browser: Google Chrome / Firefox

**Additional Information:**

There are no error messages in the Nextcloud logs or web server logs.
I have checked user permissions and group configurations.
I have tried clearing the cache and restarting the server.
I am using the latest versions of Nextcloud and Libresign.
Please let me know if you need any further information or logs.

Thank you for your assistance.

**Comment by vitormattos** [comment]
I will check this. Thanks by your help to this project.

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made a lot of improvements.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
