### ISSUE TITLE
No way to return from the validation after signing

### ISSUE THREAD

**Issue by kater-murr** [LibreSign/libresign#3133]
**Describe the bug**
After signing a document you get forwarded to the validation page, but differently from getting here after requesting a validation, there is no small cross shaped button in the top right corner to close the validation and return to where you came from, presumably the files app. So there is no other way to return than using the browser's back button.

**To Reproduce**
- Log into Nextcloud
- Receive a notification about a signing request
- Click on 'View'
- Click on 'Sign the document' and 'Confirm'
- You are forwarded to the validation outcome with no button to close the validation and return to the files app. (The button marked with 'Return' brings you back to where you can change the ID of the document to validate, also without possibility to close the validation.)

**Expected behavior**
I'd expect a button to show up that brings me back to where I came from, presumably the files app.

**Screenshots**
![grafik](https://github.com/LibreSign/libresign/assets/44290287/97a7549a-cfc0-4bd8-bd63-8a4710fb6f99)

**Environment information (please complete the following information):**
 - OS: Server Debian Bullseye, Client Manjaro, Windows
 - Browser LibreWolf, Firefox, Chromium
 - LibreSign Version 9.0.2
 - Nextcloud Server Version 29.0.0

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made improvements at this point.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
