### ISSUE TITLE
l10n: Need context to understand strings

### ISSUE THREAD

**Issue by rakekniven** [LibreSign/libresign#316]
https://github.com/LibreSign/libresign/blob/a0716811df1e26b547ec3d85d9480ec63e28b7c8/lib/Helper/ValidateHelper.php#L149

Could this mean "... the signer requested for ..." or "... the designated signer for ..."? 

https://github.com/LibreSign/libresign/blob/a0716811df1e26b547ec3d85d9480ec63e28b7c8/lib/Helper/ValidateHelper.php#L155

Could this mean "User must input values"?

Asked at Transifex.

**Comment by rakekniven** [comment]
Hello @vitormattos , can you spend a second?

**Comment by vitormattos** [comment]
Hi @rakekniven,

Sorry for the delay in replying.
We are focused on finding ways to get funding for LibreSign.
I am very happy for your contributions to the project.

> https://github.com/LibreSign/libresign/blob/a0716811df1e26b547ec3d85d9480ec63e28b7c8/lib/Helper/ValidateHelper.php#L149
> 
> Could this mean "... the signer requested for ..." or "... the designated signer for ..."?

This phrase is used in an incorrect use of the API. Returns when a request is made for some action in the file that only those who requested the document to be signed should do.

Normally, in the origin application or in the frontend, there should already be some logic to prevent the action to be performed.

Examples of moments that is used:
- Request the exclusion of someone who must sign a document.
- Send reminder to someone who must sign a document.

Maybe it can be used:

`You do not have permission for this action.`

> https://github.com/LibreSign/libresign/blob/a0716811df1e26b547ec3d85d9480ec63e28b7c8/lib/Helper/ValidateHelper.php#L155
> 
> Could this mean "User must input values"?

This phrase is used in an incorrect use of the API. It returns when a request is made that needs user data and does not have any user data.

Perhaps a better phrase to make the translation easier might be: No user data.

What do you think?

**Comment by Valdnet** [comment]
> Perhaps a better phrase to make the translation easier might be: No user data.

If a given message is to inform only about an error, in my opinion it can be: `No user data`.

Unless it is to specifically inform about some lack of data.

@rakekniven What do you think of the text string proposed by vitormattos?

**Comment by rakekniven** [comment]
`No user data` works for me.

Regarding the first topic:
`You are not the signer request for this file`.

This english does not sound good to me.
I understood your explanation.

Ahh, did not not notice your suggestion:
`You do not have permission for this action.`

Works for me as well and it will be an improvement.
