### ISSUE TITLE
Fix pagination

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/libresign#3245]
Now we return 100 items by page, when we have more than 100 items, is necessary to display the content of next page.

## API side
- [x] Is returning the follow json. But need to return populated the fields that have null values.
  - https://github.com/LibreSign/libresign/pull/3266
  ```json
  "pagination": {
      "total": 100,
      "current": null,
      "next": null,
      "prev": null,
      "last": null,
      "first": null
    }
  ```
## Frontend side
- [ ] At Files, need to be possible to see all files scrolling down.

**Comment by hunxjunedo** [comment]
@vitormattos can I get assigned ? I'd like to contribute.

**Comment by vitormattos** [comment]
Yes @hunxjunedo !
If you want, we can pair at this task to share knowledge.

**Comment by vitormattos** [comment]
The start point is this:

https://github.com/LibreSign/libresign/blob/3022de710c86d063dab5fbfcd9b5e639c7861f63/lib/Helper/Pagination.php#L34-L49

To check what's happening I suggest the follow steps:
- Implement integration test to reproduce the problematic scenario
- Put a xdebug breakpoint at first row of this method and check if the arguments are ok.

**Comment by hunxjunedo** [comment]
@vitormattos thanks for the suggestion, let me have a look and get back to you.

**Comment by vitormattos** [comment]
At the file CONTRIBUTING have instructions about how to setup the development environment.

**Comment by vitormattos** [comment]
Hi @hunxjunedo,
I will need to works in this issue. Did you want to pair with me?
If yes, could you join to LibreSign group at Telegram to be possible we check a best moment to work together sharing screen to works in this issue? Our group at Telegram is: https://t.me/LibreSign. Don't worry about Portuguese messages at this group, we talk the language of person that send the message, commonly is Portuguese, but we can talk in English too.

**Comment by hunxjunedo** [comment]
Sure, it will be my pleasure. Unfortunately I can't connect on Telegram, Discord maybe ? I'm having trouble reproducing the issue, will have to setup the data first.

**Comment by vitormattos** [comment]
We haven't Discord.
what is your time zone and the best time interval to have a call?

**Comment by hunxjunedo** [comment]
Sure! I'm in PKT timezone, UTC +05 , we can have a call 12 PM UTC, that's 5pm PKT.

**Comment by vitormattos** [comment]
@hunxjunedo is this time ok for you?

5 PM UTC +5 will be 9 AM to me

If OK, I will stay at this link:

https://meet.librecode.coop/b060a974-eaf2-496f-8f82-b1c6510fbfbc

**Comment by hunxjunedo** [comment]
UPDATE: docker composing

**Comment by hunxjunedo** [comment]
@vitormattos the docker compose command is having trouble connecting nextcloud to mysql. I'm troubleshooting, I suggest to proceed with solving the issue.

**Comment by vitormattos** [comment]
This is common before finish the setup. Is necessary to wait a bit.

![Screenshot_20240702_144008](https://github.com/LibreSign/libresign/assets/1079143/8ed4d164-1156-46eb-b5fd-1ca5c1de0fdf)

When run the first `docker compose up ....` will clone the Nextcloud server repository and this could delay a bit.

**Comment by vitormattos** [comment]
Closing this issue because need to be replaced by
-  #3143

**Comment by hunxjunedo** [comment]
Alright I got it, have you reached a solution?

**Comment by vitormattos** [comment]
The solution at backend side was a bit big. I made at this PR:
- https://github.com/LibreSign/libresign/pull/3266

The frontend solution I think that will be best to implement at issue that I commented because we will need to change the listening components. This will be complex to do.
