### ISSUE TITLE
Error creating password

### ISSUE THREAD

**Issue by mineus55** [LibreSign/libresign#328]
Hi,

I am stuck at the part where I am asked to create a password to sign document but also receive error when trying to create password:

"Error creating new password, please contact the administrator"

Next cloud log is not showing the said error, but I haven't tinkered with my log level though.

Any idea what could be the cause here? My setup:

Ubuntu 20.04 VM
NC 21.0.3
Libresign 2.4.2

And another question, does cfssl server have to be running all the time or just during cert generations?

Thanks in advance.

**Comment by vitormattos** [comment]
Hi  @mineus55,

In this action the frontend is not displaying the response returned by the LibreSign API. Press F12 on your browser and on the Network tab see the response to the request made when you save to reset the password.

Thanks for the contribution.

**Comment by mineus55** [comment]
Thanks for your clue..it's resolved now...=)

For future users stumbling upon this issue, it was caused by the browser not being able to connect to cfssl server at the given port. In my case the cause was unrelated to libresign. I guess this also means cfssl always has to be running 24/7.

I'm closing this issue.
