### ISSUE TITLE
Libresign:Install scripts doesn't seem to work properly.

### ISSUE THREAD

**Issue by Albusoline** [LibreSign/libresign#3292]
Dear vitormattos.
Thank you for your comment and your work in #1798 
Meanwhile I updated php from 7.4.3 to 8.1.
Nextcloud: 29.0.3
LibreSign: 9.1.2

I installed everything by using:
occ libresign:uninstall --all
occ files:scan-app-data libresign
occ libresign:install --all

Then I rebooted the server.

However, when using occ libresign:configure:check I get
![grafik](https://github.com/LibreSign/libresign/assets/96739565/af812bf1-0f3c-4df6-bc09-697b439e5da8)

On the error log in Nextcloud I found multiple of the entries (almost at the same time):
{"reqId":"XLnVSZf790zQyTeut9r7","level":3,"time":"2024-07-07T14:55:32+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"chmod(): Operation not permitted at /var/www/nextcloud/apps/libresign/lib/Service/Install/InstallService.php#599","userAgent":"--","version":"29.0.3.4","data":{"app":"PHP"},"id":"668ab011e63ec"}

Any ideas?

**Comment by vitormattos** [comment]
This is a problem at build process when sign the dependencies of LibreSign. You can ignore this message for now.

This is the problem at build:
https://github.com/LibreSign/libresign/actions/runs/9785773468/job/27019904975#step:19:627
I need to check whats happening with private key that can't be read.

**Comment by vitormattos** [comment]
I created an issue about chmod.

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

Closing this issue as solved (check setup).

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
