### ISSUE TITLE
Invalid data to validate file

### ISSUE THREAD

**Issue by tendaworld** [LibreSign/libresign#330]
{"reqId":"1rLTerl6ymAfR3tIv81G","level":3,"time":"2021-07-13T09:09:21+00:00","remoteAddr":"41.80.96.147","user":"txxxxxxx.xx@gmail.com","app":"libresign","method":"GET","url":"/apps/libresign/api/0.1/file/validate/uuid/9aa22458-2996-472a-8cb5-aad6dcee472e","message":"Invalid data to validate file","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0","version":"22.0.0.11","id":"60ed584226fbc"}

Is it a missing url issue as of { "url":"/apps/libresign/api/0.1/file/validate/uuid/9aa22458-2996-472a-8cb5-aad6dcee472e" }
or is it something else?
How can i check and/or fix it?
What is the expected format?

**Comment by vitormattos** [comment]
It can also be understood as:
> File not found.

Was this request made by LibreSign itself or is it some integration that you are developing?

In the log has a file UUID in a validation URL. A LibreSign file has 2 types of UUID:
1. File identifier. Added to the footer of the signed PDF and returned by the API to anyone requesting a document to be signed.
2. Identifier of a document signing request. Sent in an email link to whoever must sign a document.

For validation only the file identification UUID works, the sign request identification is only for signing a document and is not the same as the file identification.

**Comment by Khomotica** [comment]
Hi @vitormattos 
the same issue here when trying to validate every PDF file : 

`{"reqId":"yyteo5OJnRn2J7HMqE0f","level":3,"time":"2021-08-10T15:14:03+02:00","remoteAddr":"x.x.x.x","user":"harvester","app":"libresign","method":"GET","url":"/apps/libresign/api/0.1/file/validate/uuid/828f53fd-3bfe-475c-a400-4fd88a361975","message":"Invalid data to validate file","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":"22.1.0.0"}
`

**Comment by upultfs** [comment]
@Khomotica  
I'm having the same issue did anyone fix this?

{"reqId":"Wkseocznr54c6jKVm9oi","level":3,"time":"2021-11-23T04:01:33+00:00","remoteAddr":"43.245.82.32","user":"upulssds@yahoo.com","app":"libresign","method":"POST","url":"/nextcloud/index.php/apps/libresign/api/0.1/sign/uuid/a4469898-0cc6-4869-bb9c-f5e5f461ba8a","message":"Error to sign PDF. []","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36","version":"22.2.0.2"}

**Comment by vitormattos** [comment]
Hi @Khomotica the UUID to validate file you can find on footer of document. The UUID that the users receive on URL to sign the document don't is the same to use on validation page.

Hi @upultfs this error is trigged by JSignPDF when try to sign a PDF with structural problem. Can you try with other PDR generated by other way? I already reproduced this and fixed on main branch but we need make the main branch stable to launch new release with this fix and many others news, for example, signing using visible signature.

**Comment by upultfs** [comment]
@vitormattos  thanks for reply. I will wait until with new release

**Comment by Iwios** [comment]
Hello,
I have this error. This is very strage from my account no error, but when other account try to sign the same file he got this error.

I have the request answer:

<?xml version="1.0" encoding="utf-8"?>

<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">

  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>

  <s:message>File with name //Sans nom 4.pdf could not be located</s:message>

</d:error>

**Comment by vitormattos** [comment]
Hi @Iwios,
You have more details?
I never saw anything like this.

**Comment by vitormattos** [comment]
I will close this issue, the last comments are out of topic.
