### ISSUE TITLE
Unable to install java/jsignpdf/pdftk from command line on Nextcloud v28.0.2

### ISSUE THREAD

**Issue by DazeEnd** [LibreSign/libresign#3312]
**Describe the bug**
When running LibreSign v8.1.3 on Nextcloud v28.0.2, an error is returned when installing the pdf, jsignpdf, and pdftk binaries from command line.

**To Reproduce**
1. Install a new instance of Nextcloud v28.0.2.
2. Log in as the admin and install LibreSign v8.1.3.
3. Log into the server via `ssh` and change to the nextcloud installation directory.
4. Run the following commands to install the required binaries:
```
sudo -u apache php occ libresign:install --java
sudo -u apache php occ libresign:install --pdftk
sudo -u apache php occ libresign:install --jsignpdf
```

**Expected Results**
After running each command in step 4 above, each binary should be successfully installed.

**Actual Results**
The following error is printed after each command is run:
```
In Folder.php line 162:
                                                              
  Could not create folder "/appdata_ocnb4cjpki06/libresign/"
```

**Screenshots**
![Screenshot from 2024-07-09 14-08-53](https://github.com/LibreSign/libresign/assets/2699247/5674c16c-2bd2-4598-b897-01b078e3cd4d)
![Screenshot from 2024-07-09 14-32-56](https://github.com/LibreSign/libresign/assets/2699247/e6617dce-d89b-498c-9d88-3099c5385c9e)

**Environment information (please complete the following information):**
 - OS: AlmaLinux v8.4
 - Browser: N/A
 - LibreSign Version: v8.1.3
 - Nextcloud Server Version: v28.0.2
 - Logs:
```
{"reqId":"AKeuMPCTzLS2jZUBo7de","level":3,"time":"2024-07-09T14:07:06-04:00","remoteAddr":"","user":"--","app":"libresign","method":"","url":"--","message":"Could not create folder \"/appdata_ocnb4cjpki06/libresign/\"","userAgent":"--","version":"28.0.2.5","data":{"app":"libresign"}}
{"reqId":"ab1FACsGABqspZfPuonR","level":3,"time":"2024-07-09T14:10:09-04:00","remoteAddr":"","user":"--","app":"libresign","method":"","url":"--","message":"Could not create folder \"/appdata_ocnb4cjpki06/libresign/\"","userAgent":"--","version":"28.0.2.5","data":{"app":"libresign"}}
{"reqId":"AeNC1gvy9LZwSGvWh20p","level":3,"time":"2024-07-09T14:11:40-04:00","remoteAddr":"","user":"--","app":"libresign","method":"","url":"--","message":"Could not create folder \"/appdata_ocnb4cjpki06/libresign/\"","userAgent":"--","version":"28.0.2.5","data":{"app":"libresign"}}
{"reqId":"2sXNA4d98n5hyidGb1tc","level":3,"time":"2024-07-09T14:13:10-04:00","remoteAddr":"","user":"--","app":"libresign","method":"","url":"--","message":"Could not create folder \"/appdata_ocnb4cjpki06/libresign/\"","userAgent":"--","version":"28.0.2.5","data":{"app":"libresign"}}
{"reqId":"JuiGjvXDXWUfGpqE2h1X","level":3,"time":"2024-07-09T14:13:19-04:00","remoteAddr":"","user":"--","app":"libresign","method":"","url":"--","message":"Could not create folder \"/appdata_ocnb4cjpki06/libresign/\"","userAgent":"--","version":"28.0.2.5","data":{"app":"libresign"}}
```
**Additional context**
1. After upgrading Nextcloud to v28.0.7, this error was no longer displayed, and I was able to install the binaries successfully.
2. I almost didn't file this bug since upgrading Nextcloud makes it go away. However, since LibreSign v8.1.3 is marked as being compatible with Nextcloud v28.0.2, I decided to file this issue to let you know about it.
3. Just for the record, I think it is reasonable to close this issue as "Won't Fix" and tell people to upgrade to the newest minor version of Nextcloud 28 if fixing this issue is non-trivial.

**Comment by vitormattos** [comment]
Thanks again by your contribution!

This is a very specific scenario and relative to an old version of LibreSign.

Considering that using the latest version of LibreSign and Nextcloud don't throws the error, we can close this.
