### ISSUE TITLE
Install scripts doesn't seem to work properly --> continuation from #3292

### ISSUE THREAD

**Issue by Albusoline** [LibreSign/libresign#3313]
Dear vitormattos.
Thank you for your comment and your work in #3292.
This issue is the same topic.

Updated to LibreSign 9.1.3
Nextcloud: 29.0.3

I installed everything by using:
occ libresign:uninstall --all
occ files:scan-app-data libresign
occ libresign:install --all

Then I rebooted the server.

However, when using occ libresign:configure:check I still get
![grafik](https://github.com/LibreSign/libresign/assets/96739565/7e672031-1952-4945-aae9-a706166d646b)

On the error log in Nextcloud I found multiple entries about Operation not permitted:

_One is:_
{"reqId":"rSPI4WWIiG7LYnZCTOfY","level":3,"time":"2024-07-09T18:01:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"chmod(): Operation not permitted at /var/www/nextcloud/apps/libresign/lib/Service/Install/InstallService.php#599","userAgent":"--","version":"29.0.3.4","data":{"app":"PHP"},"id":"668d864891f86"}
 **--> seem to be the bug from #3293**

_others_:
`{"reqId":"rSPI4WWIiG7LYnZCTOfY","level":3,"time":"2024-07-09T17:59:43+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"ZipArchive::extractTo(/mnt/data/appdata_ocmjteth5a7k/libresign/aarch64/jsignpdf/jsignpdf-2.2.2/JSignPdf.jar): Operation failed: Operation not permitted at /var/www/nextcloud/lib/private/Archive/ZIP.php#189","userAgent":"--","version":"29.0.3.4","data":{"app":"PHP"},"id":"668d864891fdd"}`

Owner and Group rwx for all folders recursively of /var/www/nextcloud/... is www-data www-data.
Owner and Group rwx for all folders recursively of  /mnt/data/...  is root www-data

**Comment by vitormattos** [comment]
I think that this is related to:
- #3293

**Comment by vitormattos** [comment]
I will close this issue because is duplicated of #3293. Let's go ahead talking about this at #3293 issue.
