### ISSUE TITLE
Nextcloud AIO 29.0.3 and LibreSign 9.1.3 can't get past 'Invalid hash of binaries files.' error

### ISSUE THREAD

**Issue by t3cneo** [LibreSign/libresign#3324]
**Describe the bug**
NC AIO 29.0.3 here with LibreSign 9.1.3, can't get past the 'Invalid hash of binaries files.' error

**To Reproduce**
Install LibreSign 9.1.3 from webUI, click 'Download Binaries' and get the error.
Install from cli (from inside the container) lead to the same error.

**Expected behavior**
Binaries installed and LibreSign ready to work..

**Screenshots**
![Copie d'écran_20240710_211823](https://github.com/LibreSign/libresign/assets/42748615/b82e1720-e7aa-4523-a995-d81c2b9c1fd0)

**Environment information (please complete the following information):**
 - OS: Docker AIO
 - Browser Firefox
 - LibreSign Version 9.1.3
 - Nextcloud Server Version 29.0.3
 - Logs 

![Copie d'écran_20240710_212226](https://github.com/LibreSign/libresign/assets/42748615/65f64c57-3550-471b-b80c-d58408ca82bb)

**Additional context**
I read all topics related to AIO, especially #1409 and #3026, here are a few things you might ask :

`NEXTCLOUD_ADDITIONAL_APKS` is set to `imagemagick ghostscript` and the output of `gs --version` is `10.03.1`

Java seams to install as expected  :
```
8b0f582248ca:/var/www/html$ /mnt/ncdata/appdata_ID/libresign/x86_64/java/jdk-21.0.2+13-jre/bin/java --version
openjdk 21.0.2 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)
```

EDIT: 

Don't think it could be related but alpine has been bumped since #3026 

```
8b0f582248ca:/var/www/html$ php -r "var_dump(shell_exec('cat /etc/*-release'));"
string(195) "3.20.1
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.20.1
PRETTY_NAME="Alpine Linux v3.20"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
"
```

**Comment by t3cneo** [comment]
It's getting better but weird :

I had the idea to try earlier version of LibreSign.

Could not get any of 9.1.x version working but 9.0.2 installed and got me passed the webUI LibreSign Wizard. 
I could not get the webapp to work though (visiting `https://cloud.mydomain.tld/apps/libresign/*` would break Nextcloud's menu) so I updated it via webUI and it is now working.

I can still see the 'Invalid hash of binaries files.' error when visiting `https://cloud.mydomain.tld/settings/admin/libresign` (exactly the same as in the first screenshot) but the webapp at `https://cloud.mydomain.tld/apps/libresign/*` is working now. (only tested signing requests via email)

**Comment by vitormattos** [comment]
These dependencies are no longer necessary in LibreSign, they have been replaced by pdftk.

> NEXTCLOUD_ADDITIONAL_APKS is set to imagemagick ghostscript and the output of gs --version is 10.03.1

**Comment by vitormattos** [comment]
Could you provide more information about the files that stay at log? Sounds that PHP haven't access to these files.

Other possible points to check is about this issue:
- https://github.com/LibreSign/libresign/issues/3227

Another point to check is a ls -l at folder appinfo of LibreSign. The build process put the signature files of binaries inside this folder.

**Comment by vitormattos** [comment]
@t3cneo I identified a problem at build process and created a new release with fixes.

Could ou test again with the newest release?

**Comment by t3cneo** [comment]
All good now with 9.2.2, thanks a lot @vitormattos

**Comment by vitormattos** [comment]
@t3cneo we need help to funding this project.
If you like this project  and want to help, you could make a recurrent [sponsor](https://github.com/sponsors/LibreSign)
The funding is very important to keep alive this project.
