### ISSUE TITLE
Could not create folder "/appdata_oc4nx8lg6f3y/libresign/

### ISSUE THREAD

**Issue by mezzomokaue** [LibreSign/libresign#3325]
Hello,

When I try to sign a document, it keeps loading infinitely. I went to the libre sign admin panel and clicked on validate the installation but in the logs it appears to be giving an error.

Step by step:

1 - I tried to sign the document and it keeps loading infinitely.

2 - I went to the libresign admin panel and clicked on validate installation. Apparently he tries to validate but fails.

3 - I went to the logs and saw the error.

PR-BR

Olá,

Quando tento assinar um documento fica em um loading infinito. Fui no painel admin do libre sign e cliquei em validar a instalação mas nos logs aparentemente está dando erro.

Passo a passo:

1 - Tentei assinar o documento e fica em um loading infinito.

2 - Fui no painel admin do libresign e cliquei em validar instalação. Aparentemente ele tenta validar mas falha.

3 - Fui nos logs e visualizei o erro.

Loading infinito:
![image](https://github.com/LibreSign/libresign/assets/130859376/a76b7044-0c58-4ead-8db6-d60f9ec3dbae)

LibreSign admin config
![image](https://github.com/LibreSign/libresign/assets/130859376/044e8152-c43b-4e4a-9023-351a32488f3e)

Logs:
![image](https://github.com/LibreSign/libresign/assets/130859376/4428ebea-c2a4-4727-8743-e44883958bf4)

{"reqId":"THOmbexOYA3Y1mV9BRc4","level":3,"time":"2024-07-10T23:08:53+00:00","remoteAddr":"","user":"--","app":"libresign","method":"","url":"--","message":"Could not create folder \"/appdata_oc4nx8lg6f3y/libresign/\"","userAgent":"--","version":"29.0.1.1","data":{"app":"libresign"},"id":"668f161cdac5a"}

 - OS: Docker
 - Browser Chrome
 - LibreSign Version 9.1.3
 - Nextcloud Server Version 29.0.1

**Comment by vitormattos** [comment]
> Could not create folder "/appdata_oc4nx8lg6f3y/libresign/"

I identified an issue about this and fixed at newest release.

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made a lot of improvements.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
