### ISSUE TITLE
Incompatibility with groupfolders app when limiting LibreSign to groups

### ISSUE THREAD

**Issue by w1n5l0w** [LibreSign/libresign#3351]
**Describe the bug**
When I limit the usage of LibreSign to a specific group (can be any group, doesn't have to be the admin-group) in the app settings, then all users who don't belong to this group can't access groupfolders it the WebUI of the file app anymore (access via synced Nextcloud Desktop app works). These user see the groupfolders in the File app, but they are only a link to the webdav endpoint and one can't access the groupfolders via WebUI.

**To Reproduce**
- I'm an admin user, the groufolders app is installed and there is at least one groupfolder created to which i have access to
- Go to 'App Settings' (/settings/apps/)
- Click on 'LibreSign' and limit the usage of the app to an group I am not a member of
- Go to 'Files app' (/apps/files/)
- I can't access the groupfolder anymore, the listed groupfolder only provides a link to /remote.php/dav/files/<user>/<groufolder>/

**Expected behavior**
Any user can access the groupfolders to which s/he has access, no matter if the usage of the LibreSign app is limited to group(s)

**Environment information (please complete the following information):**
 - OS: Debian Bookworm
 - Browser: Doesn't matter if Firefox or Chromium
 - LibreSign Version 9.2.0
 - Nextcloud Server Version 29.0.3
 - Logs (get the entries from nextcloud.log related with LibreSign i.e `tail -f data/nextcloud.log|grep libresign`)
```
{"reqId":"QoHC0DOxs3qTqDhpJNI2","level":3,"time":"2024-07-11T21:50:03+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job OCA\\Libresign\\BackgroundJob\\UserDeleted (id: 321, arguments: null)","userAgent":"--","version":"29.0.3.4","exception":{"Exception":"TypeError","Message":"OCA\\Libresign\\Db\\FileMapper::neutralizeDeletedUser(): Argument #1 ($userId) must be of type string, null given, called in /srv/nextcloud/app/apps/libresign/lib/BackgroundJob/UserDeleted.php on line 39","Code":0,"Trace":[{"file":"/srv/nextcloud/app/apps/libresign/lib/BackgroundJob/UserDeleted.php","line":39,"function":"neutralizeDeletedUser","class":"OCA\\Libresign\\Db\\FileMapper","type":"->"},{"file":"/srv/nextcloud/app/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\Libresign\\BackgroundJob\\UserDeleted","type":"->"},{"file":"/srv/nextcloud/app/lib/public/BackgroundJob/QueuedJob.php","line":57,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/srv/nextcloud/app/lib/public/BackgroundJob/QueuedJob.php","line":47,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"},{"file":"/srv/nextcloud/app/cron.php","line":177,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/srv/nextcloud/app/apps/libresign/lib/Db/FileMapper.php","Line":227,"message":"Error while running background job OCA\\Libresign\\BackgroundJob\\UserDeleted (id: 321, arguments: null)","exception":{},"CustomMessage":"Error while running background job OCA\\Libresign\\BackgroundJob\\UserDeleted (id: 321, arguments: null)"}}
{"reqId":"aVnCH7YD4YIgqJMuDUC1","level":3,"time":"2024-07-11T22:15:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type null at /srv/nextcloud/app/apps/libresign/lib/BackgroundJob/UserDeleted.php#34","userAgent":"--","version":"29.0.3.4","data":{"app":"PHP"}}
{"reqId":"aVnCH7YD4YIgqJMuDUC1","level":3,"time":"2024-07-11T22:15:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type null at /srv/nextcloud/app/apps/libresign/lib/BackgroundJob/UserDeleted.php#35","userAgent":"--","version":"29.0.3.4","data":{"app":"PHP"}}
{"reqId":"aVnCH7YD4YIgqJMuDUC1","level":3,"time":"2024-07-11T22:15:02+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job OCA\\Libresign\\BackgroundJob\\UserDeleted (id: 325, arguments: null)","userAgent":"--","version":"29.0.3.4","exception":{"Exception":"TypeError","Message":"OCA\\Libresign\\Db\\FileMapper::neutralizeDeletedUser(): Argument #1 ($userId) must be of type string, null given, called in /srv/nextcloud/app/apps/libresign/lib/BackgroundJob/UserDeleted.php on line 39","Code":0,"Trace":[{"file":"/srv/nextcloud/app/apps/libresign/lib/BackgroundJob/UserDeleted.php","line":39,"function":"neutralizeDeletedUser","class":"OCA\\Libresign\\Db\\FileMapper","type":"->"},{"file":"/srv/nextcloud/app/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\Libresign\\BackgroundJob\\UserDeleted","type":"->"},{"file":"/srv/nextcloud/app/lib/public/BackgroundJob/QueuedJob.php","line":57,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/srv/nextcloud/app/lib/public/BackgroundJob/QueuedJob.php","line":47,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"},{"file":"/srv/nextcloud/app/cron.php","line":177,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/srv/nextcloud/app/apps/libresign/lib/Db/FileMapper.php","Line":227,"message":"Error while running background job OCA\\Libresign\\BackgroundJob\\UserDeleted (id: 325, arguments: null)","exception":{},"CustomMessage":"Error while running background job OCA\\Libresign\\BackgroundJob\\UserDeleted (id: 325, arguments: null)"}}
```

**Comment by vitormattos** [comment]
Sounds that this log isn't related to described scenario.

**Comment by vitormattos** [comment]
I think that I didn't understood your scenario. Could you explain with more details?

**Comment by w1n5l0w** [comment]
I can try. But what exactly don't you understand?

**Comment by vitormattos** [comment]
This was fixed here:

https://github.com/LibreSign/libresign/commit/f96ae08741944d54ab8e22f26d58513379cd6e7d

Could you check again at the newest release of LibreSign?

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
