### ISSUE TITLE
Signature Pic isn't shown.

### ISSUE THREAD

**Issue by MarkusWortmann** [LibreSign/libresign#3403]
After creating a User Signature [ Upload an .png or create by draw ] it is shown in this session, but if you left the session and com back there is only a brocken picture sign in the browser.

**Screenshots**
![Bildschirmfoto vom 2024-07-22 09-54-08](https://github.com/user-attachments/assets/788a166d-9538-40fc-ac5a-c740a3b7f4da)

**Environment information (please complete the following information):**
 - OS: Debian 12 
 - Browser Chrome
 - LibreSign Version : 9.2.2
 - Nextcloud Server Version: 29.0.4
 - Logs: no log data during this issue

**Comment by vitormattos** [comment]
Fixed here:
- https://github.com/LibreSign/libresign/pull/3425
Will come in the next release.

**Comment by vitormattos** [comment]
@MarkusWortmann could you test again with the newest release?

**Comment by MarkusWortmann** [comment]
@vitormattos all looks fine now. Thanks 
![LibreSign_new](https://github.com/user-attachments/assets/de2a5587-0b41-4aea-b330-7388963086fc)

**Comment by vitormattos** [comment]
Hi @MarkusWortmann very nice to see that all worked fine to you!

I made a refactor in all routes of LibreSign to be possible to we have the OpenApi documentation inside the code. At this refactor I put the wrong verb to the endpoint of signature, but this was fixed.

If LibreSign help your daily work and is a good app to the company that you work returning reduction of cost to use digital signatures, we will like a lot to receive a recurrent contribution at GitHub sponsor to help us to maintain the development of this app that we love a lot and do a very big work to maintain. We have a lot of challenges at development and a lot of ideas and to solve the challenges and implement the ideas, you can be part of this helping us.

Our sponsor is here: https://github.com/sponsors/LibreSign
