### ISSUE TITLE
Browsing a folder with numeric name leads to error

### ISSUE THREAD

**Issue by IchbinkeinReh** [LibreSign/libresign#3480]
**Describe the bug**
Browsing a folder with numeric name leads to error

**To Reproduce**
- I'm an authenticated user
- Go to the LibreSign App
- Click on "Choose from Files"
- Navigate to a folder with a purely numeric name (eg 2015)
- UI is not usable anymore and error appears in browser console

**Expected behavior**
The folder is shown and i can click on it to access files inside

**Environment information:**
 - OS: Linux Debiam
 - Browser Google Chrome 126.0.6478.12
 - LibreSign Version 9.2.3
 - Nextcloud Server Version 29.0.4

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made a lot of improvements and updated the dependency related to Nextcloud app Files.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop

**Comment by IchbinkeinReh** [comment]
Yes thank you. Its fixed now in version 9.3.1
