### ISSUE TITLE
browsing cloud files never loads

### ISSUE THREAD

**Issue by Fuseteam** [LibreSign/libresign#3505]
**Describe the bug**
when trying to choose a file from withing nextcloud the picker never loads the directory structure

**To Reproduce**
- I'm an authenticated user
- Go to Request
- Click on "Choose from Files"
- See error

**Expected behavior**
I should be able to choose a file

**Screenshots**
![image](https://github.com/user-attachments/assets/f35035e3-8248-4684-b644-8345310ab8df)

**Environment information (please complete the following information):**
 - OS: Docker 
 - Browser firefox
 - LibreSign Version 9.2.3
 - Nextcloud Server Version 29.0.4
 - Logs (console logs)
 ```
Error: Invalid displayname type
    B index.mjs:433
    N index.mjs:510
    O index.mjs:780
    L index.mjs:886
    i FilePicker-DUbP4INd.mjs:856
    value FilePicker-DUbP4INd.mjs:856
[vue.runtime.esm.js:3065:16](webpack:///libresign/node_modules/vue/dist/vue.runtime.esm.js)
    VueJS 4
        vn
        gn
        pn
        fn

​```
**Additional context**
Add any other context about the problem here.

**Comment by Fuseteam** [comment]
hmmm now i look it might be related to  #3480, the difference is that i can't browser for any files.
I do have numeric IDs for my users, could this be the cause?

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made a lot of improvements and updated the JS dependencies related to Nextcloud Files.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop

**Comment by Fuseteam** [comment]
this is indeed solved, thank you :heart:
