### ISSUE TITLE
Defining a Signature for an Anonymous User is Almost Impossible on Mobile

### ISSUE THREAD

**Issue by DynAggelos** [LibreSign/libresign#3541]
**Describe the bug**
When entering the email of a non-Nextcloud user and sending them a document to sign, they are initially greeted with a screen that tells them they have no signature defined.

![Screenshot_20240823-035123_Browser](https://github.com/user-attachments/assets/86ad4886-38e2-4493-b7a8-7acf10fb720f)

However, when trying to define a signature, the modal to do so is only 1" tall, so more than 90% of the content in the modal/popup is invisible.

![Screenshot_20240823-035137_Browser](https://github.com/user-attachments/assets/76d275dc-aaa2-47da-8590-7255a7865967)

Also, even if the user guesses they need to scroll down in the modal, if they stop over the "Draw" signature field, it's not possible to start scrolling again, because at that point the only thing to drag on is the drawing canvas (which obviously draws instead of scrolls).

**To Reproduce**
- Send a PDF to an email address that isn't signed up for an account in NextCloud.
- Open the email with a mobile device.
- Click the Sign button.
- Click the button to define a signature.
- Try to define a signature on mobile, with our without landscape orientation.

**Expected behavior**
The modal/popup should take up the full screen, with an X in the corner to close the modal.

**Environment information (please complete the following information):**
 - Device: Google Pixel 5
 - Browser: Cromite
 - LibreSign Version 9.2.3
 - Nextcloud Hub 8  (29.0.4)

**Additional context**
See related LibreSign settings here:

![image](https://github.com/user-attachments/assets/98151985-d383-4acd-bd30-382c2225f78e)

**Comment by vitormattos** [comment]
Fixed here:
- #3544

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made a lot of improvements.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
