### ISSUE TITLE
Issue on Libresign 9.2.3

### ISSUE THREAD

**Issue by alfany** [LibreSign/libresign#3543]
**Describe the bug**
Status of setup got error as below
![1](https://github.com/user-attachments/assets/e03767e8-9b69-404a-bdd7-0b9f9f018d55)

in fact already successed installing the addons
![2](https://github.com/user-attachments/assets/10408618-e53c-442a-9568-e1ac85700d6d)

on signing the document got this message
![3](https://github.com/user-attachments/assets/430faf6d-14c6-49b6-8368-6683d4387931)

**Expected behavior**
After success signing the document, signer can download or save the file.

**Environment information (please complete the following information):**
 - Shared hosting
 - LibreSign 9.2.3
 - Nextcloud Server 29.0.5

**Libresign Setting**
- Cert engine OpenSSL
- Identification [Account -> Email token] [Email -> Email token]
**Log**
{"reqId":"7XHXejVqkGF56cmA2757","level":3,"time":"2024-08-27T08:51:02+00:00","remoteAddr":"xxx","user":"--","app":"libresign","method":"POST","url":"/ocs/v2.php/apps/libresign/api/v1/sign/uuid/69ed88a5-141e-49f9-908a-c4249a888076","message":"OCA\\Libresign\\Service\\SignFileService::forceSaveFileOfDifferentUser(): Argument #2 ($content) must be of type string, bool given, called in /home/u444396987/domains/blessingtransportbromoijen.com/public_html/work/apps/libresign/lib/Service/SignFileService.php on line 590","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0","version":"29.0.5.1","data":{"app":"libresign"}}

{"reqId":"7XHXejVqkGF56cmA2757","level":3,"time":"2024-08-27T08:51:02+00:00","remoteAddr":"xxx","user":"--","app":"libresign","method":"POST","url":"/ocs/v2.php/apps/libresign/api/v1/sign/uuid/69ed88a5-141e-49f9-908a-c4249a888076","message":"[{\"file\":\"\\/home\\/u444396987\\/domains\\/blessingtransportbromoijen.com\\/public_html\\/work\\/apps\\/libresign\\/lib\\/Service\\/SignFileService.php\",\"line\":590,\"function\":\"forceSaveFileOfDifferentUser\",\"class\":\"OCA\\\\Libresign\\\\Service\\\\SignFileService\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/blessingtransportbromoijen.com\\/public_html\\/work\\/apps\\/libresign\\/lib\\/Service\\/SignFileService.php\",\"line\":423,\"function\":\"getPdfToSign\",\"class\":\"OCA\\\\Libresign\\\\Service\\\\SignFileService\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/blessingtransportbromoijen.com\\/public_html\\/work\\/apps\\/libresign\\/lib\\/Service\\/SignFileService.php\",\"line\":282,\"function\":\"getFileToSing\",\"class\":\"OCA\\\\Libresign\\\\Service\\\\SignFileService\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/blessingtransportbromoijen.com\\/public_html\\/work\\/apps\\/libresign\\/lib\\/Controller\\/SignFileController.php\",\"line\":145,\"function\":\"sign\",\"class\":\"OCA\\\\Libresign\\\\Service\\\\SignFileService\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/blessingtransportbromoijen.com\\/public_html\\/work\\/apps\\/libresign\\/lib\\/Controller\\/SignFileController.php\",\"line\":111,\"function\":\"sign\",\"class\":\"OCA\\\\Libresign\\\\Controller\\\\SignFileController\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/blessingtransportbromoijen.com\\/public_html\\/work\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php\",\"line\":232,\"function\":\"signUsingUuid\",\"class\":\"OCA\\\\Libresign\\\\Controller\\\\SignFileController\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/blessingtransportbromoijen.com\\/public_html\\/work\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php\",\"line\":138,\"function\":\"executeController\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/blessingtransportbromoijen.com\\/public_html\\/work\\/lib\\/private\\/AppFramework\\/App.php\",\"line\":184,\"function\":\"dispatch\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/blessingtransportbromoijen.com\\/public_html\\/work\\/lib\\/private\\/Route\\/Router.php\",\"line\":338,\"function\":\"main\",\"class\":\"OC\\\\AppFramework\\\\App\",\"type\":\"::\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/blessingtransportbromoijen.com\\/public_html\\/work\\/ocs\\/v1.php\",\"line\":66,\"function\":\"match\",\"class\":\"OC\\\\Route\\\\Router\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/blessingtransportbromoijen.com\\/public_html\\/work\\/ocs\\/v2.php\",\"line\":23,\"args\":[\"\\/home\\/u444396987\\/domains\\/blessingtransportbromoijen.com\\/public_html\\/work\\/ocs\\/v1.php\"],\"function\":\"require_once\"}]","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0","version":"29.0.5.1","data":{"app":"libresign"}}

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made a lot of improvements.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
