### ISSUE TITLE
Make it more obvious how to place signature box on 2nd or later page of document

### ISSUE THREAD

**Issue by DazeEnd** [LibreSign/libresign#3548]
**Is your feature request related to a problem? Please describe.**
When requesting a signature on a multi-page document, it is not obvious to the user how to place a signature box on the 2nd or later page.

In my own experience and in conversations with my users, it is very common that an inexperienced user clicks the name of the signer to place a signature box on the first page, then tries to drag the signature box into place on page 2. However, when dragging the signature box, they quickly learn that the placed signature box is confined to the first page and that it cannot be dragged to other pages.

The user may then try to scroll the document so that the desired page is visible in the preview before placing a signature box, but when they click the name of the signer the signature box is again placed on page 1.

It usually requires a phone call to me to explain how things work before they learn that they have to **click** on the desired page before placing the signature box.

This whole process is frustrating and confusing.

**Describe the solution you'd like**
Ideally, a signature box could be placed anywhere on the document, and then dragged to any other page. This would be the most obvious from the perspective of a new user.

**Describe alternatives you've considered**
If a signature box must be constrained to only one page, it should be much more obvious which page is currently selected so that the user can guess that they need to select the right page before placing the signature box. I would suggest that the currently selected page be highlighted with a colored frame.

**Additional context**
![image](https://github.com/user-attachments/assets/c9ac0426-7962-4f56-bdc6-bf24c390eebc)

**Comment by vitormattos** [comment]
Maybe blocking to move the box outside to page could be a good step to solve this UX problem.

**Comment by vitormattos** [comment]
Fixed by #3983

Coming in the next release.

**Comment by DazeEnd** [comment]
Great. That will much appreciated by my customers.

I agree that not allowing the signature outside the page is a good first step, but I strongly encourage you to pair that with some type of stronger indication of which page is currently selected. I’ve watched my customers use the tool, and it is very common for them to just scroll to the appropriate page and then create a signature field without clicking the page. It just doesn’t register with them that they need to scroll AND click the page.

Thanks for all your work on this.

**Comment by vitormattos** [comment]
>  pair that with some type of stronger indication of which page is currently selected

I already made this ;)

It will come in the next release.

Now, after click at signer name, is displayed this:

![Screenshot_20241119_165246](https://github.com/user-attachments/assets/845da035-728b-4f1e-a424-66da2ad4dd4b)

**Comment by vitormattos** [comment]
Is ok this message in English?

**Comment by DazeEnd** [comment]
I would suggest:

"Click the location where the signature should appear."
...or...
"Click the page on which the signature should appear." -- This version emphasizes the need for the user to select the right page.

I think either would be ok. Since I haven't seen the workflow in action, I'm not sure which is more appropriate.

**Comment by vitormattos** [comment]
https://github.com/user-attachments/assets/cceb00d8-d360-46ca-98ac-89bd2344e2fa
