### ISSUE TITLE
Page not found signing in from the details menu

### ISSUE THREAD

**Issue by cabaseira** [LibreSign/libresign#3611]
**Describe the bug**
When I try to sign a document from the document details side menu, I get an error:
"Page not found"

**To Reproduce**
- I'm an authenticated user
- Go to the details menu of the document I want to sign.
- I request that the document be signed only by me.
- In the same file details menu, I click on "sign"
- I get the error

**Expected behavior**
The signing process should continue.

**Screenshots**

![H7u3ShzvlD](https://github.com/user-attachments/assets/444282f9-6be7-468b-85b2-6d92419a419e)

![c71R2HnEN1](https://github.com/user-attachments/assets/66deb17e-d4e1-47b5-84bf-949b8fbf8d3d)

![vKTdT33v8b](https://github.com/user-attachments/assets/8d23bdcb-4328-41e4-82f2-3423600f1a55)

![Gl2q1UcII6](https://github.com/user-attachments/assets/ed3e779e-46c0-4ad9-b1c7-e00a3427f916)
231aa5a.png)

![Ta2P50Q0k4](https://github.com/user-attachments/assets/e7aa1a86-b2ee-418a-89d1-ff23d1f65d0c)

![L0HBWM9K3V](https://github.com/user-attachments/assets/23774973-03c0-42e1-aee3-5ea70ef44ed8)

**Environment information (please complete the following information):**
 - OS: Docker
 - Browser: Mozilla Firefox, Microsoft Edge
 - LibreSign Version 9.2.3
 - Nextcloud Server Version 29.0.4

**Comment by vitormattos** [comment]
will be closed by next release

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made a lot of improvements.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop

**Comment by cabaseira** [comment]
I miss a button to be able to close the modal window when the signing process is finished. Now, the only way to close that modal window is to refresh nextcloud again.

![Captura de pantalla 2024-09-15 153631](https://github.com/user-attachments/assets/ae16cb0f-f8c0-4db0-8956-3131c7d405f7)
