### ISSUE TITLE
Add filter by signature date at listing endpoint

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/libresign#3623]
Add two more query string to filter by signature date:

- sign_date_begin
- sign_date_end

When the begin will be greater than the defined date and end less than.

Consider as date format: YYYY-MM-DD

Don't consider the time, only use the date.

At API side, the end date should have the suffix 23:59:59 and the begin the suffix 00:00:00.

Route to be changed: `GET: /api/{apiVersion}/file/list`

Fallback of:
https://github.com/LibreSign/libresign/pull/3599

Don't worry about frontend, will be refactored by:
- https://github.com/LibreSign/libresign/issues/3143

to-do
- [ ] change the code
- [ ] run the command `composer openapi` to update endpoint documentation
- [ ] run the command `composer cs:fix` to apply PHP linter
- [ ] write integration or unit tests
- [ ] sign-off all commits

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by vitormattos** [comment]
I have added this feature to the new release.
