### ISSUE TITLE
Cannot close the modal window after sign a file from app Files

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/libresign#3715]
> I miss a button to be able to close the modal window when the signing process is finished. Now, the only way to close that modal window is to refresh nextcloud again.

![Captura de pantalla 2024-09-15 153631](https://github.com/user-attachments/assets/ae16cb0f-f8c0-4db0-8956-3131c7d405f7)

_Originally posted by @cabaseira in https://github.com/LibreSign/libresign/issues/3611#issuecomment-2351598968_

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
