### ISSUE TITLE
Footer with `QR code` is printed at wrong place when the PDF file have pages with different dimensions

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/libresign#3744]
**Describe the bug**
The footer with `QR code` is printed at wrong place when the PDF file have pages with different dimensions.

**To Reproduce**
- I'm an authenticated user
- I go to LibreSign App
- I go to Request
- I go to Upload
- I send the follow PDF file: [multisizes-1.pdf](https://github.com/user-attachments/files/17066232/multisizes-1.pdf)
- I click to add signer, choose herself and click at Next
- I don't need to set a visible signature, then I only click to `Request` button and confirm
- I go to `Files` at LibreSign app
- I click at `multisizes-1` file and sign the document
- When I click at button `View`, the `QR code` will be displayed at wrong places at pages

**Expected behavior**
Put the footer with the `QR code` at left botton corner of all pages

**Screenshots**
The wrong behavior:
![Screenshot_20240919_174651](https://github.com/user-attachments/assets/d9619e40-8ebb-4f11-a586-18b59285a5d1)

**Environment information (please complete the following information):**
 - Browser Firefox 130
 - LibreSign Version 11.0.0-dev
 - Nextcloud Server Version [e.g. 31.0.0 dev]

**Comment by Ravijhabit** [comment]
Hi @vitormattos, Can you assign me this issue ?

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
