### ISSUE TITLE
File Upload for Validation

### ISSUE THREAD

**Issue by vinicios-gomes** [LibreSign/libresign#375]
Given I'm on the validation page (validador.libresign.coop)
And I see "Upload" option
And I click "Upload"
So I should see the subscription data

More information: https://www.portaldeassinaturas.com.br/VerificadorAssinaturas/Verificador

**Comment by vitormattos** [comment]
Moved to GitLab:

https://gitlab.com/librecodecoop/libresign/libresign/-/issues/375
