### ISSUE TITLE
l10n: Incomplete sentence 

### ISSUE THREAD

**Issue by rakekniven** [LibreSign/libresign#3782]
https://github.com/LibreSign/libresign/blob/c29e33316d8b53ee6a608ac2b5b91fda91dec0ee/appinfo/info.xml#L13

truncated phrase, please complete sentence

Reported at Transifex.

**Comment by vitormattos** [comment]
Fixed by #3781

**Comment by vitormattos** [comment]
Thanks a lot by your help!

**Comment by vitormattos** [comment]
I saw now that isn't the same.

I will fix this.

**Comment by vitormattos** [comment]
Will be fixed by this:
- https://github.com/LibreSign/site/pull/300
And after I will add the link to this post.
