### ISSUE TITLE
Problem with Accented Characters in Signer Name

### ISSUE THREAD

**Issue by ssebech** [LibreSign/libresign#3787]
**Describe the bug**
When there are certain accented characters in the Signer name like š, č, ň, ž, the requested signer cannot be added (saved). Clicking the "Save" button does nothing. After removing such characters from the Signer name and clicking "Save" the dialog advances, i.e. the "Next" button appears.

**To Reproduce**
- Open the "LibreSign" tab of a document details in the Files view or start the Request Signatures dialog and Choose from Files.
- Then the "Add signer" button appears which clicking shows the dialog to choose or search the requested signer.
- If the Signer name field contains any of the problematic accented characters it is not possible to advance further - clicking the "Save" button does nothing.
- If there is no such character clicking the "Save" button works and the dialog advances to "Next".
- The problematic characters are š, č, ň, ž including their upper-case versions, both commonly used in Slovak language.

**Expected behavior**
Any characters in the Signer name should be accepted and the dialog should go on.

**Environment information (please complete the following information):**
 - OS: server: Linux Debian, client: Windows 11
 - Browser: both Firefox and Chrome
 - LibreSign Version: 9.3.2 and 10.0.2
 - Nextcloud Server Version: 29.0.7 and 30.0.0

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
