### ISSUE TITLE
FR: Provide For Use of Visible Signatures When Signing

### ISSUE THREAD

**Issue by cohabo** [LibreSign/libresign#382]
Currently Libresign Doesn't Support the Use of Visible Signatures When Signing
The proposal is to include the creation of a visible signature that will be saved as an image and inserted into a document during the sign request. 

**### CURRENT UI/UX:**
Libresign Application does not support use of visible signatures
![image](https://user-images.githubusercontent.com/2689940/130041679-4742e010-ad11-4c3d-8587-b69570aa5684.png)

**### UPGRADED UI/UX:**
During the Libresign Create Account workflow, the user shall be presented with a widget on their browser which they will use to either, Type, Draw or Upload a Signature. The signature shall be stored in Nextcloud together with the users Digital Certificate.
![image](https://user-images.githubusercontent.com/2689940/130041816-96c9a1a9-8f0f-4a43-895b-ac2f4daf2359.png)

![image](https://user-images.githubusercontent.com/2689940/130042002-c4126c61-f54d-4557-a0b2-5bff04a3be54.png)

**### CURRENT UI/UX:**
Libresign Application does not support the placement of visible signatures on a pdf.
![image](https://user-images.githubusercontent.com/2689940/130042676-140f7f4e-fe91-47cb-b882-76055bb7f61d.png)

**### UPGRADED UI/UX**
During the Libresign Request signature workflow, the user shall upload a pdf document, and the pdf document shall be rendered in the centre iframe of the browser application.
![image](https://user-images.githubusercontent.com/2689940/130051974-c7e3fe93-3fc3-46ea-a065-02a8b1de8ae3.png)

During the Libresign Request signature workflow, the user shall use a Draggable Action Button to drag and place their default visible signature onto the pdf document.
_**SideBar Activity 1:**_
![image](https://user-images.githubusercontent.com/2689940/130050675-c16b4a34-d7fe-484e-81e6-64ce587fbc39.png)

_**SideBar Activity 2:**_
![image](https://user-images.githubusercontent.com/2689940/130050279-614e8b71-1795-47f7-b73f-9f49dac600fa.png)

The following details will be passed to the  jsignpdf visible signature option parameters: The pdf file ID, The signature image, the page Number where the signature has been inserted and the x,y coordinates on the page where it is inserted.

This upgrade will achieve a simple User Experience that includes default visible signatures placed onto a Digitally Signed PDF.

**### Methodology**

- [ ] Code review Libresign PDF Rendering approach
- [ ] Code review of PDFViewer, Vue-pdf browser rendering modules for pdf
- [ ] Code review of jsignpdf signing module
- [ ] Code build
- [ ] Code Test
- [ ] PR to https://github.com/Libresign repo -> Visible Signatures Branch

**Comment by vinicios-gomes** [comment]
Wow very nice.
On behalf of the team, I thank you for your affection and your time available to analyze our project and create this issue. 
I'll be passing it on to the team and let's put a special affection for this feature.

**Comment by upultfs** [comment]
@cohabo is this live now? "Visible Signatures"

**Comment by vitormattos** [comment]
Hi @upultfs this is a WIP feature on main branch. On this week we will create a pre release to test this feature.

**Comment by upultfs** [comment]
@vitormattos  Is there any update with this feature? thanks

**Comment by rishichathuranga** [comment]
@vitormattos Is this features available on the current release? thanks

**Comment by vitormattos** [comment]
Hi @rishichathuranga,
No, only on main branch at this time

**Comment by rishichathuranga** [comment]
@vitormattos Thanks for the reply.

**Comment by upultfs** [comment]
@vitormattos  grate news. could you pls send me the URL? thanks

**Comment by vitormattos** [comment]
@upultfs if you want do a early test, you can make a build on main branch to test before the next release

**Comment by danir-de** [comment]
It would be nice, if you could decide between **_Signing_** and **_Certifying_** a document in the process ([as described here](https://github.com/LibreSign/libresign/issues/617#issuecomment-1057945224) https://github.com/LibreSign/libresign/issues/617#issuecomment-1057945224).

**Comment by vitormattos** [comment]
This (visible signatures) already was implemented, we only need generate a new release from main branch. If you want test before the new release, will be necessary build locally.
