### ISSUE TITLE
Configuring libresign on my docker-composer.yml

### ISSUE THREAD

**Issue by MoffatSD404** [LibreSign/libresign#3828]
So i have been trying to intergrate nextcloud to libresign i have had a hard-time configuring  libresign environment in my docker-compose.yml   
libresign:
    image: ghcr.io/librecodecoop/libresign:latest  
    ports:
      - "8081:8080"
    volumes:
      - nextcloud:/var/www/html
      - ./libresign:/var/www/html/apps-extra/libresign  
    environment:
      LIBRESIGN_DATA_DIR: /var/lib/libresign
      LIBRESIGN_DEBUG: true
      LIBRESIGN_NEXTCLOUD_URL: http://localhost:8080/apps/dashboard/
      LIBRESIGN_NEXTCLOUD_USER: nextcloud 
      LIBRESIGN_NEXTCLOUD_PASSWORD: "Michael@20"
escpecially on the head section it provides the following error 
C:\Users\Administrator\nextcloud-docker>docker-compose up -d
time="2024-10-24T14:55:55+03:00" level=warning msg="C:\\Users\\Administrator\\nextcloud-docker\\docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
[+] Running 1/1
 ✘ libresign Error Head "https://ghcr.io/v2/librecodecoop/libresign/manifests/latest": denied                                                                     29.1s
Error response from daemon: Head "https://ghcr.io/v2/librecodecoop/libresign/manifests/latest": denied kindly assist

**Comment by vitormattos** [comment]
LibreSign haven't a dedicated image, you need to run your Nexrtcloud instance and setup LibreSign from Nextcloud app store.

Do you want to run as developer?

**Comment by MoffatSD404** [comment]
Yes please
Guide me on how i can set up libresign from nextcloud app on docker

**Comment by vitormattos** [comment]
Closing as no more comments here.
