### ISSUE TITLE
Complete reset

### ISSUE THREAD

**Issue by c00ntact** [LibreSign/libresign#383]
I have installed libresign on a test server and while it took me a while I think I got most everything to work.
I accidentally deleted the folder specified in the Config path on the settings screen.
To start fresh, I tried to remove and reinstall the application but the entire root certificate section continues to be greyed out.
How can I reset all settings to start over?

Thank you

**Comment by vitormattos** [comment]
Hi, after saving the certificate settings are not editable, this feature of changing the root certificate has not been implemented yet.

To change, go to the database and do this query to find the LibreSign settings and update the records you want:

```bash
select * from <prefix>appconfig oa where appid = 'libresign' and configkey in ('commonName', 'country', 'organization', 'organizationUnit', 'cfsslUri', 'configPath')
```

If you used any prefix for the tables, you should use it.

On you set only one config value of certificate to null on database, the save button will be enabled. You need change the values on settings form to run creation of json setting file.

**Comment by c00ntact** [comment]
Thank you it worked perfectly
