### ISSUE TITLE
Hardcoded /etc/debian file read attempts unhandled failure when open_basedir in effect

### ISSUE THREAD

**Issue by darkpoetry** [LibreSign/libresign#3985]
**Describe the bug**
Attempts to determine if the OS is Debian accesses files outside the server root and causes complete failure at file selector stage of app use.

**To Reproduce**
- Complete initial install steps
- Attempt to select a file
- Get no error message, just an unresponsive UI. 
- Read logfile, which says:

file_exists(): open_basedir restriction in effect. File(//etc/debian_version) is not within the allowed path(s): (/home/s/.composer:/home/s/web/cloud.s.com/public_html:/home/s/web/cloud.s.com/private:/home/s/web/cloud.s.com/public_shtml:/home/s/tmp:/tmp:/var/www/html:/bin:/usr/bin:/usr/local/bin:/usr/share:/opt) at /home/s/web/cloud.s.com/public_html/apps/libresign/vendor/libresign/whatosami/src/OperatingSystem.php#105 

**Expected behavior**
Determines, assuming it has to, whether it's on Debian using some other means that does not involve attempting to access the filesystem outside the NC instance.
Correctly selects a file and proceeds to next dialog.

Alternatively: Permit the debian / not debian to be a setting if it's necessary so that the app can operate when open_basedir is enabled, which is a key safeguard for securing php based servers.

**Environment information (please complete the following information):**
 - OS: Debian 12.8 with Hestia control panel
 - Browser Firefox
 - LibreSign Version 10.2.0
 - Nextcloud Server Version 30.0.0.2
 - See above

**Additional context**
Similar to #1279

**Comment by vitormattos** [comment]
Will be fixed by this:
https://github.com/LibreSign/whatosami/pull/1

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made changes at this point to check `open_basedir` before retrieve the file.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
