### ISSUE TITLE
Signature stuck at "available for signature"

### ISSUE THREAD

**Issue by Gwylohm** [LibreSign/libresign#4121]
Hello,
I have been experiencing a problem for a few days.
Once the request for a signature has been sent, the signer enters his email address and his authentication code, clicks on "Sign the document" and then nothing happens, he remains stuck on the window indicating "Available for signature" (see below).
What can I do to solve this problem?
Thank you.

![Capture d’écran du 2024-12-12 11-32-52](https://github.com/user-attachments/assets/41c516a9-8498-42d5-bb72-b8da5a2a3885)

**Comment by vitormattos** [comment]
Hi @Gwylohm 

Could you check the follow points?

- If is added any log entry at nextcloud.log file about LibreSign when you access the link to sign the document
- Open the Developer Tools of your browser (commonly pressing F12) and check:
  - console tab, if have any error about LibreSign. And if yes, get the details of the error.
  - network tab, to check if have any request with status code different of 2xx. The status code 4xx and 5xx could point to a problem. You can filter the list by `libresign` to only get the requests to LibreSign API.
- Take a screenshot of Administration Settings > LibreSign. Take care to blur or hide possible data that you don't want to expose. Is important to identify your settings to be possible try to reproduce the same scenario that you made. 
- Describe the scenario to sign that you made. Did you made a sign request to an email that haven't an account or did you made a sign request to an user that have account at your instance?
- Your LibreSign and Nextcloud version
- The operational system that you used to setup your Nextcloud. Yes, this could affect.

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made a lot of improvements.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
