### ISSUE TITLE
Error to sign PDF. []

### ISSUE THREAD

**Issue by govenka** [LibreSign/libresign#431]
Hi :)

All seems to be configures, but i obtain "Error to sign PDF. []" in Nextcloud syslog when i wan't to sign a PDF. 
Here my logs : 

------------------
[02/Nov/2021:16:32:06 +0000] "POST /apps/libresign/api/0.1/sign/file_id/8253 HTTP/1.1" **422** 792 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
------------------

bin/cfssl serve -ca=ca.pem -ca-key=ca-key.pem -address=0.0.0.0  -config config_server.json
2021/11/02 16:39:50 [INFO] Initializing signer
2021/11/02 16:39:50 [WARNING] couldn't initialize ocsp signer: open : no such file or directory
2021/11/02 16:39:50 [INFO] endpoint '/' is enabled
2021/11/02 16:39:50 [INFO] endpoint '/api/v1/cfssl/scan' is enabled
2021/11/02 16:39:50 [INFO] endpoint '/api/v1/cfssl/scaninfo' is enabled
2021/11/02 16:39:50 [INFO] endpoint '/api/v1/cfssl/certadd' is enabled
2021/11/02 16:39:50 [INFO] endpoint '/api/v1/cfssl/sign' is enabled
2021/11/02 16:39:50 [INFO] endpoint '/api/v1/cfssl/authsign' is enabled
2021/11/02 16:39:50 [INFO] endpoint '/api/v1/cfssl/newcert' is enabled
2021/11/02 16:39:50 [INFO] bundler API ready
2021/11/02 16:39:50 [INFO] endpoint '/api/v1/cfssl/bundle' is enabled
2021/11/02 16:39:50 [INFO] endpoint '/api/v1/cfssl/certinfo' is enabled
2021/11/02 16:39:50 [WARNING] endpoint 'revoke' is disabled: cert db not configured (missing -db-config)
2021/11/02 16:39:50 [INFO] endpoint '/api/v1/cfssl/info' is enabled
2021/11/02 16:39:50 [INFO] endpoint '/api/v1/cfssl/gencrl' is enabled
2021/11/02 16:39:50 [INFO] endpoint '/api/v1/cfssl/init_ca' is enabled
2021/11/02 16:39:50 [WARNING] endpoint 'ocspsign' is disabled: signer not initialized
2021/11/02 16:39:50 [INFO] endpoint '/api/v1/cfssl/health' is enabled
2021/11/02 16:39:50 [WARNING] endpoint 'crl' is disabled: cert db not configured (missing -db-config)
2021/11/02 16:39:50 [INFO] setting up key / CSR generator
2021/11/02 16:39:50 [INFO] endpoint '/api/v1/cfssl/newkey' is enabled
2021/11/02 16:39:50 [INFO] Handler set up complete.
2021/11/02 16:39:50 [INFO] Now listening on 0.0.0.0:8888

Any idea where i can find a solution ?

Thx!!

**Comment by obi12341** [comment]
I get exactly the same. Why have you closed it? Do you have a solution for it?

**Comment by vitormattos** [comment]
This message is of JSignPDF.

Can you test define version of JSignPDF on database?

```
occ config:app:set libresign jsignpdf_jar_path --value=/opt/jsignpdf-1.6.5/JSignPdf.jar
```

On master branch this already is fixed but we need finish the implementation of visible elements to create a new release.
