### ISSUE TITLE
how to get CFSSL API URI Root certificate data in root certificate data.

### ISSUE THREAD

**Issue by rohit-lipl** [LibreSign/libresign#439]
i  am triyng to Electronic Signatures module with Nextcloud  using libresign how to get CFSSL API URI and CFSSL setup.

**Comment by vitormattos** [comment]
Hi,
You can found this information on README of this repository:
https://github.com/LibreSign/libresign#with-cfss-server
To setup follow the maintainer of cfssl instructions:
https://github.com/cloudflare/cfssl
The URL depend of your setup. Using the instructions from README and making the setup using Docker, the URL will be `http://cfssl:8888/api/v1/cfssl/` but if using a non Docker setup, you will need use the domain of your cfssl instance with path `/api/v1/cfssl/`

**Comment by rohit-lipl** [comment]
> cfssl
yes i have this repository, but i need How to setup  CFSSL in nextcloud project and if i download the cfssl zip code where is placed in project then what next need to do for electronic signatures module with nextcloud.

**Comment by vitormattos** [comment]
I did the setup using container and described on README of this repository.

When I helped a person doing a handmade setup of CFSSL I saw that only work using the instructions from CFSSL reposistory: https://github.com/cloudflare/cfssl#installation.

When the person used the CFSSL from Ubuntu, don't had success because on package manage of Ubuntu have a outdated version of CFSSL.

**Comment by rohit-lipl** [comment]
> I did the setup using container and described on README of this repository.
> 
> When I helped a person doing a handmade setup of CFSSL I saw that only work using the instructions from CFSSL reposistory: https://github.com/cloudflare/cfssl#installation.
> 
> When the person used the CFSSL from Ubuntu, don't had success because on package manage of Ubuntu have a outdated version of CFSSL.

Can i need to install "golang (Go) " for cfssl.

**Comment by vitormattos** [comment]
Yes.

**Comment by vitormattos** [comment]
I want to remove the dependency of CFSSL from LibreSign replacing by OpenSSL but we need get sponsor to do this and pay the time the work of team.

**Comment by vitormattos** [comment]
Duplicated, see #400
