### ISSUE TITLE
error 401 when I try to generate certificat

### ISSUE THREAD

**Issue by Iwios** [LibreSign/libresign#445]
Hi ,

I have follow the instructions to install ans configure libresign. I have installed cfssl and when I clic on generate certificat file i have an error. If I Open the consol i Can see a 401 error unauthorized.

Can you help me to debug this problem?

Thanks a lot.

**Comment by vitormattos** [comment]
To help is necessary the entire response of request.

**Comment by Iwios** [comment]
Hi, this is a print screen from debug consol

![image](https://user-images.githubusercontent.com/94412636/141973013-5dd785a8-002a-496f-b44e-e1d652ad5e5f.png)

![image](https://user-images.githubusercontent.com/94412636/141973360-3a324c5a-0e23-48b8-98c2-6e68f46d130b.png)

Do you need something else?

**Comment by Iwios** [comment]
This is my ssh consol when I launch cfssl serve:

2021/11/16 11:49:14 [WARNING] couldn't initialize ocsp signer: open : no such file or directory
2021/11/16 11:49:14 [INFO] Setting up '/api/v1/cfssl/scan' endpoint
2021/11/16 11:49:14 [INFO] Setting up '/api/v1/cfssl/gencrl' endpoint
2021/11/16 11:49:14 [INFO] Setting up '/api/v1/cfssl/bundle' endpoint
2021/11/16 11:49:14 [INFO] bundler API ready
2021/11/16 11:49:14 [INFO] Setting up '/api/v1/cfssl/newkey' endpoint
2021/11/16 11:49:14 [INFO] setting up key / CSR generator
2021/11/16 11:49:14 [INFO] Setting up '/api/v1/cfssl/scaninfo' endpoint
2021/11/16 11:49:14 [INFO] Setting up '/api/v1/cfssl/certinfo' endpoint
2021/11/16 11:49:14 [INFO] Setting up '/api/v1/cfssl/revoke' endpoint
2021/11/16 11:49:14 [WARNING] endpoint '/api/v1/cfssl/revoke' is disabled: cert db not configured (missing -db-config)
2021/11/16 11:49:14 [INFO] Setting up '/' endpoint
2021/11/16 11:49:14 [WARNING] endpoint '/' is disabled: could not locate box "static"
2021/11/16 11:49:14 [INFO] Setting up '/api/v1/cfssl/sign' endpoint
2021/11/16 11:49:14 [INFO] Setting up '/api/v1/cfssl/authsign' endpoint
2021/11/16 11:49:14 [WARNING] endpoint '/api/v1/cfssl/authsign' is disabled: {"code":5200,"message":"Invalid or unknown policy"}
2021/11/16 11:49:14 [INFO] Setting up '/api/v1/cfssl/info' endpoint
2021/11/16 11:49:14 [INFO] Setting up '/api/v1/cfssl/newcert' endpoint
2021/11/16 11:49:14 [INFO] Setting up '/api/v1/cfssl/init_ca' endpoint
2021/11/16 11:49:14 [INFO] Setting up '/api/v1/cfssl/ocspsign' endpoint
2021/11/16 11:49:14 [WARNING] endpoint '/api/v1/cfssl/ocspsign' is disabled: signer not initialized
2021/11/16 11:49:14 [INFO] Handler set up complete.
2021/11/16 11:49:14 [INFO] Now listening on 127.0.0.1:8888

**Comment by vitormattos** [comment]
What is the response?

**Comment by vitormattos** [comment]
This endpoint return a json on body of response with the error message.

![Screenshot_20211116_194733](https://user-images.githubusercontent.com/1079143/142078546-ba7473ea-9507-4d79-9cd9-76cda1f29573.png)

**Comment by Iwios** [comment]
Hi, this is the response :+1: 

"Error while writing CSR server file!"

**Comment by vitormattos** [comment]
The user of PHP don't have permission to write the configuration of CFSSL server on CFSSL directory defined on LibreSign configuration.

For example, if the user is www-data you can do a chown to change the owner of directory that you choose to save the CFSSL data. On documentation doing the setup with Docker, the suggested folder is `/cfssl/`

**Comment by vitormattos** [comment]
https://github.com/LibreSign/libresign/blob/57c989ac890a980d4645cac48e34265edc19532c/lib/Handler/CfsslServerHandler.php#L53-L56

**Comment by vitormattos** [comment]
The `$filename` is a concatenation of the path that you put on form and the constant with the name of configuration file `csr_server.json`

**Comment by Iwios** [comment]
I have configur without docker.
 
I'm sure I have make a chown... By the way, after a chown I have another error :+1: 
Client error: `GET http://127.0.0.1:8888/api/v1/cfssl/health` resulted in a `404 Not Found` response:404 page not found

**Comment by vitormattos** [comment]
You don't started the CFSSL server or CFSSL server don't respond on this URL,

**Comment by vitormattos** [comment]
Duplicated, see and interact on #400
