### ISSUE TITLE
Can I sign with a Real sign?

### ISSUE THREAD

**Issue by Iwios** [LibreSign/libresign#460]
Hello,
I have a question : Libresign allowed to add a Real sign scan? Liké docusign ?

**Comment by vitormattos** [comment]
Hi, I don't understood, can you give more info?

**Comment by Iwios** [comment]
It's possible ton incluse to the pdf a jpg or another image file if my real sign?

**Comment by vitormattos** [comment]
This will be possible on next release.

If you can help more the project, we have a Patreon here: https://patreon.com/libresign

**Comment by Iwios** [comment]
Ok thanks you for your answer.
AT this moment my company is starting. I Can't help with my own money. 
But if my company bring money, I Can help you on patreon.

**Comment by Alexis-M51** [comment]
@vitormattos  wanted to know which file type is accepted by your software at the moment

**Comment by vitormattos** [comment]
Hi @Alexis-M51 only PDF for now but I already started to implement support to sign other files generating p7s file. I paused the implementation because I need more patrons to make possible work on more features
