### ISSUE TITLE
report bug after validation of the signature no change of state on the status of the document

### ISSUE THREAD

**Issue by Alexis-M51** [LibreSign/libresign#486]
Hello, 

I am reporting a bug which is the non validation of the signed document status when we enter the iud of the signature:

version: libresign 2.4.5, installation without docker

procedure: - document signature completed
                  - click on the validation link
                  - being in /apps/libresign/validation/ enter iud and message proving that the document is valid
                  - return in /apps/libresign/timeline/sign, document validate is current prending

**Comment by vitormattos** [comment]
Check new version.
