### ISSUE TITLE
error when deleting the document to be signed when the document is no longer available

### ISSUE THREAD

**Issue by Alexis-M51** [LibreSign/libresign#490]
Hello,

I reporte a bug, error when deleting the document to be signed when the document is no longer available

version: libresign 2.4.5, installation without docker

procedure:
- /apps/libresign/
- /apps/libresign/timeline/sign
- click on the document that no longer exists on nextcloud and delete the signature request --> errors=  Error: Request failed with status code 401

**Comment by vitormattos** [comment]
Check new version.
