### ISSUE TITLE
Notify error when I send a request.

### ISSUE THREAD

**Issue by Iwios** [LibreSign/libresign#498]
Hi, 
I have an issue with mail notification.
When I send the request I have an error message 

![image](https://user-images.githubusercontent.com/94412636/146911523-37793f74-4a21-4ab0-9073-8d61a5a8af48.png)

422 Request answer : 
Notify unsigned notification mail could not be sent

**Comment by vitormattos** [comment]
The user need an email to receive the request email to sign.
Define the email on Nextcloud user profile.

**Comment by Iwios** [comment]
Email pas already set

**Comment by vitormattos** [comment]
You configured the email settings on your Nextcloud instance?
I believe that your instance can't send email.

**Comment by Iwios** [comment]
Unfortunatly, m'y SMTP serveur was correctly set. I can send mail

**Comment by vitormattos** [comment]
This error was trigged when haven't success to send email. On nextcloud.log you can read more details.

https://github.com/LibreSign/libresign/blob/3b2b46d4c2b3ff2dee128322b4f36531873a2e94/lib/Service/MailService.php#L87-L88

**Comment by Iwios** [comment]
Sorry, in fact the problem is from m'y postfix configuration.
