### ISSUE TITLE
Error when I try to sign directly on file explorer

### ISSUE THREAD

**Issue by Iwios** [LibreSign/libresign#499]
Hello, 

When I try to sign from the 3 dot on file explorer I have an error but when I try to sign the same PDF from libresign apps the process work fine.

What do you need like informations to try to debug?

**Comment by Iwios** [comment]
I have this error in the debug consol:

<?xml version="1.0" encoding="utf-8"?>

<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">

  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>

  <s:message>File with name //Sans nom 4.pdf could not be located</s:message>

</d:error>

**Comment by Iwios** [comment]
In the Nextcloud Log I have this message :

Error | libresign | Invalid data to validate file

**Comment by Iwios** [comment]
And in the web server log :

"PROPFIND /remote.php/dav/files/User1/Sans%20nom%205.pdf HTTP/2.0" 404 197 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62"

- - [23/Dec/2021:14:33:16 +0100] "PROPFIND /remote.php/dav/files/User1/Sans%20nom%205.pdf HTTP/2.0" 404 197 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62"

- - [23/Dec/2021:14:33:20 +0100] "GET /apps/libresign/api/0.1/file/validate/file_id/5241 HTTP/2.0" 404 148 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62"

**Comment by Iwios** [comment]
@vitormattos  you have no ideas?

**Comment by Iwios** [comment]
I continue to search for error log :

"app":"libresign","method":"GET","url":"/apps/libresign/api/0.1/file/validate/file_id/5792","message":"Invalid data to validate file",
"app":"workflowengine","method":"GET","url":"/apps/libresign/api/0.1/file/validate/file_id/5792","message":"Flow activation: rules were requested for operation Bloquer l'acc\u00e8s \u00e0 un fichier"

**Comment by Iwios** [comment]
After many tries... I understand where is the problem.
The error is when I try to sign a pdf under a folder.

**Comment by Iwios** [comment]
Hi @vitormattos any ideas about this case ?

**Comment by vitormattos** [comment]
I see an error generated by event of app workflowengine, this isn't LibreSign error.
Is only with a specific file?

**Comment by Iwios** [comment]
Hi,
No with any files on subfolder

**Comment by vitormattos** [comment]
Can you generate an example PDF with problem without sensible data and send here?

**Comment by Iwios** [comment]
Yes, but with a blank file from Word, I have an error.

**Comment by vitormattos** [comment]
I don't use Microsoft Word.

**Comment by Iwios** [comment]
Hi,
You can try with this file
[Sans nom 1.pdf](https://github.com/LibreSign/libresign/files/7860595/Sans.nom.1.pdf)

**Comment by Iwios** [comment]
Hi @vitormattos Have you try with my PDF file to sign it into a subfolder ?

**Comment by vitormattos** [comment]
I tested it using:
```
server: 21, 22 and 23
LibreSign: 2.4.5
java --version
     openjdk 11.0.13 2021-10-19
JSignPDF: 1.6.5
cfssl version
     Version: 1.5.0
     Runtime: go1.14.1
```

I didn't find problems

Check if you have JSignPDF version 1.6.5. LibreSign version 2.4.5 (latest stable) is not yet compatible with newer versions of JSignPDF.
https://github.com/LibreSign/libresign/blob/v2.4.5/lib/Handler/JSignPdfHandler.php#L46

**Comment by Iwios** [comment]
Hello this is my configuration :
Jsign : 1.6.5
Java : openjdk 11.0.13
Nextcloud : 34
Cfssl: version dev
Runtime : go1.17.5

**Comment by Iwios** [comment]
Hello, I see the differenc is the cfssl version and go version.

It's possible this is the problem ?

**Comment by Iwios** [comment]
> I tested it using:
> ```
> server: 21, 22 and 23
> LibreSign: 2.4.5
> java --version
>      openjdk 11.0.13 2021-10-19
> JSignPDF: 1.6.5
> cfssl version
>      Version: 1.5.0
>      Runtime: go1.14.1
> ```
> 
> I didn't find problems
> 
> Check if you have JSignPDF version 1.6.5. LibreSign version 2.4.5 (latest stable) is not yet compatible with newer versions of JSignPDF.
> https://github.com/LibreSign/libresign/blob/v2.4.5/lib/Handler/JSignPdfHandler.php#L46

Hi, sorry to be so pressed, but have you an Idea about my problem?

**Comment by vitormattos** [comment]
Hi, I haven't idea. I can't reproduce your problem using your PDF file.

Looking at your logs it looks like a problem about the file that doesn't exist.

Does the problem persist using other files?

**Comment by Iwios** [comment]
Hello,
Yes with differents documents thé problem persist.

In wich log ? I look into the log in web interface of Nextcloud but nogthin

**Comment by Iwios** [comment]
Hi,

Can you give me the right process to install the good version of cfssl ?

**Comment by vitormattos** [comment]
Check new version of LibreSign.
