### ISSUE TITLE
On NC23 it does not seem to work at all ... cannot sign

### ISSUE THREAD

**Issue by rotdrop** [LibreSign/libresign#514]
Hi, thanks a log for sharing this app. However, I am not able to actually sign a single document. This is with the stable23 branch from GH.

What works:
- the app loads fine
- in the setting menu I can create signature and initials
- I can set the signing password, which also implies that the cfssl server is reachable
- I can choose files from the cloud and send out signature requests by email, also the files show up in the "pending" section in the LS-app

However, when I send hit the "sign" button in the app, nothing happens
 
![Screenshot_20220102_174429](https://user-images.githubusercontent.com/1494769/147887314-b864d31f-fb08-4d0e-a645-999f3b4e9682.png)

Also when I click on the link in the email the following page appears in the web-browser with no signing button:

![Screenshot_20220102_174450](https://user-images.githubusercontent.com/1494769/147887338-57b8cfb1-7ed6-4ae8-b828-ae4c303ba4de.png)
 
The "Send reminder" button works just fine.

**Comment by rotdrop** [comment]
In the web-browser's console I see debug messages
```
Ignoring invalid tab 
...
baseURI: "https://anaxagoras.home.claus-justus-heine.de/nextcloud-git/index.php/apps/libresign/f/timeline/sign"
​​```

**Comment by rotdrop** [comment]
Ok. Given that there are numerous commits between the v2.4.5 tag and the stable23 branch I assume that stable-branch is rather a development branch ... ;)

**Comment by vitormattos** [comment]
Hi @rotdrop!
Thanks for your interaction and help!
## About your question
You used the app from branch stable23 and did a build or installed from store?
I believe that if you installed from store and do a refresh on page you will see the preview of PDF and I believe that we already identified this on main branch and fixed.

##  About branches
We did a lot of changes on code to implement visible signatures and now we need do adjusts on UX to launch the next release.

The development is on main branch, when a PR will be created, we make a backport to last LibreSign stable branches . Now, the last stable branches are stable23, stable22 and stable21.
i.e.: on every PR created from any branches to main branch, if is necessary, after the code stay on main branch, we will create a backport to branch stable23, stable22 and stable21. When the release *.5.0 will finished we will generate 3 new releases to LibreSign: 23.5.0 to Nextcloud 23, 22.5.0 to Nextcloud 22 and 21.5.0 to Nextcloud 21.

Following with this way, we every will maintain the development of LibreSign compatible with the next version of server and will be possible maintain the stable releases to all Nextcloud stable releases.

The major number of LibreSign on the next version will follow the Nextcloud server major version.

**Comment by rotdrop** [comment]
Thank you! I had checked the stable23 branch after the installation from the store did not work. Also: PDF preview is not the problem. Its was just that the sign-button was dead. Anyhow, after struggling to find the correct JSignPdf version I have now a working setup with the app-version from the store.

**Comment by vitormattos** [comment]
Only one more consideration: all bugfixes need submitted to main branch and after the PR was merged to main, we will create a backport to stable branches.

**Comment by rotdrop** [comment]
Makes sense.

**Comment by rotdrop** [comment]
But then still: the git-branch "stable23" ATM does not work with the NC stable23 branch. I think there is an issue with the tabs-definitions of the right side-bar. At least the 2.4.5 version from the app-store works with NV v23 (after fingering out version of JSignPdf to use) and there is also a "sign" where in the stable23 branch there is only this "Validate File"-Button. And in the web-browser's console I find notifications about "Ignoring invalid tab" which originate from `@nextcloud/vue` 

![Screenshot_20220103_140016](https://user-images.githubusercontent.com/1494769/147933385-ae2daeb8-b1ab-406a-bc16-38f5ee0dda2b.png)

**Comment by rotdrop** [comment]
Ok, so last I think I understood your development policy: none of the branches is necessarily stable between releases and is in potentially not-working state (as is the case ATM). It is just that the stableXY branch is targeted towards the respective NC branch.  

I'm closing this now. For the record: as far as I understand it signing does not work at the HEAD of all branches ATM, at least if it is meant as "signing using the web-ui". Defining signatures etc. OTOH does work, also placing the signature field on the PDFs.
