### ISSUE TITLE
Error creating new password in document signing

### ISSUE THREAD

**Issue by rishichathuranga** [LibreSign/libresign#515]
Hi, 

There was an error on creating password for signing documents.  Although admin is not able to sign documents on the system.

Nextcloud 22.2.0
![error 1](https://user-images.githubusercontent.com/84203284/147906173-199ccbe9-052d-4bf8-9195-8b58b11c00fe.PNG)
![error 2](https://user-images.githubusercontent.com/84203284/147906181-10fa6a4e-124f-4439-864b-e5d08a9d0160.PNG)

**Comment by vitormattos** [comment]
Look the log on developer tools on your browser and the nextcloud logs on your server. I believe that you will see the problem and I believe that the problem is on unfinished configuration of CFSSL on `settings > administration > LibreSign`.

**Comment by vitormattos** [comment]
Issue solved on last comment
