### ISSUE TITLE
Which version of app for which version of Nextcloud?

### ISSUE THREAD

**Issue by rotdrop** [LibreSign/libresign#516]
Hi,

kind thanks for the app, however: it seems that the "stable23" branch does not work and has rather the status of a development branch? Could this perhaps be clarified?

Kind thanks!

Claus

**Comment by rotdrop** [comment]
It also seems that the 2.4.5 version at least by default needs another version of jsignpdf, which -- reading the source -- seems to be `/opt/jsignpdf-1.6.5/JSignPdf.jar`.

**Comment by rotdrop** [comment]
Ok, after installing the correct version of JSignPDF I was able to sign a file. It may be that I have overlooked the information?

**Comment by vitormattos** [comment]
On branch `stable23`:
https://github.com/LibreSign/libresign/blob/stable23/lib/Handler/JSignPdfHandler.php#L50

I think that I never did a migration with UPDATE when I bumped the version of JSignPdf. Is a good first issue to do on main branch: create a migration to bump to version 2.1 of JSignPdf.

The backend have a good coverage. Before I started to implement support to visible signatures, the coverage with tests was near by 100%, but, unfortunately, now is near by 70%.

If you upgraded the LibreSign from last tag to main or stable23 branch, you will need upgrade the version of JSignPdf on appsetting table:
Example:
```
occ config:app:set libresign jsignpdf_jar_path --value=/opt/jsignpdf-2.0.0/JSignPdf.jar
```
Replace the path by path JsignPdf on your environment.

**Comment by rotdrop** [comment]
Well, my point was rather where to find the documentation for the 2.4.5 release, i.e. the information that by default it needs the 1.6.5 version of JSignPdf (not 2.0.0) . ATM, the stable23 branch does not  work, so currently I am experimenting with the 2.4.5 version from the app-store, which is less fancy (no handwritten signatures images etc.) but works.

Thank you for your good work!

**Comment by vitormattos** [comment]
I don't remember if the release 2.4.5 have the right version of JSignPdf, If don't work, bump to 2.0

Have a small difference of return of JSignPdf output between 1.6.5 and 2.0 and the PHP wrapper to JSignPdf broked, I fixed this on wrapper and on main branch is working fine. If don't work on stable23, maybe is a specific bug on this branch.

> P.S.: The main branch is only compatible with Nextcloud 24.

**Comment by rotdrop** [comment]
Well, the point is that 2.4.5 search for the file `/opt/jsignpdf-1.6.5/JSignPdf.jar` and it is not obvious that this particular version should be installed, or that one has to override the setting on the command-line.

I think it would be worth some lines in the README.md. Perhaps it would be a good idea to include the path into the Admin-Settings for the App?

> P.S.: The main branch is only compatible with Nextcloud 24.

Which means you do not want to use the main branch it if just testing out the app. But it makes of course sense and is in agreement with the branch-layout of NC.

**Comment by vitormattos** [comment]
Excellent suggestions!

The admin settings (`settings > administrations > LibreSign`) of LibreSign need a lot of improvements.

At this time I think the more simple way is put on README but about this specific setting (`jsignpdf_jar_path`) the best way will be put this on a migration. When we launch a new release of LibreSign, the release only will be tested with an specific version of JSignPdf.

An example of new feature without documentation is the integration with playSMS to allow to sign the documents only using SMS token. We go fast to implement this feature on code to one partner and now we need implement the UI and improve the UX.

**Comment by vitormattos** [comment]
@rotdrop can we close this issue? I think all questions are answered.
