### ISSUE TITLE
Remove Qrcode and validation link

### ISSUE THREAD

**Issue by Iwios** [LibreSign/libresign#518]
Hi,
It's possible to remove the qrcode and the validation link After sign?

**Comment by vitormattos** [comment]
Yes, don't fill the validation URL.
The condition to put the qrcode and validation link on footer of document is the existence of validation URL.

**Comment by vitormattos** [comment]
This also is a good feature to implement on `settings > administration > LibreSign`:
* Enable and disable qrcode on footer
* Define the pages to put the qrcode
* make possible put other texts on footer
* preview how the footer will look

But we need funding to implement this changes on frontend.

**Comment by Iwios** [comment]
I'm a integrator and I have a potential customer which is ready to help you with a financial return

**Comment by DaianeAlvesRJ** [comment]
Hi, @Iwios 

To implement this I believe will be necessary investment between 120 to 160 hours. We have a lot of improvements to implement on LibreSign and at this time we need investment near by 4k USD/Euro by month to maintain the development and we haven't at this time.

To speak with our commercial department, send an email to contact@librecode.coop

**Comment by Iwios** [comment]
Ok thanks for the informations.I'm going to speak with my partner. Me or m'y partner take coomntact with you to speak about this project and a potential money investissement.

Have a good day :)

**Comment by DaianeAlvesRJ** [comment]
Thank you very much have a nice day too :-D
