### ISSUE TITLE
Problem with deploying jsign/cfssl using LibreSign documentation

### ISSUE THREAD

**Issue by jehster** [LibreSign/libresign#564]
Hi,

I'm trying to install LibreSign, JSign and CFSSL, based on README. 
I've deployed a standalone server (Ubuntu 20.04, Apache 2.4 with mod-php, PHP 8, MariaDB, Nextcloud 23)
Nextcloud is running good

I've installed LibreSign using occ : 
`sudo -u www-data ./occ app:install libresign
`
Next steps are KO : 
```
occ libresign:install:java
occ libresign:install:jsignpdf
occ libresign:install:cfssl
```

it leads to : 
`There are no commands defined in the "libresign:install" namespace.
`
If you have any idea on what I did wrong, it would be great.

regards

**Comment by vitormattos** [comment]
Hi @jehster, for now you will need do a handmade setup, The commands only will came on next version.

* Setup java
* Download JSignPDF version 1.6.5 and extract on folder /opt
* Install CFSSL on latest versin or download the server and cfssljson binary to your architecture on releases of cfssl and run the steps on file `cfssl/entrypoint.sh`

On release 2.4.5 you will need make a handmade setup.

**Comment by jehster** [comment]
Hi,
Thanks for helping

I still have an error about Java : 
`The command line tool java could not be found`

But I manage to enable app and configure CFSSL. 

I can now send a sign request but I can't set password because there is a tooltip on the password textbox that does not disappear.

**Comment by vitormattos** [comment]
You need install java or download all the jre for your environment. The java is necessary to run JSignPdf. You already did the setup of JSignPdf following the instructions from README? Only one observation about JSignPdf, is necessary use the version 1.6.5, not the 2.0.0

To set password you will need do the setup of CFSSL and configure the root certificate following the instructions on README

**Comment by jehster** [comment]
Java is installed as said on readme

Jsign is installed in 1.6.5 version as you tell me higher 

CFSSL is setup as documented in readme

![image](https://user-images.githubusercontent.com/11501053/151994205-36fb973a-e44f-4d1b-bd5b-7b668076e51e.png)

**Comment by vitormattos** [comment]
You generated the root certificate with success on settings > administration > LibreSign?

**Comment by jehster** [comment]
Yes, certificate has been successfully generated. 

Maybe the problem comes from validation url. Whatever is the url I give, I can save it. I don't have 'Save' button

**Comment by jehster** [comment]
it seems that I have a problem with saving password for signing. I get an error : 
`Erro while creating new password. Contact your administrator.`

![image](https://user-images.githubusercontent.com/11501053/152059561-4cdfdd86-c5fb-4698-b243-ab40405e72d9.png)

I have noticed some error while starting CFSSL : 
`
2022/02/01 22:04:47 [WARNING] couldn't initialize signer: {"code":2000,"message":"Unknown private key error"}
2022/02/01 22:04:47 [DEBUG] Loading issuer cert:
2022/02/01 22:04:47 [WARNING] couldn't initialize ocsp signer: open : no such file or directory
`
I'm trying to find which directory is missing. For the following error, I don't know if it's due to this one or not

`
2022/02/01 22:04:47 [DEBUG] getHandler for authsign
2022/02/01 22:04:47 [WARNING] endpoint 'authsign' is disabled: signer not initialized
[...]
2022/02/01 22:04:47 [DEBUG] getHandler for info
2022/02/01 22:04:47 [WARNING] endpoint 'info' is disabled: signer not initialized
2022/02/01 22:04:47 [DEBUG] getHandler for crl
2022/02/01 22:04:47 [WARNING] endpoint 'crl' is disabled: signer not initialized
[...]
2022/02/01 22:04:47 [DEBUG] getHandler for gencrl
2022/02/01 22:04:47 [WARNING] endpoint 'gencrl' is disabled: signer not initialized
2022/02/01 22:04:47 [DEBUG] getHandler for newcert
2022/02/01 22:04:47 [WARNING] endpoint 'newcert' is disabled: signer not initialized
[...]
2022/02/01 22:04:47 [DEBUG] getHandler for ocspsign
2022/02/01 22:04:47 [WARNING] endpoint 'ocspsign' is disabled: signer not initialized
[...]
2022/02/01 22:04:47 [DEBUG] getHandler for sign
2022/02/01 22:04:47 [WARNING] endpoint 'sign' is disabled: signer not initialized
[...]
2022/02/01 22:04:47 [DEBUG] getHandler for revoke
2022/02/01 22:04:47 [WARNING] endpoint 'revoke' is disabled: cert db not configured (missing -db-config)

`

**Comment by vitormattos** [comment]
Hi, about qrcode is the URL that you put on settings >  administration > LibreSign

The right URL is `cloud.yourdomain.coop/apps/libresign/validation/` changing the domain for your domain.

At this moment LibreSign don't write the date and isn't possible change the footer. 

The validation URL is very big, I recommend to create a rule on your http server to redirect a small URL with the UUID of file to long URL.

About CFSSL, the basic necessary to LibreSign work is OK. At this moment only use the endpoints `health` and `newcert`. I have plans to implement support to CRL and to use endpoint `revoke`

**Comment by jehster** [comment]
Ok, so if I understand well, everything is now ok :)

Last question .. is it possible to reduce the size of the QR code ? :)

thanks for helping

**Comment by vitormattos** [comment]
The qrcode is proportional to size of validation page URL. Now only is possible reduce the size with security creating a very small domain with UUID on path and implementing redirection to full URL of validation page like the example on README.

**Comment by vitormattos** [comment]
Check new version of LibreSign.
