### ISSUE TITLE
Question concerning "prevent users to see details"

### ISSUE THREAD

**Issue by rotdrop** [LibreSign/libresign#660]
Hi,

somehow the commit

4d835495

had the result that also the "requester" can no longer see the details page, at least this is what I am experiencing in my test setup. The relevant changed lines are

https://github.com/LibreSign/libresign/blob/6b3b39cf50824208ecc5068f5f1ce36653bbcfe2/src/Components/File/SignaturesTab.vue#L75-L79

From naively reading the code the lines mean that I have access to the details if I am at the same time the "requester" and one of the signers.

**Comment by vitormattos** [comment]
Replied here:

https://github.com/LibreSign/libresign/commit/4d8354959a10f92477acd305c3ac253fe98f93dd#r67165314
