### ISSUE TITLE
2.5.0 App is not working after build

### ISSUE THREAD

**Issue by rishichathuranga** [LibreSign/libresign#712]
I have build Libresign latest 2.5.0 on a Linux server. Compilation was success. Anyhow I could not enable the app from the next cloud since there was a message that the next cloud version is not compatible with the build.
I have check the AppInfo and the min version is listed as 24. The Nextcloud latest version is 23 and it seem to be a bug.

![image](https://user-images.githubusercontent.com/84203284/158304721-465103c8-b668-43f6-85b6-a9528d6bea3b.png)

Thereafter I have changed the info.xml file for the min version and the app got enabled and now the Libresign is returning a blank screen. No errors on the console. 

![Screenshot 2022-03-15 at 9 44 50 AM](https://user-images.githubusercontent.com/84203284/158305202-7de9cc7d-d7f0-49c3-8dd5-a775aa12b5d8.png)

Blank Screen
![Screenshot 2022-03-15 at 9 48 51 AM](https://user-images.githubusercontent.com/84203284/158308329-e5914c7b-ddef-429c-b63d-1fabb6de31ac.png)

**Comment by vitormattos** [comment]
Hi @rishichathuranga,

We fixed de branches of LibreSign following this relation:

| LibreSign | Nextcloud Server |
|---|---|
| main | master (24) |
| stable23 | stable23 |
| stable22 | stable22 |

The actual stable LibreSign app is compatible with server version 21 and 22.
On the next version we will maintain the stable branches only compatible with the same version of the server.

If you want build the next version of LibreSign to Nextcloud 23, you will need use the branch stable23 of LibreSign.

If you want to develop to LibreSign, you will need use the main branch of LibreSign and work with stable branch of server. When you finish the development, you will need send a PR to main branch and after all CI jobs finish and if is important to send to stable branches (actually stable22 and stable23), we will create backport to respective stable branches.

**Comment by vitormattos** [comment]
Check new version of LibreSign.
