### ISSUE TITLE
Grammatical Corrections

### ISSUE THREAD

**Issue by vinicius73** [LibreSign/libresign#727]
```diff
- "You need to create an account with the same email you received the invitation"
+ "You need to create an account with the same email address you received the invitation"
```

```diff
- "Password for sign document"
+ "Password to sign the document"
```

```diff
- "Able to Sign"
+ "Available for Signature"
```

```diff
- "Element created with success!"
+ "Signature created!"
```

**Comment by meskobalazs** [comment]
I'd add this line too:
https://github.com/LibreSign/libresign/blob/48a1eb5cf49cb1f993dcef69d48c35fe8c5078f1/src/views/Validation.vue#L93

It should say `Document information` as information is uncountable.

**Comment by vitormattos** [comment]
Solved by previous PR.

If you have other suggestions of translation fix, don't hesitate to create an issue or send a PR with your suggestion.
