### ISSUE TITLE
JSignPdf reports successful signing operation, libresign reports error anyway

### ISSUE THREAD

**Issue by czentgraf** [LibreSign/libresign#731]
I am currently preparing an "hand-made" setup with following env:

 * cfssl located at /opt/cfssl
 * jsignpdf located at /opt/jsignpdf-1.6.5

I successfully created an CA and wanted to do an signature. In the Nextcloud UI, is see an error "Internal Error. Contact Administrator".

From the nextcloud log, i see following message:

`{"reqId":"Yk1VuaPqCUZFuwfUgfLJwgAAAAM","level":3,"time":"2022-04-06T08:56:27+00:00","remoteAddr":"XXX","user":"XXX","app":"libresign","method":"POST","url":"/nextcloud/index.php/apps/libresign/api/0.1/sign/file_id/68224","message":"Error to sign PDF. [\"WARN  net.sf.jsignpdf.utils.PropertyProvider$ProperyProviderException: Property file conf\\/conf.properties doesn't exist.\",\"INFO  Checking input and output PDF paths.\",\"INFO  Hole Schl\\u00fcssel Alias\",\"INFO  Verwendet Schl\\u00fcssel: 1\",\"INFO  Lade privaten Schl\\u00fcssel\",\"INFO  Hole Zertifikatskette\",\"INFO  \\u00d6ffne PDF Eingabedatei: \\/mnt\\/nextclouddata\\/tmp\\/e4ff495c26d35efddd2a9b2db98f8222.pdf\",\"INFO  Erzeuge PDF Ausgabedatei: \\/mnt\\/nextclouddata\\/tmp\\/e4ff495c26d35efddd2a9b2db98f8222_signed.pdf\",\"INFO  Erzeuge Signatur\",\"INFO  Setze Zertifizierungsstufe\",\"INFO  Bearbeite (es kann ein wenig l\\u00e4nger dauern) ...\",\"INFO  Schlie\\u00dfe erzeugten PDF Stream\",\"INFO  Fertig: Signatur erfolgreich erzeugt\"]","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.175 Safari/537.36","version":"23.0.3.2"}`

What i tried so far:

 * change jsignpdf to Version 2.0.0
 * switch form java 11 to java 8

What else could go wrong here?

Here my config:
```

        "libresign": {
            "authkey": "8d98962acdfb5745de394f8d6360bae6",
            "cfsslUri": "http:\/\/127.0.0.1:8888\/api\/v1\/cfssl\/",
            "commonName": "CN",
            "configPath": "\/mnt\/nextclouddata\/",
            "country": "DE",
            "enabled": "yes",
            "installed_version": "2.4.5",
            "jsignpdf_jar_path": "\/opt\/jsignpdf-1.6.5\/JSignPdf.jar",
            "jsignpdf_temp_path": "\/mnt\/nextclouddata\/tmp\/",
            "notifyUnsignedUser": "1",
            "organization": "O",
            "organizationUnit": "OU",
            "types": "",
            "validation_site": "https:\/\/next.cloud\/nextcloud\/validate",
            "webhook_authorized": "[\"admin\"]"
        },
```

**Comment by vitormattos** [comment]
Check new version of LibreSign.
