### ISSUE TITLE
Cannot create Password

### ISSUE THREAD

**Issue by Phosub** [LibreSign/libresign#732]
I have LibreSign up and running so far, as that I can request Signatures.
When the Receipient opens the request he ist asked to create a Password. Entering a Password results in an Error Message 
"Error creating new password, please contact the administrator". 

The Browser Console says 
POST https://<Servername>/index.php/apps/libresign/api/0.1/account/signature 401 (Unauthorized)

In the CFSSL ServerI see 

022/04/06 15:21:49 [INFO] Now listening on 0.0.0.0:8888
2022/04/06 15:22:02 [INFO] request for CSR
2022/04/06 15:22:02 [INFO] generate received request
2022/04/06 15:22:02 [INFO] received CSR
2022/04/06 15:22:02 [INFO] generating key: rsa-2048
2022/04/06 15:22:02 [INFO] encoded CSR
2022/04/06 15:22:02 [INFO] signed certificate with serial number 480093466278551917336339019494046806303339437804
2022/04/06 15:22:02 [INFO] 127.0.0.1:54966 - "POST /api/v1/cfssl/newcert" 200

I cannot find where the cause is or where I did wrong with the Setup.

**Comment by vitormattos** [comment]
Check new version of LibreSign.

**Comment by nazarpleskanka** [comment]
Hello,
I have same issue
I am using latest version of Nextcloud and LibreSign
My cfssl server config looks like here:
`
{
  "signing": {
    "default": {
      "expiry": "8760h"
    },
    "profiles": {
      "intermediate_ca": {
        "usages": [
            "signing",
            "digital signature",
            "key encipherment",
            "cert sign",
            "crl sign",
            "server auth",
            "client auth"
        ],
        "expiry": "8760h",
        "ca_constraint": {
            "is_ca": true,
            "max_path_len": 0, 
            "max_path_len_zero": true
        }
      },
      "peer": {
        "usages": [
            "signing",
            "digital signature",
            "key encipherment", 
            "client auth",
            "server auth"
        ],
        "expiry": "8760h"
      },
      "server": {
        "usages": [
          "signing",
          "digital signing",
          "key encipherment",
          "server auth"
        ],
        "expiry": "8760h"
      },
      "client": {
        "usages": [
          "signing",
          "digital signature",
          "key encipherment", 
          "client auth"
        ],
        "expiry": "8760h"
      }
    }
  }
}
`
But when i try to create pass for Sign document , i have 
POST https:///index.php/apps/libresign/api/0.1/account/signature 401 (Unauthorized)

**Comment by pwepwe973** [comment]
hello
I have same issue
I am using latest version of Nextcloud and LibreSign
