### ISSUE TITLE
Impossible to update to 4.1.0

### ISSUE THREAD

**Issue by Iwios** [LibreSign/libresign#784]
After my ohter post, I try tu update the 4.1.0 but I have another error:

I think another error appears:

Exception: Class "TCPDI" not found in file '/var/www/trez/apps/libresign/lib/Handler/TCPDILibresign.php' line 7

/var/www/trez/lib/private/AppFramework/App.php - line 157:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/trez/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/var/www/trez/lib/base.php - line 1008:

OC\Route\Router->match()

/var/www/trez/index.php - line 36:

OC::handleRequest()

Causé par Error: Class "TCPDI" not found

/var/www/trez/lib/composer/composer/ClassLoader.php - line 571:

include()

/var/www/trez/lib/composer/composer/ClassLoader.php - line 428:

Composer\Autoload\includeFile()

/var/www/trez/apps/libresign/lib/Migration/Version2040Date20211027183759.php - line 64:

Composer\Autoload\ClassLoader->loadClass()

/var/www/trez/lib/private/DB/MigrationService.php - line 547:

OCA\Libresign\Migration\Version2040Date20211027183759->postSchemaChange()

/var/www/trez/lib/private/DB/MigrationService.php - line 425:

OC\DB\MigrationService->executeStep()

/var/www/trez/lib/private/legacy/OC_App.php - line 1021:

OC\DB\MigrationService->migrate()

/var/www/trez/lib/private/Installer.php - line 201:

OC_App::updateApp("*** sensiti ... *")

/var/www/trez/apps/settings/lib/Controller/AppSettingsController.php - line 536:

OC\Installer->updateAppstoreApp("*** sensiti ... *")

/var/www/trez/lib/private/AppFramework/Http/Dispatcher.php - line 217:

OCA\Settings\Controller\AppSettingsController->updateApp("*** sensiti ... *")

/var/www/trez/lib/private/AppFramework/Http/Dispatcher.php - line 126:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/trez/lib/private/AppFramework/App.php - line 157:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/trez/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/var/www/trez/lib/base.php - line 1008:

OC\Route\Router->match()

/var/www/trez/index.php - line 36:

OC::handleRequest()

**Comment by vitormattos** [comment]
I think that you didn't update the code. The relation of rows between the backtrace and source of release 4.1.0 is different.

Backtrace:
```
lib/Migration/Version2040Date20211027183759.php - line 64
```
Row 64 in 4.1.0:
https://github.com/LibreSign/libresign/blob/v4.1.0/lib/Migration/Version2040Date20211027183759.php#L64

**Comment by vitormattos** [comment]
Strange, looking on apps.nextcloud.com/apps/libresign the code of package 4.1.0 is right.

Anyway, I will launch a new release now, 4.1.1. I replaced the TCPDI by LibreSign CLI in other part of code but is a part without relation with migration.

**Comment by Alexis-M51** [comment]
Hello, I have the same problem with the update except that I have this error:


index	Exception: json_decode() expects parameter 1 to be string, null given in file '/var/www/nextcloud/apps/libresign/lib/Migration/Version2040Date20211027183759.php' line 100
/var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/nextcloud/lib/private/Route/Router.php - line 298:

OC\AppFramework\App::main()

/var/www/nextcloud/lib/base.php - line 1023:

OC\Route\Router->match()

/var/www/nextcloud/index.php - line 36:

OC::handleRequest()

Causé par TypeError: json_decode() expects parameter 1 to be string, null given
/var/www/nextcloud/apps/libresign/lib/Migration/Version2040Date20211027183759.php - line 100:

json_decode()

/var/www/nextcloud/apps/libresign/lib/Migration/Version2040Date20211027183759.php - line 84:

OCA\Libresign\Migration\Version2040Date20211027183759->getMetadataFromCli()

/var/www/nextcloud/lib/private/DB/MigrationService.php - line 547:

OCA\Libresign\Migration\Version2040Date20211027183759->postSchemaChange()

/var/www/nextcloud/lib/private/DB/MigrationService.php - line 425:

OC\DB\MigrationService->executeStep()

/var/www/nextcloud/lib/private/Installer.php - line 154:

OC\DB\MigrationService->migrate()

/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 451:

OC\Installer->installApp()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:

OCA\Settings\Controller\AppSettingsController->enableApps()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/nextcloud/lib/private/Route/Router.php - line 298:

OC\AppFramework\App::main()

/var/www/nextcloud/lib/base.php - line 1023:

OC\Route\Router->match()

/var/www/nextcloud/index.php - line 36:

OC::handleRequest()

And I would like to know when the 4.1.1 update will be deployed?
