### ISSUE TITLE
tcpdi_parser errors in 4.1.0 and 5.0.0-rc.1

### ISSUE THREAD

**Issue by metheos** [LibreSign/libresign#786]
Running NC 23.0.4 and testing out the new releases

ran  occ libresign:install --all to install the required files

signed files are blank and the following error is logged

{"reqId":"jTEqzrzUKZwjm3ZL8xXY","level":3,"time":"2022-04-27T14:08:08+00:00","remoteAddr":"10.0.1.61","user":"3068AB2C-4706-4705-86D8-F14F237C43DC","app":"PHP","method":"POST",
"url":"/index.php/apps/libresign/api/0.1/sign/register",
"message":"Trying to access array offset on value of type int at /var/www/nextcloud/apps/libresign/vendor/libresign/tcpdi_parser/src/tcpdi_parser.php#261",
"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36","version":"23.0.4.1",
"exception":
{"Exception":"Error","Message":"Trying to access array offset on value of type int at /var/www/nextcloud/apps/libresign/vendor/libresign/tcpdi_parser/src/tcpdi_parser.php#261","Code":0,"Trace":[
{"file":"/var/www/nextcloud/apps/libresign/vendor/libresign/tcpdi_parser/src/tcpdi_parser.php","line":261,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},
{"file":"/var/www/nextcloud/apps/libresign/vendor/libresign/tcpdi_parser/src/tcpdi_parser.php","line":208,"function":"readPages","class":"LibreSign\\TcpdiParser\\tcpdi_parser","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/vendor/iio/libmergepdf/tcpdi/tcpdi.php","line":124,"function":"__construct","class":"LibreSign\\TcpdiParser\\tcpdi_parser","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":236,"function":"setSourceData","class":"TCPDI","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":217,"function":"getFileMetadata","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":167,"function":"saveFile","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Controller/SignFileController.php","line":88,"function":"save","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"requestSign","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},
{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},
{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},
{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}

**Comment by vitormattos** [comment]
Hi @metheos, I identified this problem and started the fix in PR #785 
Unfortunately the TCPDF, the biggest PHP package to work with PDF is very outdated and hard to maintain.
Fortunately we already started to create a CLI application to replace the TCPDF implementations. To your case the LibreSign CLI will solve.
Wait a moment for PR #785 and next release.
