### ISSUE TITLE
Documents in draft mode if selected from nc files app

### ISSUE THREAD

**Issue by tasagore** [LibreSign/libresign#790]
Hi

Don't know if it's a bug (v4.1.0) but if I request a signature from the details of one archive (NC app files) it can't be signed since its status is draft. If I request the same signature from the libresign app it works ok.

The field "status" from oc_libresign_file in the first case is 0, in the second is 1 (I guess 0=draft,1=able to be signed)

**Comment by vitormattos** [comment]
Please, check in the newest version of LibreSign. I will close this issue, if the problem persist, return here and reopen the issue.
