### ISSUE TITLE
The app shows the request signature page although the user is not authorized to that

### ISSUE THREAD

**Issue by tasagore** [LibreSign/libresign#791]
The frontend only should show the request page for those users authorized to request signatures (defined in the app settings)

**Comment by vitormattos** [comment]
Solved at newest release.

## Identification methods

Now is possible to only allow to see the sign page to authenticated accounts. To configure this, go to `Administration Settings > LibreSign`
![Screenshot_20240424_104038](https://github.com/LibreSign/libresign/assets/1079143/0b508fcf-800a-444f-8db0-1fcfdfa7250a)

## Validation URL

Is possible to restrict the access to validation URL only to authenticated users.  To configure this, go to `Administration Settings > LibreSign`

![Screenshot_20240424_104235](https://github.com/LibreSign/libresign/assets/1079143/4de4418b-6695-442f-81b4-b272908ec9c3)
