### ISSUE TITLE
Libresign não funciona para multiplos nextcloud no mesmo host diretamente

### ISSUE THREAD

**Issue by Sollydus** [LibreSign/libresign#792]
Estou com dois nextcloud instalado no mesmo host e preciso configurar e instalar JAVA e JSJSignPDF para os dois
Usei o comando sudo -u www-data php /var/www/nextcloud1/occ libresign:install --jsignpdf --java e funcionou no primeiro nextcloud
Porém tenho outro nextcloud /var/www/nextcloud2/ que preciso também configurar/instalar
Como fazer esse procedimento?

**Comment by vitormattos** [comment]
LibreSign was updated, check if the problem persist in latest version.

I recommend to use with server in version 25.

If the problem persists, reopen this issue with more details.
