### ISSUE TITLE
l10n: Need context for "inform URL"

### ISSUE THREAD

**Issue by rakekniven** [LibreSign/libresign#806]
https://github.com/LibreSign/libresign/blob/6fce103789a5970059d6a1cde8a8f0c1e9445105/lib/Helper/ValidateHelper.php#L116

Not sure If I understand code correctly
Does inform should be replaced with "Invalid"?

**Comment by rakekniven** [comment]
@vitormattos Do you know?

**Comment by vitormattos** [comment]
I think that I understood the question.
File type in this phrase is relative of 3 follow types. This is only to identify the type of file in validation method. This method is used on 3 moments, to request to sign a file, when the requester define a visible image to put together with the signature of a signer and when the signer send the own image file of own signature:
- file to sign
- file defined by requester to make visible in PDF. By example, one logo of company to use together with the signature
- file of signature or initials of user

The 3 other types is about the way to send the file to API:
- using an URL
- using a base64 of file
- using the fileId of existing file of Nextcloud.

Maybe will be best:

Must to define URL or base64 or fileID to send a %s file.

**Comment by meskobalazs** [comment]
In this case, I'd recommend the following:

>  File type: %s. Specify a URL, a base64 string or a fileID.
