### ISSUE TITLE
Signers and datetime beside QR

### ISSUE THREAD

**Issue by tasagore** [LibreSign/libresign#808]
Hi

I suggest to add the name of the signer(s) and date/time, should be useful in the printed version of the document. Also should be fine to make an option to put the validation URL in vertical instead horizontal.

This document can be a example of that: https://www.infosubvenciones.es/bdnstrans/GE/es/convocatoria/815887/document/700936

**Comment by vitormattos** [comment]
This is an undocumented feature but already implemented.

https://github.com/LibreSign/libresign/blob/6fce103789a5970059d6a1cde8a8f0c1e9445105/lib/Handler/Pkcs12Handler.php#L185-L190

Can be configured using:
```
occ config:app:set --help
```

**Comment by tasagore** [comment]
Sorry but...how can I add the signers and datetime? I can see that I can configure footer_first_row and footer_second_row but can't imagine how to add the signer(s) and datetime(s).
