### ISSUE TITLE
Unable to upgrade

### ISSUE THREAD

**Issue by c00ntact** [LibreSign/libresign#811]
During app upgrade process nextcloud enters maintenance mode due to errors thrown by libre sign.

Error message:
An unhandled exception has been thrown:
Error: Call to a member function getAppValue() on null in /var/www/html/nextcloud/apps/libresign/lib/Migration/Version2040Date20211027183759.php:108
Stack trace:
#0 /var/www/html/nextcloud/apps/libresign/lib/Migration/Version2040Date20211027183759.php(67): OCA\Libresign\Migration\Version2040Date20211027183759->getLibesignCli()
#1 /var/www/html/nextcloud/lib/private/DB/MigrationService.php(547): OCA\Libresign\Migration\Version2040Date20211027183759->postSchemaChange()
#2 /var/www/html/nextcloud/lib/private/DB/MigrationService.php(425): OC\DB\MigrationService->executeStep()
#3 /var/www/html/nextcloud/lib/private/legacy/OC_App.php(1011): OC\DB\MigrationService->migrate()
#4 /var/www/html/nextcloud/lib/private/Updater.php(353): OC_App::updateApp()
#5 /var/www/html/nextcloud/lib/private/Updater.php(265): OC\Updater->doAppUpgrade()
#6 /var/www/html/nextcloud/lib/private/Updater.php(133): OC\Updater->doUpgrade()
#7 /var/www/html/nextcloud/core/Command/Upgrade.php(235): OC\Updater->upgrade()
#8 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#9 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#10 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 /var/www/html/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#13 /var/www/html/nextcloud/console.php(99): OC\Console\Application->run()
#14 /var/www/html/nextcloud/occ(11): require_once('...')

**Comment by Alexis-M51** [comment]
Try replacing the code /var/www/html/nextcloud/apps/libresign/lib/Migration/Version2040Date20211027183759.php by github code.

**Comment by vitormattos** [comment]
We need a new version of https://github.com/nextcloud/twofactor_gateway to finish the PR https://github.com/LibreSign/libresign/pull/801 and launch a new release of LibreSign with this bugfix.

**Comment by nvlrdn** [comment]
I Have same issue, can someone help me ?

Error: Call to a member function getAppValue() on null in /var/www/html/nextcloud/apps/libresign/lib/Migration/Version2040Date20211027183759.php:108
Stack trace:
#0 /var/www/html/nextcloud/apps/libresign/lib/Migration/Version2040Date20211027183759.php(67): OCA\Libresign\Migration\Version2040Date20211027183759->getLibesignCli()
#1 /var/www/html/nextcloud/lib/private/DB/MigrationService.php(547): OCA\Libresign\Migration\Version2040Date20211027183759->postSchemaChange()
#2 /var/www/html/nextcloud/lib/private/DB/MigrationService.php(425): OC\DB\MigrationService->executeStep()
#3 /var/www/html/nextcloud/lib/private/legacy/OC_App.php(1021): OC\DB\MigrationService->migrate()
#4 /var/www/html/nextcloud/lib/private/Updater.php(353): OC_App::updateApp()
#5 /var/www/html/nextcloud/lib/private/Updater.php(265): OC\Updater->doAppUpgrade()
#6 /var/www/html/nextcloud/lib/private/Updater.php(133): OC\Updater->doUpgrade()
#7 /var/www/html/nextcloud/core/Command/Upgrade.php(235): OC\Updater->upgrade()
#8 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#9 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#10 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 /var/www/html/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#13 /var/www/html/nextcloud/console.php(99): OC\Console\Application->run()
#14 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#15 {main}

**Comment by c00ntact** [comment]
I have replaced the /var/www/html/nextcloud/apps/libresign/lib/Migration/Version2040Date20211027183759.php file with the current version on git but am experiencing the same errors.

**Comment by torwag** [comment]
Same issue here.... I temporarily deinstalled libresign to get the update running through... just in case someone looks for a quick solution
within the container run
`php occ app:remove libresign`

or from host

`docker run <nextcloudcontainer> php occ app:remove libresign`

if an error about user and permission appears, the executing user needs to be the same as the file owner of the Nextcloud container and volumes (e.g. www-data)
in this case, figure out the username or id and use 
`docker run -u <name> <nextcloudcontainer> php occ app:remove libresign`
or
`docker run -u #<id> <nextcloudcontainer> php occ app:remove libresign`

That said, this is all out of my memory... might be syntactically wrong, but it should give people an idea what to do.

**Comment by vitormattos** [comment]
LibreSign in latest version now have a more easy setup.

I recommend to use with server in version 25.
