### ISSUE TITLE
Unbale to update from 4.1 to 5.1.1

### ISSUE THREAD

**Issue by Iwios** [LibreSign/libresign#813]
Hello, 

I have some difficulties to update libresign.

I have update Nextcloud to 24.0
When I try to update plugin I have this error :

{"reqId":"o1fTSZ9UAsLGjJLFpYsQ","level":3,"time":"2022-05-12T17:52:19+00:00","remoteAddr":"XX.XX.XX.XX","user":"SomeAdmin","app":"jsresourceloader","method":"GET","url":"/settings/apps/update/libresign","message":"Could not find resource js/maintenance.js to load","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0","version":"24.0.0.12"}

**Comment by vitormattos** [comment]
I think this isn't a LibreSign problem. The LibreSign don't have a JS file called maintenance.js. Maybe is a conflict with other app, I don't know.
Do you have more information to reproduce the scenario?

**Comment by vinicius73** [comment]
this log is from https://github.com/nextcloud/server/blob/master/lib/private/Template/JSResourceLocator.php#L105

Based on `resource` info it is not related to libresign.

Please, if you have more information about how this error is related to libresign we will be happy to help you.
