### ISSUE TITLE
I cant sign TCPDF_PARSER ERROR: decodeFilterFlateDecode

### ISSUE THREAD

**Issue by linuxska** [LibreSign/libresign#814]
I cant sign documents

![Screen Shot 2022-05-12 at 14 22 25](https://user-images.githubusercontent.com/399177/168152506-2989441d-0542-4ea6-8a6d-b1e60e643443.png)

I see the logs
{"reqId":"FImjk1H98y1j7ywmCfYa","level":3,"time":"2022-05-12T19:18:34+00:00","remoteAddr":"10.34.6.47","user":"admin","app":"libresign","method":"POST","url":"/index.php/apps/libresign/api/0.1/sign/uuid/dc65c213-efc7-4bf4-8ba7-0d9ca3732dcb","message":"TCPDF_PARSER ERROR: decodeFilterFlateDecode: invalid code","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36","version":"23.0.4.1"}

Fresh instalation of NC

**Comment by vitormattos** [comment]
Are you generating footer for the PDF's?

**Comment by linuxska** [comment]
Hello 

No, i just try to sign.

**Comment by vitormattos** [comment]
LibreSign was updated, check if the problem persist in latest version.

I recommend to use with server in version 25.

If the problem persists, reopen this issue with more details.
