### ISSUE TITLE
Unable to activate libresign plugin

### ISSUE THREAD

**Issue by Iwios** [LibreSign/libresign#815]
Hello,

I'm trying to activate libresign plugin after Nextcloud disable him after update to 4.

This is the log message I have : (Sorry log was very long)

{"reqId":"srXj8NAWLu7rN1yKecr2","level":3,"time":"2022-05-12T20:43:00+00:00","remoteAddr":"XX.XX.XX.XX","user":"SomeUser","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"Undefined variable $install at /opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php#31","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0","version":"24.0.0.12","exception":{"Exception":"Error","Message":"Undefined variable $install at /opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php#31","Code":0,"Trace":[{"file":"/opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php","line":31,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"function":"__construct","class":"OCA\\Libresign\\Migration\\Version2040Date20211027183759","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Utility/SimpleContainer.php","line":108,"function":"newInstanceArgs","class":"ReflectionClass","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Utility/SimpleContainer.php","line":133,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/DB/MigrationService.php","line":498,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/DB/MigrationService.php","line":522,"function":"createInstance","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/opt/sharepoint/lib/private/DB/MigrationService.php","line":425,"function":"executeStep","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/opt/sharepoint/lib/private/Installer.php","line":154,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/opt/sharepoint/apps/settings/lib/Controller/AppSettingsController.php","line":451,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/opt/sharepoint/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/opt/sharepoint/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/opt/sharepoint/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/opt/sharepoint/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"srXj8NAWLu7rN1yKecr2","level":3,"time":"2022-05-12T20:43:00+00:00","remoteAddr":"XX.XX.XX.XX","user":"SomeUser","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"Undefined variable $config at /opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php#32","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0","version":"24.0.0.12","exception":{"Exception":"Error","Message":"Undefined variable $config at /opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php#32","Code":0,"Trace":[{"file":"/opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php","line":32,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"function":"__construct","class":"OCA\\Libresign\\Migration\\Version2040Date20211027183759","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Utility/SimpleContainer.php","line":108,"function":"newInstanceArgs","class":"ReflectionClass","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Utility/SimpleContainer.php","line":133,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/DB/MigrationService.php","line":498,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/DB/MigrationService.php","line":522,"function":"createInstance","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/opt/sharepoint/lib/private/DB/MigrationService.php","line":425,"function":"executeStep","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/opt/sharepoint/lib/private/Installer.php","line":154,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/opt/sharepoint/apps/settings/lib/Controller/AppSettingsController.php","line":451,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/opt/sharepoint/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/opt/sharepoint/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/opt/sharepoint/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/opt/sharepoint/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"srXj8NAWLu7rN1yKecr2","level":3,"time":"2022-05-12T20:43:00+00:00","remoteAddr":"XX.XX.XX.XX","user":"SomeUser","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"Undefined variable $systemConfig at /opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php#33","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0","version":"24.0.0.12","exception":{"Exception":"Error","Message":"Undefined variable $systemConfig at /opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php#33","Code":0,"Trace":[{"file":"/opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php","line":33,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"function":"__construct","class":"OCA\\Libresign\\Migration\\Version2040Date20211027183759","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Utility/SimpleContainer.php","line":108,"function":"newInstanceArgs","class":"ReflectionClass","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Utility/SimpleContainer.php","line":133,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/DB/MigrationService.php","line":498,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/DB/MigrationService.php","line":522,"function":"createInstance","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/opt/sharepoint/lib/private/DB/MigrationService.php","line":425,"function":"executeStep","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/opt/sharepoint/lib/private/Installer.php","line":154,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/opt/sharepoint/apps/settings/lib/Controller/AppSettingsController.php","line":451,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/opt/sharepoint/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/opt/sharepoint/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/opt/sharepoint/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/opt/sharepoint/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"srXj8NAWLu7rN1yKecr2","level":3,"time":"2022-05-12T20:43:00+00:00","remoteAddr":"XX.XX.XX.XX","user":"SomeUser","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"Undefined variable $rootfolder at /opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php#34","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0","version":"24.0.0.12","exception":{"Exception":"Error","Message":"Undefined variable $rootfolder at /opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php#34","Code":0,"Trace":[{"file":"/opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php","line":34,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"function":"__construct","class":"OCA\\Libresign\\Migration\\Version2040Date20211027183759","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Utility/SimpleContainer.php","line":108,"function":"newInstanceArgs","class":"ReflectionClass","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Utility/SimpleContainer.php","line":133,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/DB/MigrationService.php","line":498,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/opt/sharepoint/lib/private/DB/MigrationService.php","line":522,"function":"createInstance","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/opt/sharepoint/lib/private/DB/MigrationService.php","line":425,"function":"executeStep","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/opt/sharepoint/lib/private/Installer.php","line":154,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/opt/sharepoint/apps/settings/lib/Controller/AppSettingsController.php","line":451,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/opt/sharepoint/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/opt/sharepoint/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/opt/sharepoint/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/opt/sharepoint/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"srXj8NAWLu7rN1yKecr2","level":3,"time":"2022-05-12T20:43:00+00:00","remoteAddr":"XX.XX.XX.XX","user":"SomeUser","app":"index","method":"POST","url":"/settings/apps/enable","message":"Call to a member function getAppValue() on null in file '/opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php' line 109","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0","version":"24.0.0.12","exception":{"Exception":"Exception","Message":"Call to a member function getAppValue() on null in file '/opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php' line 109","Code":0,"Trace":[{"file":"/opt/sharepoint/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/opt/sharepoint/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/opt/sharepoint/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/opt/sharepoint/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/opt/sharepoint/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"Error","Message":"Call to a member function getAppValue() on null","Code":0,"Trace":[{"file":"/opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php","line":68,"function":"getLibesignCli","class":"OCA\\Libresign\\Migration\\Version2040Date20211027183759","type":"->"},{"file":"/opt/sharepoint/lib/private/DB/MigrationService.php","line":547,"function":"postSchemaChange","class":"OCA\\Libresign\\Migration\\Version2040Date20211027183759","type":"->"},{"file":"/opt/sharepoint/lib/private/DB/MigrationService.php","line":425,"function":"executeStep","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/opt/sharepoint/lib/private/Installer.php","line":154,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/opt/sharepoint/apps/settings/lib/Controller/AppSettingsController.php","line":451,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/opt/sharepoint/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/opt/sharepoint/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/opt/sharepoint/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/opt/sharepoint/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/opt/sharepoint/apps/libresign/lib/Migration/Version2040Date20211027183759.php","Line":109},"CustomMessage":"--"}}

**Comment by Iwios** [comment]
Hello :)

Non ideas about this bug ?

**Comment by linuxska** [comment]
No, i have the same

**Comment by Iwios** [comment]
Since 25 days, I need to work.
So I've decide to completly remove plugin et install manualy the Libresign v4.1.1.
With JSign 2.1. That's work.
