### ISSUE TITLE
Error sign PDF

### ISSUE THREAD

**Issue by Alexis-M51** [LibreSign/libresign#816]
Hello

I have a problem when signing a pdf, when I type the password to sign it tells me to contact the administrator, here is the log of the problem below

**Environment information:**
 - OS: [Ubuntu 20.4]
 - Browser [Edge]
 - LibreSign Version [5.1.1]
 - Nextcloud Server Version [24]
 - Logs (array_map(): Argument #2 ($array) must be of type array, bool given)

**Comment by iamkhalidbashir** [comment]
Same errorr for me too

**Comment by vitormattos** [comment]
LibreSign was updated, check if the problem persist in latest version.

I recommend to use with server in version 25.

If the problem persists, reopen this issue with more details.
