### ISSUE TITLE
 The document is considered a draft

### ISSUE THREAD

**Issue by Alexis-M51** [LibreSign/libresign#817]
Hello

I found a bug, the bug is that when you want to send a document to sign and you go through the share icon.

https://ibb.co/jvRWV03

Opening the email to sign, the pdf document and consider it as a draft.

https://ibb.co/mHT4dMd

**Environment information:**
 - OS: [Ubuntu 20.4]
 - Browser [Edge]
 - LibreSign Version [5.1.1]
 - Nextcloud Server Version [24]

**Comment by Iwios** [comment]
Same for me.

    OS: [Ubuntu 20.4]
    Browser [Firefox]
    LibreSign Version [4.1.1]
    Nextcloud Server Version [23]

**Comment by vitormattos** [comment]
The status of your file is draft. You don't send the document to sign.
Other point, now have a new version of LibreSign: 5.1.3
