### ISSUE TITLE
Document not available for signature

### ISSUE THREAD

**Issue by RafOSS-br** [LibreSign/libresign#820]
I installed LibreSign according to the README, but whenever I request a file to be signed, the message Document not available for signature appears.

![image](https://user-images.githubusercontent.com/50782362/169839031-542a6427-403e-4500-89a2-a3398ed9fbd8.png)

**Comment by hanserasmus** [comment]
I have this same exact issue. Nextcloud 23.04, PHP 8.0. Installation method was using the "Standalone" steps. Anyone have any idea why this pops up? Document is showing as pending in my Nextcloud instance.

**Comment by vitormattos** [comment]
The status of your file is draft. You don't send the document to sign.
