### ISSUE TITLE
Preview Image of document for "visible signature" not shown

### ISSUE THREAD

**Issue by Bolli84** [LibreSign/libresign#829]
Whenever i try to create an signature, the preview image is not create to show the pages as it would be expected.

To sign the document, it works, however it is a blinded flight through the document.

Which cfssl modules and nextcloud apps have to be enabled to show it correctly?

**Comment by vitormattos** [comment]
LibreSign use ImageMagick extension to generate the preview of all pages and the ImageMagick need to have permission to work with PDF.

Search by policy of ImageMagick and give the rights read and write.

Depending on your setup, the follow command will solve.

```
sed -i'' 's|.*<policy domain="coder".*"PDF".*|<policy domain="coder" rights="read \| write" pattern="PDF" />|g' /etc/ImageMagick-6/policy.xml
```

**Comment by Bolli84** [comment]
Tried it and it works after you restart the php-fpm handler.

**Comment by dreamflasher** [comment]
`sudo service php7.4-fpm restart` does the trick
