### ISSUE TITLE
Signature line and signature drawing

### ISSUE THREAD

**Issue by sollermun** [LibreSign/libresign#843]
It would be nice if the person preparing the document for signature can create signature boxes for each signer, like DocuSign, and also for the signer to draw their own signature. There should also be boxes for initials.

Right now, it looks like documents are digitally signed but there is no signature on the printed pdf.

**Comment by sollermun** [comment]
So I found how to draw a signature and initial on my settings page, but I still have not figured out how to add the signature to the document.

**Comment by vitormattos** [comment]
Steps from app Files:

* Open the LibreSign tab from a PDF file
* Add all that need to sign the document
* Request to sign
* Click in OK on confirmation to go to screen where you will define the places of signatures
* select the page to put the signature
* click in the person that will sign in this page
* Adjust the position of box
* Click in save button to save the position
* Send the document to sign

I wrote this only remembering the steps. Sorry if I wrote any step with a wrong word.
