### ISSUE TITLE
 update that does not update all good packages

### ISSUE THREAD

**Issue by Alexis-M51** [LibreSign/libresign#868]
When I update libreSign, some github packages are not updated, it gives me errors that I have to correct myself by copying the github packages

**Comment by vitormattos** [comment]
could you give more details?

**Comment by Alexis-M51** [comment]
Nextcloud 23.0.3
Server: Ubuntu server 20.04

For example, when I update libresign, the package [PdfParserService.php](https://github.com/LibreSign/libresign/blob/main/lib/Service/PdfParserService.php) was an old package, even after uninstalling and reinstalling LibreSign

**Comment by vitormattos** [comment]
Could you check with newest version of LibreSign?

**Comment by Alexis-M51** [comment]
I checked the new version and I did not find any reported bug but I did not check all the configuration files

**Comment by vitormattos** [comment]
We could close this issue? Solved in the newest version?

**Comment by vitormattos** [comment]
LibreSign was updated, check if the problem persist in latest version.

I recommend to use with server in version 25.

If the problem persists, reopen this issue with more details.
