### ISSUE TITLE
Bug when adding signature

### ISSUE THREAD

**Issue by Alexis-M51** [LibreSign/libresign#888]
**Describe the bug**
pdf display bug when adding signature + signatures are not visible when signing

**To Reproduce**

1    From any file click on the details (three dots at the right)
2    In the LibreSign tab click on "Request"
3    Fill the email and click in "Add"
4    Click on "Submit Request"
5    A popup ask if we want to configure visible signatures, should be a YES/NO dialog but is a OK/CANCEL dialog
6    Click "Ok"
7    this is where I have the bug, the pdf file is not displayed and errors are sent to me, also if I put a signature, the signature is not reproduced at the time of the signature.

**Screenshot**
![signatuer bugue](https://user-images.githubusercontent.com/90853905/184157846-b1ff3013-1353-481f-81ea-7b2e6a6f045c.PNG)

![error log](https://user-images.githubusercontent.com/90853905/184157980-c1b0cc3b-2287-44ab-ac05-2138796fa450.PNG)

**Environment information (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Browser: Chrome, firefox, edge
 - LibreSign Version 5.1.4
 - Nextcloud Server Version 24.0.3

**Additional context**

**Comment by vitormattos** [comment]
Thanks for detailed steps to reproduce the problem.
This scenario is duplicated of #829
Check if the solution of previous issue solve your question and if not, return here and reopen the issue.
