### ISSUE TITLE
Files with "spaces" are not able to be uploaded or signed

### ISSUE THREAD

**Issue by Bolli84** [LibreSign/libresign#890]
Files with spaces in their filesnames are not able to be signed. The File seems not to be available and could not be uploaded nor signed with the libresign app.

Create a document  "123.pdf" which can be signed completely
Create a document "12 3.pdf" which is not able to be signed

**Comment by vitormattos** [comment]
Are you using the latest version of LibreSign? The latest version is:
5.1.4 for Nextcloud 24
4.1.3 for Nextcloud 23

**Comment by vitormattos** [comment]
Closing the issue. Problem already solved

**Comment by Bolli84** [comment]
We are using 5.1.4 with nextcloud 24. 
The issue is not solved for me, since it still appears.
