### ISSUE TITLE
Impossible get metadata from this file. Check if you installed correctly the libresign-cli

### ISSUE THREAD

**Issue by Alexis-M51** [LibreSign/libresign#898]
**Describe the bug**
When I try to send a document I get this error " "Impossible get metadata from this file. Check if you installed correctly the libresign-cli"

**To Reproduce**
- access to second account
- go to libresign or share and libresign
- add email
- send

**Expected behavior**
send email and access the signature finalization document

**Screenshots**
![1](https://user-images.githubusercontent.com/90853905/186356308-9697a209-f90c-457b-b358-10b28c504362.PNG)
![2](https://user-images.githubusercontent.com/90853905/186356327-3918b0d7-7ca2-4443-bcdc-72e02c7bb365.PNG)

**Environment information (please complete the following information):**
- OS: Ubunu Server 20.04
 - Browser Chrome, firefox, edge
 - LibreSign Version 5.1.4
 - Nextcloud Server Version 24.0.4  
 - NO LOGS
 - Logs (get the entries from nextcloud.log related with LibreSign i.e `tail -f data/nextcloud.log|grep libresign`)

**Additional context**
When I had the bug I was on a secondary account with admin rights and signing rights, when I did it with the main account there is no error message.

I redid a test on another server the test and the bug is not present

**Comment by Iwios** [comment]
Hello @Alexis-M51 
Have you again this error ?

I have the same :/

**Comment by Iwios** [comment]
After many try, It's happened when the file I wanna sign is in a subfolder wich share

Same for you @Alexis-M51

**Comment by vitormattos** [comment]
LibreSign was updated, check if the problem persist in latest version.

I recommend to use with server in version 25.

If the problem persists, reopen this issue with more details.
