### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by pixieheath** [LibreSign/libresign#904]
I have installed the NextCloud All in One on a Linode. I am running NC 24.0.4.

I followed the standalone install instructions and then added the LibreSign application via the GUI.

On the host, /mnt/ncdata/appdata_ocnjvnr5owk2/libresign/java-se-8u41-ri/bin/ has permissions of:

-rwxr-xr-x 1 www-data www-data   7981 Jan 15  2020 appletviewer
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 extcheck
-rwxr-xr-x 1 www-data www-data   7973 Jan 15  2020 idlj
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 jar
-rwxr-xr-x 1 www-data www-data   7957 Jan 15  2020 jarsigner
-rwxr-xr-x 1 www-data www-data   7742 Jan 15  2020 java
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 javac
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 javadoc
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 javah
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 javap
-rwxr-xr-x 1 www-data www-data   2806 Jan 15  2020 java-rmi.cgi
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 jcmd
-rwxr-xr-x 1 www-data www-data   8013 Jan 15  2020 jconsole
-rwxr-xr-x 1 www-data www-data   7981 Jan 15  2020 jdb
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 jdeps
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 jhat
-rwxr-xr-x 1 www-data www-data   8109 Jan 15  2020 jinfo
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 jjs
-rwxr-xr-x 1 www-data www-data   8109 Jan 15  2020 jmap
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 jps
-rwxr-xr-x 1 www-data www-data   7965 Jan 15  2020 jrunscript
-rwxr-xr-x 1 www-data www-data   7981 Jan 15  2020 jsadebugd
-rwxr-xr-x 1 www-data www-data   8109 Jan 15  2020 jstack
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 jstat
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 jstatd
-rwxr-xr-x 1 www-data www-data   7957 Jan 15  2020 keytool
-rwxr-xr-x 1 www-data www-data   7949 Jan 15  2020 native2ascii
-rwxr-xr-x 1 www-data www-data   8149 Jan 15  2020 orbd
-rwxr-xr-x 1 www-data www-data   7957 Jan 15  2020 pack200
-rwxr-xr-x 1 www-data www-data   8013 Jan 15  2020 policytool
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 rmic
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 rmid
-rwxr-xr-x 1 www-data www-data   7949 Jan 15  2020 rmiregistry
-rwxr-xr-x 1 www-data www-data   7973 Jan 15  2020 schemagen
-rwxr-xr-x 1 www-data www-data   7941 Jan 15  2020 serialver
-rwxr-xr-x 1 www-data www-data   7981 Jan 15  2020 servertool
-rwxr-xr-x 1 www-data www-data   8181 Jan 15  2020 tnameserv
-rwxr-xr-x 1 www-data www-data 264846 Jan 15  2020 unpack200
-rwxr-xr-x 1 www-data www-data   7957 Jan 15  2020 wsgen
-rwxr-xr-x 1 www-data www-data   7957 Jan 15  2020 wsimport
-rwxr-xr-x 1 www-data www-data   7957 Jan 15  2020 xjc

However when as the admin user I go to sign, I get this error: Error to sign PDF. ["sh: \/mnt\/ncdata\/appdata_ocnjvnr5owk2\/libresign\/java-se-8u41-ri\/bin\/java: not found"]

However as far as I can see, java is in this path and executable. 

The front end just says "Internal Error. Contact Administrator".

Not sure how to progress to resolve this issue or investigate further.

**Comment by vitormattos** [comment]
LibreSign in latest version now have a more easy setup.

I recommend to use with server in version 25.
