### ISSUE TITLE
Signed document can't be validated if the original is deleted

### ISSUE THREAD

**Issue by tasagore** [LibreSign/libresign#906]
Steps:

1) Upload document.pdf and request a signature
2) Sign the document
3) Validate the document, all works ok
4) Delete the original document (not the signed one)
5) Validate the document, it fails (document not found)

I've observed the table oc_libresign_file, there is a field for the signed document (signed_node_id) and another for the original document (node_id). It has sense meanwhile the document is not totally signed but when it's signed the node_id should not be relevant.

When I delete the original document (step 4) the register in the oc_libresing_file is also deleted so the signed document can't be validated, although exists.

Don't know if it's a bug or a standard behavior, but for me has no sense to have a document that can't be validated if the original document does not exists.

**Comment by tasagore** [comment]
I guess you will not have side effects. I've made a small process that do exactly that, when a document status is signed I set node_id to null and after that delete the original document (I need that behavior) and all runs fine.

**Comment by vitormattos** [comment]
Hi @tasagore I already did the fix but don't create a new release of app.
This fix will come maybe in the next weekend.

**Comment by vitormattos** [comment]
Fixed, I recommend to use server with version 25
