### ISSUE TITLE
PDF Preview not working

### ISSUE THREAD

**Issue by Iwios** [LibreSign/libresign#922]
**PDF Preview not working when I try to appose my sign**

**Screenshots**
![image](https://user-images.githubusercontent.com/94412636/190580682-d9594a92-7cea-4f31-9c0f-9c04a2cbaf13.png)

![image](https://user-images.githubusercontent.com/94412636/190580576-0b9fbc1c-8e43-46f6-83ba-cc5e7914c5e8.png)

**Environment information (please complete the following information):**
 - OS: [Linux]
 - Browser [Firefox]
 - LibreSign Version [5.1.4]
 - Nextcloud Server Version [24.0.5]

**Comment by vitormattos** [comment]
Duplicated of #829
